In [6]:
%load_ext autoreload
%autoreload 2
import sys, warnings
sys.path.append('..')
warnings.filterwarnings('ignore')

import pandas as pd
import pm4py
from pm4py.visualization.petri_net import visualizer as pn_visualizer
from python_analysis.functions import (
    read_log, distinct_values, show_trace_rows, unique_analysis, field_summary, traces_without,
    trace_share, start_end, event_code_legend, variants,
    activity_table, equivalence_classes, template, cover_table, assign_classes,
    metric, discover_and_evaluate, compare, combine_partitions, style_stats,
    discover_inductive_noise_twentieth, discover_ilp, discover_powl, discover_inductive_noise_tenth, direct_neighborhood, predecessor_times, successor_times, rejection_timeline
)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [7]:
##Daten lesen
dom_log_base = read_log('../data/DomesticDeclarations.xes')
int_log_base = read_log('../data/InternationalDeclarations.xes')

dummy = int_log_base["case:Permit id"].ne(int_log_base["case:Permit ID"])
decl_and_permit = int_log_base[~dummy].copy()
international_only_decl = int_log_base[dummy].copy()
declarations_only = pd.concat(
    [dom_log_base.assign(**{"case:source": "domestic"}),
     international_only_decl.assign(**{"case:source": "international"})],
    ignore_index=True,
).sort_values(["case:concept:name", "time:timestamp"], kind="stable", ignore_index=True)

def split_by_trace_start(log, cutoff="2018-01-01"):
    events = log.loc[
        ~log["concept:name"].isin({"Start trip", "End trip"})
    ].copy()

    timestamps = pd.to_datetime(events["time:timestamp"], utc=True)
    starts = timestamps.groupby(events["case:concept:name"]).transform("min")
    before = starts.lt(pd.Timestamp(cutoff, tz="UTC"))

    return events.loc[before].copy(), events.loc[~before].copy()

logs = {
        #Rohdaten
        "domestic": dom_log_base,
        "international": int_log_base,
        #Aufteilung von international nach declaration only ohne Permit und den reinen Permit-enthaltenen Traces
        "int_decl_only": declarations_only,
        "int_permit": decl_and_permit,
        #Zus. ein Stack mit allen Traces nur aus Declaration (ohne Trips)
        "all_decl_only": pd.concat([dom_log_base, declarations_only[~declarations_only["concept:name"].isin({"Start trip", "End trip"})]], ignore_index=True),
        #Trips rausnehmen, weil unabhängig (betrifft nur die internationalen Traces)
        "int_without_trips": int_log_base[~int_log_base["concept:name"].isin({"Start trip", "End trip"})],
        "int_decl_only_without_trips": declarations_only[~declarations_only["concept:name"].isin({"Start trip", "End trip"})],
        "int_permit_without_trips": decl_and_permit[~decl_and_permit["concept:name"].isin({"Start trip", "End trip"})],

        #"domestic_without_D20": dom_log_base[~dom_log_base["concept:name"].eq("Declaration SAVED by EMPLOYEE")],

        #"int_without_trips_or_D20": int_log_base[~int_log_base["concept:name"].isin({"Start trip", "End trip", "Declaration SAVED by EMPLOYEE"})],
        #"int_only_decl": international_only_decl,
        #"int_only_decl_without_trips": international_only_decl[~international_only_decl["concept:name"].isin({"Start trip", "End trip"})],
        #"int_only_decl_without_trips_or_D20": international_only_decl[~international_only_decl["concept:name"].isin({"Start trip", "End trip", "Declaration SAVED by EMPLOYEE"})],


}

# 2017/2018 Split
logs["domestic_before_2018"], logs["domestic_from_2018"] = (
    split_by_trace_start(logs["domestic"])
)

logs["int_without_trips_before_2018"], logs["int_without_trips_from_2018"] = (
    split_by_trace_start(logs["int_without_trips"])
)

logs["int_decl_only_without_trips_before_2018"], logs["int_decl_only_without_trips_from_2018"] = (
    split_by_trace_start(logs["int_decl_only_without_trips"])
)

logs["int_permit_without_trips_before_2018"], logs["int_permit_without_trips_from_2018"] = (
    split_by_trace_start(logs["int_permit_without_trips"])
)

def add_2018_marker(l) :
    source = l.copy()
    source["time:timestamp"] = pd.to_datetime(
        source["time:timestamp"], utc=True
    )
    source["synthetic"] = False

    # Je Trace ein Marker; nur die Trace-Attribute übernehmen.
    case_columns = [c for c in source.columns if c.startswith("case:")]
    markers = (
        source[case_columns]
        .drop_duplicates(subset="case:concept:name")
        .reindex(columns=source.columns)
        .copy()
    )

    markers["concept:name"] = "Jahresgrenze 2018"
    markers["time:timestamp"] = pd.Timestamp("2018-01-01", tz="UTC")
    markers["synthetic"] = True

    if "org:resource" in markers.columns:
        markers["org:resource"] = "SYSTEM"
    if "org:role" in markers.columns:
        markers["org:role"] = "UNDEFINED"
    return (
        pd.concat([source, markers], ignore_index=True)
        .sort_values(
            ["case:concept:name", "time:timestamp", "synthetic"],
            ascending=[True, True, False],
            kind="stable",
            ignore_index=True,
        )
    )

logs["int_without_trips_with_year_marker"] = add_2018_marker(logs["int_without_trips"])
logs["dom_with_year_marker"] = add_2018_marker(logs["domestic"])

parsing log, completed traces :: 100%|██████████| 10500/10500 [00:01<00:00, 8818.45it/s]
parsing log, completed traces :: 100%|██████████| 6449/6449 [00:01<00:00, 4238.75it/s]

In [8]:
MINERS = {
    #pm4py
    "inductivepn": pm4py.discover_petri_net_inductive,
    "alphapn": pm4py.discover_petri_net_alpha,
    "alphapluspn": pm4py.discover_petri_net_alpha_plus,
    "heuristicpn": pm4py.discover_petri_net_heuristics,
    "inductivebpmn": pm4py.discover_bpmn_inductive,
    #functions (auch pm4py, aber noch mit Mini-Wrapper für dieses invoke-Ding da unten)
    "inductive_noise10pn": discover_inductive_noise_tenth,
    "inductive_noise20pn": discover_inductive_noise_twentieth,
    "ilppn": discover_ilp,
    "powl": discover_powl,
}

models, stats = {}, {}
for name, log in logs.items():
    for miner, discover in MINERS.items():
        models[(name, miner)], stats[(name, miner)] = discover_and_evaluate(name, miner, discover, log)
table = pd.DataFrame(stats)
table.columns.names = ["Log", "Verfahren"]
display(style_stats(compare(table)))
display(style_stats(table))

domestic_inductivepn_model.pkl: aus Cache geladen
domestic_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_alphapn_model.pkl: aus Cache geladen
domestic_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_alphapluspn_model.pkl: aus Cache geladen
domestic_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_heuristicpn_model.pkl: aus Cache geladen
domestic_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_inductivebpmn_model.pkl: aus Cache geladen
domestic_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_inductive_noise10pn_model.pkl: aus Cache geladen
domestic_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_inductive_noise20pn_model.pkl: aus Cache geladen
domestic_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_ilppn_model.pkl: aus Cache geladen
domestic_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_powl_model.pkl: aus Cache geladen
domestic_powl_stats.pkl: 19 aus Cache, neu berechnet: –
international_inductivepn_model.pkl: aus Cache geladen
international_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
international_alphapn_model.pkl: aus Cache geladen
international_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
international_alphapluspn_model.pkl: aus Cache geladen
international_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
international_heuristicpn_model.pkl: aus Cache geladen
international_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
international_inductivebpmn_model.pkl: aus Cache geladen
international_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
international_inductive_noise10pn_model.pkl: aus Cache geladen
international_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
international_inductive_noise20pn_model.pkl: aus Cache geladen
international_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
international_ilppn_model.pkl: aus Cache geladen
international_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
international_powl_model.pkl: aus Cache geladen
international_powl_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_inductivepn_model.pkl: aus Cache geladen
int_decl_only_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_alphapn_model.pkl: aus Cache geladen
int_decl_only_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_alphapluspn_model.pkl: aus Cache geladen
int_decl_only_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_heuristicpn_model.pkl: aus Cache geladen
int_decl_only_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_inductivebpmn_model.pkl: aus Cache geladen
int_decl_only_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_inductive_noise10pn_model.pkl: aus Cache geladen
int_decl_only_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_inductive_noise20pn_model.pkl: aus Cache geladen
int_decl_only_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_ilppn_model.pkl: aus Cache geladen
int_decl_only_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_powl_model.pkl: aus Cache geladen
int_decl_only_powl_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_inductivepn_model.pkl: aus Cache geladen
int_permit_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_alphapn_model.pkl: aus Cache geladen
int_permit_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_alphapluspn_model.pkl: aus Cache geladen
int_permit_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_heuristicpn_model.pkl: aus Cache geladen
int_permit_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_inductivebpmn_model.pkl: aus Cache geladen
int_permit_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_inductive_noise10pn_model.pkl: aus Cache geladen
int_permit_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_inductive_noise20pn_model.pkl: aus Cache geladen
int_permit_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_ilppn_model.pkl: aus Cache geladen
int_permit_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_powl_model.pkl: aus Cache geladen
int_permit_powl_stats.pkl: 19 aus Cache, neu berechnet: –
all_decl_only_inductivepn_model.pkl: aus Cache geladen
all_decl_only_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
all_decl_only_alphapn_model.pkl: aus Cache geladen
all_decl_only_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
all_decl_only_alphapluspn_model.pkl: aus Cache geladen
all_decl_only_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
all_decl_only_heuristicpn_model.pkl: aus Cache geladen
all_decl_only_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
all_decl_only_inductivebpmn_model.pkl: aus Cache geladen
all_decl_only_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
all_decl_only_inductive_noise10pn_model.pkl: aus Cache geladen
all_decl_only_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
all_decl_only_inductive_noise20pn_model.pkl: aus Cache geladen
all_decl_only_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
all_decl_only_ilppn_model.pkl: aus Cache geladen
all_decl_only_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
all_decl_only_powl_model.pkl: aus Cache geladen
all_decl_only_powl_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_inductivepn_model.pkl: aus Cache geladen
int_without_trips_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_alphapn_model.pkl: aus Cache geladen
int_without_trips_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_alphapluspn_model.pkl: aus Cache geladen
int_without_trips_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_heuristicpn_model.pkl: aus Cache geladen
int_without_trips_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_inductivebpmn_model.pkl: aus Cache geladen
int_without_trips_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_inductive_noise10pn_model.pkl: aus Cache geladen
int_without_trips_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_inductive_noise20pn_model.pkl: aus Cache geladen
int_without_trips_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_ilppn_model.pkl: aus Cache geladen
int_without_trips_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_powl_model.pkl: aus Cache geladen
int_without_trips_powl_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_inductivepn_model.pkl: aus Cache geladen
int_decl_only_without_trips_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_alphapn_model.pkl: aus Cache geladen
int_decl_only_without_trips_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_alphapluspn_model.pkl: aus Cache geladen
int_decl_only_without_trips_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_heuristicpn_model.pkl: aus Cache geladen
int_decl_only_without_trips_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_inductivebpmn_model.pkl: aus Cache geladen
int_decl_only_without_trips_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_inductive_noise10pn_model.pkl: aus Cache geladen
int_decl_only_without_trips_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_inductive_noise20pn_model.pkl: aus Cache geladen
int_decl_only_without_trips_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_ilppn_model.pkl: aus Cache geladen
int_decl_only_without_trips_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_powl_model.pkl: aus Cache geladen
int_decl_only_without_trips_powl_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_inductivepn_model.pkl: aus Cache geladen
int_permit_without_trips_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_alphapn_model.pkl: aus Cache geladen
int_permit_without_trips_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_alphapluspn_model.pkl: aus Cache geladen
int_permit_without_trips_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_heuristicpn_model.pkl: aus Cache geladen
int_permit_without_trips_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_inductivebpmn_model.pkl: aus Cache geladen
int_permit_without_trips_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_inductive_noise10pn_model.pkl: aus Cache geladen
int_permit_without_trips_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_inductive_noise20pn_model.pkl: aus Cache geladen
int_permit_without_trips_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_ilppn_model.pkl: aus Cache geladen
int_permit_without_trips_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_powl_model.pkl: aus Cache geladen
int_permit_without_trips_powl_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_before_2018_inductivepn_model.pkl: aus Cache geladen
domestic_before_2018_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_before_2018_alphapn_model.pkl: aus Cache geladen
domestic_before_2018_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_before_2018_alphapluspn_model.pkl: aus Cache geladen
domestic_before_2018_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_before_2018_heuristicpn_model.pkl: aus Cache geladen
domestic_before_2018_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_before_2018_inductivebpmn_model.pkl: aus Cache geladen
domestic_before_2018_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_before_2018_inductive_noise10pn_model.pkl: aus Cache geladen
domestic_before_2018_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_before_2018_inductive_noise20pn_model.pkl: aus Cache geladen
domestic_before_2018_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_before_2018_ilppn_model.pkl: aus Cache geladen
domestic_before_2018_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_before_2018_powl_model.pkl: aus Cache geladen
domestic_before_2018_powl_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_from_2018_inductivepn_model.pkl: aus Cache geladen
domestic_from_2018_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_from_2018_alphapn_model.pkl: aus Cache geladen
domestic_from_2018_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_from_2018_alphapluspn_model.pkl: aus Cache geladen
domestic_from_2018_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_from_2018_heuristicpn_model.pkl: aus Cache geladen
domestic_from_2018_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_from_2018_inductivebpmn_model.pkl: aus Cache geladen
domestic_from_2018_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_from_2018_inductive_noise10pn_model.pkl: aus Cache geladen
domestic_from_2018_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_from_2018_inductive_noise20pn_model.pkl: aus Cache geladen
domestic_from_2018_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_from_2018_ilppn_model.pkl: aus Cache geladen
domestic_from_2018_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_from_2018_powl_model.pkl: aus Cache geladen
domestic_from_2018_powl_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_before_2018_inductivepn_model.pkl: aus Cache geladen
int_without_trips_before_2018_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_before_2018_alphapn_model.pkl: aus Cache geladen
int_without_trips_before_2018_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_before_2018_alphapluspn_model.pkl: aus Cache geladen
int_without_trips_before_2018_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_before_2018_heuristicpn_model.pkl: aus Cache geladen
int_without_trips_before_2018_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_before_2018_inductivebpmn_model.pkl: aus Cache geladen
int_without_trips_before_2018_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_before_2018_inductive_noise10pn_model.pkl: aus Cache geladen
int_without_trips_before_2018_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_before_2018_inductive_noise20pn_model.pkl: aus Cache geladen
int_without_trips_before_2018_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_before_2018_ilppn_model.pkl: aus Cache geladen
int_without_trips_before_2018_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_before_2018_powl_model.pkl: aus Cache geladen
int_without_trips_before_2018_powl_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_from_2018_inductivepn_model.pkl: aus Cache geladen
int_without_trips_from_2018_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_from_2018_alphapn_model.pkl: aus Cache geladen
int_without_trips_from_2018_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_from_2018_alphapluspn_model.pkl: aus Cache geladen
int_without_trips_from_2018_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_from_2018_heuristicpn_model.pkl: aus Cache geladen
int_without_trips_from_2018_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_from_2018_inductivebpmn_model.pkl: aus Cache geladen
int_without_trips_from_2018_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_from_2018_inductive_noise10pn_model.pkl: aus Cache geladen
int_without_trips_from_2018_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_from_2018_inductive_noise20pn_model.pkl: aus Cache geladen
int_without_trips_from_2018_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_from_2018_ilppn_model.pkl: aus Cache geladen
int_without_trips_from_2018_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
int_without_trips_from_2018_powl_model.pkl: aus Cache geladen
int_without_trips_from_2018_powl_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_before_2018_inductivepn_model.pkl: aus Cache geladen
int_decl_only_without_trips_before_2018_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_before_2018_alphapn_model.pkl: aus Cache geladen
int_decl_only_without_trips_before_2018_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_before_2018_alphapluspn_model.pkl: aus Cache geladen
int_decl_only_without_trips_before_2018_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_before_2018_heuristicpn_model.pkl: aus Cache geladen
int_decl_only_without_trips_before_2018_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_before_2018_inductivebpmn_model.pkl: aus Cache geladen
int_decl_only_without_trips_before_2018_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_before_2018_inductive_noise10pn_model.pkl: aus Cache geladen
int_decl_only_without_trips_before_2018_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_before_2018_inductive_noise20pn_model.pkl: aus Cache geladen
int_decl_only_without_trips_before_2018_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_before_2018_ilppn_model.pkl: aus Cache geladen
int_decl_only_without_trips_before_2018_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_before_2018_powl_model.pkl: aus Cache geladen
int_decl_only_without_trips_before_2018_powl_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_from_2018_inductivepn_model.pkl: aus Cache geladen
int_decl_only_without_trips_from_2018_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_from_2018_alphapn_model.pkl: aus Cache geladen
int_decl_only_without_trips_from_2018_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_from_2018_alphapluspn_model.pkl: aus Cache geladen
int_decl_only_without_trips_from_2018_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_from_2018_heuristicpn_model.pkl: aus Cache geladen
int_decl_only_without_trips_from_2018_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_from_2018_inductivebpmn_model.pkl: aus Cache geladen
int_decl_only_without_trips_from_2018_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_from_2018_inductive_noise10pn_model.pkl: aus Cache geladen
int_decl_only_without_trips_from_2018_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_from_2018_inductive_noise20pn_model.pkl: aus Cache geladen
int_decl_only_without_trips_from_2018_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_from_2018_ilppn_model.pkl: aus Cache geladen
int_decl_only_without_trips_from_2018_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
int_decl_only_without_trips_from_2018_powl_model.pkl: aus Cache geladen
int_decl_only_without_trips_from_2018_powl_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_before_2018_inductivepn_model.pkl: aus Cache geladen
int_permit_without_trips_before_2018_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_before_2018_alphapn_model.pkl: aus Cache geladen
int_permit_without_trips_before_2018_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_before_2018_alphapluspn_model.pkl: aus Cache geladen
int_permit_without_trips_before_2018_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_before_2018_heuristicpn_model.pkl: aus Cache geladen
int_permit_without_trips_before_2018_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_before_2018_inductivebpmn_model.pkl: aus Cache geladen
int_permit_without_trips_before_2018_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_before_2018_inductive_noise10pn_model.pkl: aus Cache geladen
int_permit_without_trips_before_2018_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_before_2018_inductive_noise20pn_model.pkl: aus Cache geladen
int_permit_without_trips_before_2018_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_before_2018_ilppn_model.pkl: aus Cache geladen
int_permit_without_trips_before_2018_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_before_2018_powl_model.pkl: aus Cache geladen
int_permit_without_trips_before_2018_powl_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_from_2018_inductivepn_model.pkl: aus Cache geladen
int_permit_without_trips_from_2018_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_from_2018_alphapn_model.pkl: aus Cache geladen
int_permit_without_trips_from_2018_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_from_2018_alphapluspn_model.pkl: aus Cache geladen
int_permit_without_trips_from_2018_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_from_2018_heuristicpn_model.pkl: aus Cache geladen
int_permit_without_trips_from_2018_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_from_2018_inductivebpmn_model.pkl: aus Cache geladen
int_permit_without_trips_from_2018_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
int_permit_without_trips_from_2018_inductive_noise10pn_model.pkl: aus Cache geladen

In [9]:
# Log-Gruppen, die jeweils zusammen alle Traces abdecken: raw vs. vorverarbeitet vs. ohne Trips vs. drei Prozesse getrennt
print("[oT] = ohne Trips")
PARTITIONS = {      "raw": ["domestic", "international"],
    "v1 (decl / declAndPermits)": ["all_decl_only", "int_permit"],
    "v2 (dom / int_decl_only / int_permits)": ["domestic", "int_decl_only", "int_permit"],
    "raw [oT]": ["domestic", "int_without_trips"],
    "v1 Duo [oT]": ["all_decl_only", "int_permit_without_trips"],
    "v2 Triple [oT]": ["domestic", "int_decl_only_without_trips", "int_permit_without_trips"],
    "2017/later Split [oT]": ["domestic_before_2018", "domestic_from_2018", "int_without_trips_before_2018", "int_without_trips_from_2018"],
    "2017-Triple-Split [oT]":["domestic_before_2018", "int_decl_only_without_trips_before_2018", "int_permit_without_trips_before_2018"],
    "year_event [oT]": ["dom_with_year_marker", "int_without_trips_with_year_marker"]
    #"getrennt ohne Trips": ["domestic", "decl_and_permit_without_trips", "international_only_decl_without_trips"],
    #"getrennt ohne Trips, ohne SAVE": ["domestic_without_D20", "decl_and_permit_without_trips_or_D20", "international_only_decl_without_trips_or_D20"],
}
combined = combine_partitions(table, logs, PARTITIONS)
display(style_stats(combined[["heuristicpn"]]))
display(style_stats(combined))

[oT] = ohne Trips

In [10]:
##Datenfelder je Trace / Event
field_summary(logs).style \
    .set_caption("Datenfelder je Trace / Event") \
    .set_properties(**{"text-align": "left"})

In [11]:
print("\nDomestic Log (10500):")
for f in dom_log_base.columns:
    print(str(f) + ' : '+ str(len(distinct_values(dom_log_base, f))))

print("\nInternational Log (6449):")
for f in int_log_base.columns:
    print(str(f) + ' : '+ str(len(distinct_values(int_log_base, f))))

Domestic Log (10500):
id : 56437
org:resource : 2
concept:name : 17
time:timestamp : 45403
org:role : 7
case:id : 10500
case:concept:name : 10500
case:BudgetNumber : 1
case:DeclarationNumber : 10049
case:Amount : 8326

International Log (6449):
id : 69073
org:resource : 2
concept:name : 34
time:timestamp : 51270
org:role : 8
case:Permit travel permit number : 5596
case:DeclarationNumber : 6190
case:Amount : 6100
case:RequestedAmount : 6100
case:Permit TaskNumber : 6
case:Permit BudgetNumber : 207
case:OriginalAmount : 6100
case:Permit ProjectNumber : 825
case:concept:name : 6449
case:Permit OrganizationalEntity : 27
case:travel permit number : 6033
case:Permit RequestedBudget : 5259
case:id : 6449
case:Permit ID : 6028
case:Permit id : 5608
case:BudgetNumber : 719
case:Permit ActivityNumber : 145
case:AdjustedAmount : 6101

In [12]:
unique_analysis(int_log_base, ["case:OriginalAmount", "case:AdjustedAmount", "case:RequestedAmount", "case:Amount"])

,case:OriginalAmount,case:AdjustedAmount,case:RequestedAmount,case:Amount,traces
0,0.000000,0.000000,0.000000,0.000000,2251
1,45.654385,45.654385,45.654385,45.654385,73
2,64.473928,64.473928,64.473928,64.473928,72
3,49.536371,49.536371,49.536371,49.536371,58
4,35.122357,35.122357,35.122357,35.122357,52

True     6448
False       1
Name: count, dtype: int64

,case:id,case:OriginalAmount,case:AdjustedAmount,case:RequestedAmount,case:Amount
0,declaration 54434,0.0,100.494292,0.0,0.0

['declaration 54434']

In [45]:
duplicates = dom_log_base["id"].value_counts().loc[lambda counts: counts > 1]
x = duplicates.sum()

print(f"Betroffene Events: {x}")
print(f"Zusätzliche Vorkommen (x - {len(duplicates)}): {x - len(duplicates)}")

Betroffene Events: 0
Zusätzliche Vorkommen (x - 0): 0

In [46]:
duplicates = int_log_base["id"].value_counts().loc[lambda counts: counts > 1]
x = duplicates.sum()

print(f"Betroffene Events: {x}")
print(f"Zusätzliche Vorkommen (x - {len(duplicates)}): {x - len(duplicates)}")

Betroffene Events: 4558
Zusätzliche Vorkommen (x - 1480): 3078

In [48]:
id_analysis = int_log_base.groupby("id").agg(
    events=("id", "size"),
    distinct_timestamps=("time:timestamp", lambda s: s.nunique(dropna=False)),
    distinct_concept_name=("concept:name", lambda s: s.nunique(dropna=False)),
)
duplicates = id_analysis.loc[id_analysis["events"] > 1]
conflicts = duplicates.loc[duplicates["distinct_timestamps"] > 1]
x = duplicates["events"].sum()

print(f"Mehrfach vorkommende IDs: {len(duplicates)}")
print(f"Betroffene Events: {x}")
print(f"Zusätzliche Vorkommen: {x - len(duplicates)}")
print(f"IDs mit identischem Timestamp: {len(duplicates) - len(conflicts)}")
print(f"IDs mit unterschiedlichen Timestamps: {len(conflicts)}")

print("Konzeptname")
print(duplicates.loc[duplicates["distinct_concept_name"] > 1])

display(conflicts)

Mehrfach vorkommende IDs: 1480
Betroffene Events: 4558
Zusätzliche Vorkommen: 3078
IDs mit identischem Timestamp: 1480
IDs mit unterschiedlichen Timestamps: 0
Konzeptname
Empty DataFrame
Columns: [events, distinct_timestamps, distinct_concept_name]
Index: []

Empty DataFrame
Columns: [events, distinct_timestamps, distinct_concept_name]
Index: []

In [13]:
#Permit Dummy Analyse 448 Traces
problematic = set(unique_analysis(int_log_base, ["case:Permit id", "case:Permit ID"]))
without_permit = traces_without(int_log_base, "Permit")

print("Traces ohne Permit-Event:", len(without_permit))
print("problematic_traces:", len(problematic))
print("Gleiche Menge:", without_permit == problematic)
print("Nur ohne Permit:", sorted(without_permit - problematic))
print("Nur in problematic_traces:", sorted(problematic - without_permit))

        case:Permit id       case:Permit ID  traces
0  travel permit 73562  travel permit 73562     170
1  travel permit 53343  travel permit 53343     140
2  travel permit 32577  travel permit 32577     115
3  travel permit 45618  travel permit 45618      98
4  travel permit 64232  travel permit 64232      84

True     6001
False     448
Name: count, dtype: int64

                case:id     case:Permit id        case:Permit ID
0    declaration 143637  travel permit 423  travel permit 143640
1    declaration 143644  travel permit 423  travel permit 143647
2    declaration 143578  travel permit 423  travel permit 143581
3    declaration 143585  travel permit 423  travel permit 143588
4    declaration 143657  travel permit 423  travel permit 143660
..                  ...                ...                   ...
443  declaration 147452  travel permit 423  travel permit 147455
444  declaration 147470  travel permit 423  travel permit 147473
445  declaration 147487  travel permit 423  travel permit 147490
446  declaration 147507  travel permit 423  travel permit 147509
447  declaration 147514  travel permit 423  travel permit 147517

[448 rows x 3 columns]

Traces ohne Permit-Event: 448
problematic_traces: 448
Gleiche Menge: True
Nur ohne Permit: []
Nur in problematic_traces: []

In [14]:
# Erst alle Aktivitäten anzeigen
event_types = pd.concat([pd.Series(dom_log_base["concept:name"].values), pd.Series(int_log_base["concept:name"].values)]).drop_duplicates().reset_index(drop=True).sort_values(ignore_index=True)
display(event_types)

# Dann Relationen finden: Wörter mit identischer Aktivitätsmenge bilden eine Äquivalenzklasse
acts = activity_table({"domestic": dom_log_base, "international": int_log_base})
eq = equivalence_classes(acts)
display(eq)

# Masken/Templates je Klasse definieren
eq["template"] = eq["members"].apply(template)
display(eq)

# Unnötige Masken entfernen, weil sie alles/nichts matchen
filtered_groups = eq[~eq["template"].str.fullmatch(r"[\s%]*", na=True)]
display(filtered_groups)

# Gruppen an Masken definieren, die genau jede Aktivität genau einmal abdecken
covers = cover_table(filtered_groups, set(acts.index))
display(covers)

acts["entity_classes"] = assign_classes(acts, filtered_groups, covers.at[1, "ids"])
acts["activity_classes"] = assign_classes(acts, filtered_groups, covers.at[11, "ids"])

0         Declaration APPROVED by ADMINISTRATION
1           Declaration APPROVED by BUDGET OWNER
2           Declaration APPROVED by PRE_APPROVER
3             Declaration APPROVED by SUPERVISOR
4         Declaration FINAL_APPROVED by DIRECTOR
5       Declaration FINAL_APPROVED by SUPERVISOR
6     Declaration FOR_APPROVAL by ADMINISTRATION
7       Declaration FOR_APPROVAL by PRE_APPROVER
8         Declaration FOR_APPROVAL by SUPERVISOR
9         Declaration REJECTED by ADMINISTRATION
10          Declaration REJECTED by BUDGET OWNER
11              Declaration REJECTED by DIRECTOR
12              Declaration REJECTED by EMPLOYEE
13               Declaration REJECTED by MISSING
14          Declaration REJECTED by PRE_APPROVER
15            Declaration REJECTED by SUPERVISOR
16                 Declaration SAVED by EMPLOYEE
17             Declaration SUBMITTED by EMPLOYEE
18                                      End trip
19                               Payment Handled
20             Permit APPROVED by ADMINISTRATION
21               Permit APPROVED by BUDGET OWNER
22               Permit APPROVED by PRE_APPROVER
23                 Permit APPROVED by SUPERVISOR
24             Permit FINAL_APPROVED by DIRECTOR
25           Permit FINAL_APPROVED by SUPERVISOR
26             Permit REJECTED by ADMINISTRATION
27               Permit REJECTED by BUDGET OWNER
28                   Permit REJECTED by DIRECTOR
29                   Permit REJECTED by EMPLOYEE
30                    Permit REJECTED by MISSING
31               Permit REJECTED by PRE_APPROVER
32                 Permit REJECTED by SUPERVISOR
33                  Permit SUBMITTED by EMPLOYEE
34                               Request Payment
35                                 Send Reminder
36                                    Start trip
dtype: str

,words,n,domestic,international,members
0,MEMBER STAFF,34,36353,59347,"[Declaration APPROVED by ADMINISTRATION, Decla..."
1,BY,32,36353,46449,"[Declaration APPROVED by ADMINISTRATION, Decla..."
2,DECLARATION,18,36353,25890,"[Declaration APPROVED by ADMINISTRATION, Decla..."
3,PERMIT,14,0,20559,"[Permit APPROVED by ADMINISTRATION, Permit APP..."
4,REJECTED,14,2846,4192,"[Declaration REJECTED by ADMINISTRATION, Decla..."
5,APPROVED,8,11707,15516,"[Declaration APPROVED by ADMINISTRATION, Decla..."
6,EMPLOYEE,7,13031,29338,"[Declaration REJECTED by EMPLOYEE, Declaration..."
7,SUPERVISOR,7,10425,12535,"[Declaration APPROVED by SUPERVISOR, Declarati..."
8,ADMINISTRATION,5,9155,11508,"[Declaration APPROVED by ADMINISTRATION, Decla..."
9,PRE_APPROVER,5,772,1255,"[Declaration APPROVED by PRE_APPROVER, Declara..."
10,BUDGET OWNER,4,2879,3668,"[Declaration APPROVED by BUDGET OWNER, Declara..."
11,DIRECTOR,4,0,897,"[Declaration FINAL_APPROVED by DIRECTOR, Decla..."
12,FINAL_APPROVED,4,10131,12312,"[Declaration FINAL_APPROVED by DIRECTOR, Decla..."
13,FOR_APPROVAL,3,3,0,"[Declaration FOR_APPROVAL by ADMINISTRATION, D..."
14,SYSTEM UNDEFINED,3,20084,12804,"[Payment Handled, Request Payment, Send Reminder]"
15,MISSING,2,91,146,"[Declaration REJECTED by MISSING, Permit REJEC..."
16,PAYMENT,2,20084,12370,"[Payment Handled, Request Payment]"
17,SUBMITTED,2,11531,14354,"[Declaration SUBMITTED by EMPLOYEE, Permit SUB..."
18,TRIP,2,0,12898,"[End trip, Start trip]"
19,END,1,0,6449,[End trip]
20,HANDLED,1,10044,6187,[Payment Handled]
21,REMINDER SEND,1,0,434,[Send Reminder]
22,REQUEST,1,10040,6183,[Request Payment]
23,SAVED,1,135,75,[Declaration SAVED by EMPLOYEE]
24,START,1,0,6449,[Start trip]

,words,n,domestic,international,members,template
0,MEMBER STAFF,34,36353,59347,"[Declaration APPROVED by ADMINISTRATION, Decla...",%
1,BY,32,36353,46449,"[Declaration APPROVED by ADMINISTRATION, Decla...",% by %
2,DECLARATION,18,36353,25890,"[Declaration APPROVED by ADMINISTRATION, Decla...",Declaration % by %
3,PERMIT,14,0,20559,"[Permit APPROVED by ADMINISTRATION, Permit APP...",Permit % by %
4,REJECTED,14,2846,4192,"[Declaration REJECTED by ADMINISTRATION, Decla...",% REJECTED by %
5,APPROVED,8,11707,15516,"[Declaration APPROVED by ADMINISTRATION, Decla...",% APPROVED by %
6,EMPLOYEE,7,13031,29338,"[Declaration REJECTED by EMPLOYEE, Declaration...",%
7,SUPERVISOR,7,10425,12535,"[Declaration APPROVED by SUPERVISOR, Declarati...",% by SUPERVISOR
8,ADMINISTRATION,5,9155,11508,"[Declaration APPROVED by ADMINISTRATION, Decla...",% by ADMINISTRATION
9,PRE_APPROVER,5,772,1255,"[Declaration APPROVED by PRE_APPROVER, Declara...",% by PRE_APPROVER
10,BUDGET OWNER,4,2879,3668,"[Declaration APPROVED by BUDGET OWNER, Declara...",% by BUDGET OWNER
11,DIRECTOR,4,0,897,"[Declaration FINAL_APPROVED by DIRECTOR, Decla...",% by DIRECTOR
12,FINAL_APPROVED,4,10131,12312,"[Declaration FINAL_APPROVED by DIRECTOR, Decla...",% FINAL_APPROVED by %
13,FOR_APPROVAL,3,3,0,"[Declaration FOR_APPROVAL by ADMINISTRATION, D...",Declaration FOR_APPROVAL by %
14,SYSTEM UNDEFINED,3,20084,12804,"[Payment Handled, Request Payment, Send Reminder]",%
15,MISSING,2,91,146,"[Declaration REJECTED by MISSING, Permit REJEC...",% REJECTED by MISSING
16,PAYMENT,2,20084,12370,"[Payment Handled, Request Payment]",% Payment %
17,SUBMITTED,2,11531,14354,"[Declaration SUBMITTED by EMPLOYEE, Permit SUB...",% SUBMITTED by EMPLOYEE
18,TRIP,2,0,12898,"[End trip, Start trip]",% trip
19,END,1,0,6449,[End trip],End trip
20,HANDLED,1,10044,6187,[Payment Handled],Payment Handled
21,REMINDER SEND,1,0,434,[Send Reminder],Send Reminder
22,REQUEST,1,10040,6183,[Request Payment],Request Payment
23,SAVED,1,135,75,[Declaration SAVED by EMPLOYEE],Declaration SAVED by EMPLOYEE
24,START,1,0,6449,[Start trip],Start trip

,words,n,domestic,international,members,template
1,BY,32,36353,46449,"[Declaration APPROVED by ADMINISTRATION, Decla...",% by %
2,DECLARATION,18,36353,25890,"[Declaration APPROVED by ADMINISTRATION, Decla...",Declaration % by %
3,PERMIT,14,0,20559,"[Permit APPROVED by ADMINISTRATION, Permit APP...",Permit % by %
4,REJECTED,14,2846,4192,"[Declaration REJECTED by ADMINISTRATION, Decla...",% REJECTED by %
5,APPROVED,8,11707,15516,"[Declaration APPROVED by ADMINISTRATION, Decla...",% APPROVED by %
7,SUPERVISOR,7,10425,12535,"[Declaration APPROVED by SUPERVISOR, Declarati...",% by SUPERVISOR
8,ADMINISTRATION,5,9155,11508,"[Declaration APPROVED by ADMINISTRATION, Decla...",% by ADMINISTRATION
9,PRE_APPROVER,5,772,1255,"[Declaration APPROVED by PRE_APPROVER, Declara...",% by PRE_APPROVER
10,BUDGET OWNER,4,2879,3668,"[Declaration APPROVED by BUDGET OWNER, Declara...",% by BUDGET OWNER
11,DIRECTOR,4,0,897,"[Declaration FINAL_APPROVED by DIRECTOR, Decla...",% by DIRECTOR
12,FINAL_APPROVED,4,10131,12312,"[Declaration FINAL_APPROVED by DIRECTOR, Decla...",% FINAL_APPROVED by %
13,FOR_APPROVAL,3,3,0,"[Declaration FOR_APPROVAL by ADMINISTRATION, D...",Declaration FOR_APPROVAL by %
15,MISSING,2,91,146,"[Declaration REJECTED by MISSING, Permit REJEC...",% REJECTED by MISSING
16,PAYMENT,2,20084,12370,"[Payment Handled, Request Payment]",% Payment %
17,SUBMITTED,2,11531,14354,"[Declaration SUBMITTED by EMPLOYEE, Permit SUB...",% SUBMITTED by EMPLOYEE
18,TRIP,2,0,12898,"[End trip, Start trip]",% trip
19,END,1,0,6449,[End trip],End trip
20,HANDLED,1,10044,6187,[Payment Handled],Payment Handled
21,REMINDER SEND,1,0,434,[Send Reminder],Send Reminder
22,REQUEST,1,10040,6183,[Request Payment],Request Payment
23,SAVED,1,135,75,[Declaration SAVED by EMPLOYEE],Declaration SAVED by EMPLOYEE
24,START,1,0,6449,[Start trip],Start trip

,n_groups,groups,ids
0,4,"[BY, PAYMENT, TRIP, REMINDER SEND]","[1, 16, 18, 21]"
1,5,"[DECLARATION, PERMIT, PAYMENT, TRIP, REMINDER ...","[2, 3, 16, 18, 21]"
2,5,"[BY, TRIP, HANDLED, REMINDER SEND, REQUEST]","[1, 18, 20, 21, 22]"
3,5,"[BY, PAYMENT, END, REMINDER SEND, START]","[1, 16, 19, 21, 24]"
4,6,"[DECLARATION, PERMIT, TRIP, HANDLED, REMINDER ...","[2, 3, 18, 20, 21, 22]"
5,6,"[DECLARATION, PERMIT, PAYMENT, END, REMINDER S...","[2, 3, 16, 19, 21, 24]"
6,6,"[BY, END, HANDLED, REMINDER SEND, REQUEST, START]","[1, 19, 20, 21, 22, 24]"
7,7,"[DECLARATION, PERMIT, END, HANDLED, REMINDER S...","[2, 3, 19, 20, 21, 22, 24]"
8,9,"[REJECTED, APPROVED, FINAL_APPROVED, FOR_APPRO...","[4, 5, 12, 13, 16, 17, 18, 21, 23]"
9,10,"[REJECTED, APPROVED, FINAL_APPROVED, FOR_APPRO...","[4, 5, 12, 13, 17, 18, 20, 21, 22, 23]"
10,10,"[REJECTED, APPROVED, FINAL_APPROVED, FOR_APPRO...","[4, 5, 12, 13, 16, 17, 19, 21, 23, 24]"
11,11,"[REJECTED, APPROVED, FINAL_APPROVED, FOR_APPRO...","[4, 5, 12, 13, 17, 19, 20, 21, 22, 23, 24]"

Menschliche Bewertung:
| index | Ausschlusskriterium? | Bewertung |
|-------|----------------------|-----------|
| 0     |Ja, durch "By" -> Permit/Declaration fälschlich zusammengefasst||
| 1     || Sehr gut, genau 5 Gruppen für 5 "menschlich erkennbare" [Entitätsklassen]|
| 2     |Ja, durch "By", s. (1)||
| 3     |Ja, durch "By", s. (1)||
| 4     |Ja, Aktivitäten und Entitäten werden gemischt "End, Payment, Start, etc."||
| 5     ||Ist okay, im Prinzip Gruppe (1), aber mit extra Aufteilung von "%Payment%-Aktivitäten"|
| 6     |Ja, durch "By", s. (1)||
| 7     |s. (4)||
| 8     |Ja, ähnlich zu (4) werden Aktivitäten und Entitäten gemischt (Trip, Reminder, Payment + Submitted, Approval...)||
| 9     |Ja, ebenfalls noch Entitäten (Trip) und Aktivitäten||
| 10    ||Fast gültig, es verbleiben noch eine zwei, die eineindeutige Aktivität (Reminder Send) und Payment, sonst alles abgedeckt|
| 11    ||Teilt wie bei (1) zu (5) nur das Payment auf, wodurch aber nur noch eine Entität mit eindeutiger Aktivität verbleibt -> Perfekt als [Aktivitätenklassen]|


Es verbleibt noch ein Problem, was nicht direkt ersichtlich ist: Durch die vorhandenen Matcher entsteht bei der Betrachtung der Events in ihren Klassen ein Informationsverlust bei den Aktivitäten durch den Matcher "%APPROVED %", deswegen darf beim Aufbau der Klassen nicht einfach eine Transformation zu Buchstaben erfolgen, sondern der Unterstrich beibehalten werden.

Die entstehenden Gruppierungen zeigen außerdem direkt auf, dass eindeutige Unterscheidungen nach Akteuren nicht zu einer allgemeingültigen bijektiven Abbildung führen und demnach nicht **eigenständig** geeignet für isolierte Analysen sind.

In [15]:
acts.groupby(["entity_classes", "activity_classes"])[["domestic", "international"]].sum()

                                                  domestic  international
entity_classes     activity_classes
% Payment %        Payment Handled                   10044           6187
                   Request Payment                   10040           6183
% trip             End trip                              0           6449
                   Start trip                            0           6449
Declaration % by % % APPROVED by %                   11707           7739
                   % FINAL_APPROVED by %             10131           6291
                   % REJECTED by %                    2846           3686
                   % SUBMITTED by EMPLOYEE           11531           8099
                   Declaration FOR_APPROVAL by %         3              0
                   Declaration SAVED by EMPLOYEE       135             75
Permit % by %      % APPROVED by %                       0           7777
                   % FINAL_APPROVED by %                 0           6021
                   % REJECTED by %                       0            506
                   % SUBMITTED by EMPLOYEE               0           6255
Send Reminder      Send Reminder                         0            434

In [16]:
trace_share(logs, "concept:name")

In [17]:
display(event_code_legend(logs))

with pd.option_context("display.max_colwidth", None):
    for name, log in logs.items():
        table = variants(log)
        print("" + "=" * 70)
        print(f"\n{name}: {len(table)} Abläufe")
        display(table)

                                  concept:name  Code
0       Declaration APPROVED by ADMINISTRATION   D36
1         Declaration APPROVED by BUDGET OWNER   D31
2         Declaration APPROVED by PRE_APPROVER   D32
3           Declaration APPROVED by SUPERVISOR   D35
4       Declaration FINAL_APPROVED by DIRECTOR  D5✅7
5     Declaration FINAL_APPROVED by SUPERVISOR  D5✅5
6   Declaration FOR_APPROVAL by ADMINISTRATION   D46
7     Declaration FOR_APPROVAL by PRE_APPROVER   D42
8       Declaration FOR_APPROVAL by SUPERVISOR   D45
9       Declaration REJECTED by ADMINISTRATION  D5❌6
10        Declaration REJECTED by BUDGET OWNER  D5❌1
11            Declaration REJECTED by DIRECTOR  D5❌7
12            Declaration REJECTED by EMPLOYEE  D5❌0
13             Declaration REJECTED by MISSING  D5❌_
14        Declaration REJECTED by PRE_APPROVER  D5❌2
15          Declaration REJECTED by SUPERVISOR  D5❌5
16               Declaration SAVED by EMPLOYEE   D20
17           Declaration SUBMITTED by EMPLOYEE   D10
18                                    End trip   T⬇️
19                           Jahresgrenze 2018    ??
20                             Payment Handled    🪙❗
21           Permit APPROVED by ADMINISTRATION   P36
22             Permit APPROVED by BUDGET OWNER   P31
23             Permit APPROVED by PRE_APPROVER   P32
24               Permit APPROVED by SUPERVISOR   P35
25           Permit FINAL_APPROVED by DIRECTOR  P5✅7
26         Permit FINAL_APPROVED by SUPERVISOR  P5✅5
27           Permit REJECTED by ADMINISTRATION  P5❌6
28             Permit REJECTED by BUDGET OWNER  P5❌1
29                 Permit REJECTED by DIRECTOR  P5❌7
30                 Permit REJECTED by EMPLOYEE  P5❌0
31                  Permit REJECTED by MISSING  P5❌_
32             Permit REJECTED by PRE_APPROVER  P5❌2
33               Permit REJECTED by SUPERVISOR  P5❌5
34                Permit SUBMITTED by EMPLOYEE   P10
35                             Request Payment    🪙❓
36                               Send Reminder     📨
37                                  Start trip   T⬆️

======================================================================

domestic: 99 Abläufe

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,4618,4618/10500 [43.98%],7.036163,9.377247
1,D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2473,2473/10500 [23.55%],10.232593,12.550129
2,D10 > D5✅5 > 🪙❓ > 🪙❗,1392,1392/10500 [13.26%],6.311244,9.891926
3,D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,575,575/10500 [5.48%],7.310475,9.966244
4,D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,345,345/10500 [3.29%],11.104410,18.572796
...,...,...,...,...,...
94,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > D5❌_,1,1/10500 [0.01%],47.078252,47.078252
95,D10 > D5✅5 > D5❌_ > D10 > D5❌5 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],16.774051,16.774051
96,D20 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],20.088113,20.088113
97,D10 > D42 > D5❌_,1,1/10500 [0.01%],4.134444,4.134444
98,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0,1,1/10500 [0.01%],0.166782,0.166782

======================================================================

international: 753 Abläufe

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,P10 > P36 > P5✅5 > T⬆️ > T⬇️ > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1369,1369/6449 [21.23%],55.201076,65.890619
1,P10 > P36 > P31 > P5✅5 > T⬆️ > T⬇️ > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,624,624/6449 [9.68%],65.215041,73.488146
2,P10 > P5✅5 > T⬆️ > T⬇️ > D10 > D5✅5 > 🪙❓ > 🪙❗,361,361/6449 [5.60%],49.279769,60.630991
3,P10 > P36 > P5✅5 > T⬆️ > T⬇️ > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,311,311/6449 [4.82%],66.053854,72.777658
4,P10 > P32 > P5✅5 > T⬆️ > T⬇️ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,254,254/6449 [3.94%],53.708142,63.440400
...,...,...,...,...,...
748,P10 > P36 > P35 > P5✅7 > T⬆️ > D10 > D5❌6 > T⬇️ > D5❌0 > D10 > D36 > D35 > D5✅7 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],83.750255,83.750255
749,T⬆️ > T⬇️ > P10 > P36 > P35 > P5✅7 > D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5✅7 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],24.729826,24.729826
750,P10 > P36 > P31 > P35 > P5✅7 > T⬆️ > T⬇️ > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],267.198241,267.198241
751,P10 > P36 > P5✅5 > T⬆️ > T⬇️ > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5✅7 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],99.312488,99.312488
752,T⬆️ > T⬇️ > P10 > P5❌6 > P5❌0 > P10 > P5❌6 > P5❌0 > P10 > P36 > P31 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],30.729861,30.729861

======================================================================

int_decl_only: 154 Abläufe

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,4618,4618/10948 [42.18%],7.036163,9.377247
1,D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2473,2473/10948 [22.59%],10.232593,12.550129
2,D10 > D5✅5 > 🪙❓ > 🪙❗,1392,1392/10948 [12.71%],6.311244,9.891926
3,D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,575,575/10948 [5.25%],7.310475,9.966244
4,D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,345,345/10948 [3.15%],11.104410,18.572796
...,...,...,...,...,...
149,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > D5❌_,1,1/10948 [0.01%],47.078252,47.078252
150,D10 > D5✅5 > D5❌_ > D10 > D5❌5 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/10948 [0.01%],16.774051,16.774051
151,D20 > 🪙❓ > 🪙❗,1,1/10948 [0.01%],20.088113,20.088113
152,D10 > D42 > D5❌_,1,1/10948 [0.01%],4.134444,4.134444
153,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0,1,1/10948 [0.01%],0.166782,0.166782

======================================================================

int_permit: 698 Abläufe

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,P10 > P36 > P5✅5 > T⬆️ > T⬇️ > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1369,1369/6001 [22.81%],55.201076,65.890619
1,P10 > P36 > P31 > P5✅5 > T⬆️ > T⬇️ > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,624,624/6001 [10.40%],65.215041,73.488146
2,P10 > P5✅5 > T⬆️ > T⬇️ > D10 > D5✅5 > 🪙❓ > 🪙❗,361,361/6001 [6.02%],49.279769,60.630991
3,P10 > P36 > P5✅5 > T⬆️ > T⬇️ > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,311,311/6001 [5.18%],66.053854,72.777658
4,P10 > P32 > P5✅5 > T⬆️ > T⬇️ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,254,254/6001 [4.23%],53.708142,63.440400
...,...,...,...,...,...
693,P10 > P36 > P35 > P5✅7 > T⬆️ > D10 > D5❌6 > T⬇️ > D5❌0 > D10 > D36 > D35 > D5✅7 > 🪙❓ > 🪙❗,1,1/6001 [0.02%],83.750255,83.750255
694,T⬆️ > T⬇️ > P10 > P36 > P35 > P5✅7 > D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5✅7 > 🪙❓ > 🪙❗,1,1/6001 [0.02%],24.729826,24.729826
695,P10 > P36 > P31 > P35 > P5✅7 > T⬆️ > T⬇️ > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/6001 [0.02%],267.198241,267.198241
696,P10 > P36 > P5✅5 > T⬆️ > T⬇️ > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5✅7 > 🪙❓ > 🪙❗,1,1/6001 [0.02%],99.312488,99.312488
697,T⬆️ > T⬇️ > P10 > P5❌6 > P5❌0 > P10 > P5❌6 > P5❌0 > P10 > P36 > P31 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/6001 [0.02%],30.729861,30.729861

======================================================================

all_decl_only: 133 Abläufe

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,D10 > D10 > D36 > D36 > D5✅5 > D5✅5 > 🪙❓ > 🪙❓ > 🪙❗ > 🪙❗,4618,4618/10948 [42.18%],7.036163,9.377247
1,D10 > D10 > D36 > D36 > D31 > D31 > D5✅5 > D5✅5 > 🪙❓ > 🪙❓ > 🪙❗ > 🪙❗,2463,2463/10948 [22.50%],10.242338,12.575511
2,D10 > D10 > D5✅5 > D5✅5 > 🪙❓ > 🪙❓ > 🪙❗ > 🪙❗,1392,1392/10948 [12.71%],6.311244,9.891926
3,D10 > D10 > D32 > D32 > D5✅5 > D5✅5 > 🪙❓ > 🪙❓ > 🪙❗ > 🪙❗,575,575/10948 [5.25%],7.310475,9.966244
4,D10 > D10 > D5❌6 > D5❌6 > D5❌0 > D5❌0 > D10 > D10 > D36 > D36 > D5✅5 > D5✅5 > 🪙❓ > 🪙❓ > 🪙❗ > 🪙❗,345,345/10948 [3.15%],11.104410,18.572796
...,...,...,...,...,...
128,D10 > D10 > D5❌2 > D5❌2 > D5❌0 > D5❌0 > D10 > D10 > D32 > D32 > D5✅5 > D5✅5 > D5❌_ > D5❌_,1,1/10948 [0.01%],47.078252,47.078252
129,D10 > D10 > D5✅5 > D5✅5 > D5❌_ > D5❌_ > D10 > D10 > D5❌5 > D5❌5 > D5❌0 > D5❌0 > D10 > D10 > D5✅5 > D5✅5 > 🪙❓ > 🪙❓ > 🪙❗ > 🪙❗,1,1/10948 [0.01%],16.774051,16.774051
130,D20 > D20 > 🪙❓ > 🪙❓ > 🪙❗ > 🪙❗,1,1/10948 [0.01%],20.088113,20.088113
131,D10 > D10 > D42 > D42 > D5❌_ > D5❌_,1,1/10948 [0.01%],4.134444,4.134444
132,D10 > D10 > D5❌6 > D5❌6 > D5❌0 > D5❌0 > D10 > D10 > D36 > D36 > D5❌5 > D5❌5 > D5❌0 > D5❌0,1,1/10948 [0.01%],0.166782,0.166782

======================================================================

int_without_trips: 372 Abläufe

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,P10 > P36 > P5✅5 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1776,1776/6449 [27.54%],46.204144,60.051519
1,P10 > P36 > P31 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,877,877/6449 [13.60%],53.018403,63.007440
2,P10 > P5✅5 > D10 > D5✅5 > 🪙❓ > 🪙❗,415,415/6449 [6.44%],45.159745,57.584601
3,P10 > P36 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,374,374/6449 [5.80%],61.949433,69.605391
4,P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,304,304/6449 [4.71%],49.121881,62.414359
...,...,...,...,...,...
367,P10 > P35 > P5✅7 > P5❌_ > P10 > P5✅5 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],80.289248,80.289248
368,P10 > P32 > P5✅5 > D10 > D5❌2 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],110.328472,110.328472
369,P10 > P5❌5 > P5❌0 > P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P31 > P5✅5 > 📨 > 📨 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],127.293843,127.293843
370,P10 > P36 > P31 > P35 > P5✅7 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],267.198241,267.198241
371,P10 > P5❌6 > P5❌0 > P10 > P5❌6 > P5❌0 > P10 > P36 > P31 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],16.272523,16.272523

======================================================================

int_decl_only_without_trips: 112 Abläufe

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,4706,4706/10948 [42.99%],7.049213,9.392638
1,D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2563,2563/10948 [23.41%],10.249965,12.570570
2,D10 > D5✅5 > 🪙❓ > 🪙❗,1503,1503/10948 [13.73%],6.344271,10.004573
3,D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,608,608/10948 [5.55%],7.311412,10.059960
4,D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,374,374/10948 [3.42%],11.119433,18.494576
...,...,...,...,...,...
107,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > D5❌_,1,1/10948 [0.01%],47.078252,47.078252
108,D10 > D5✅5 > D5❌_ > D10 > D5❌5 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/10948 [0.01%],16.774051,16.774051
109,D20 > 🪙❓ > 🪙❗,1,1/10948 [0.01%],20.088113,20.088113
110,D10 > D42 > D5❌_,1,1/10948 [0.01%],4.134444,4.134444
111,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0,1,1/10948 [0.01%],0.166782,0.166782

======================================================================

int_permit_without_trips: 339 Abläufe

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,P10 > P36 > P5✅5 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1776,1776/6001 [29.60%],46.204144,60.051519
1,P10 > P36 > P31 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,877,877/6001 [14.61%],53.018403,63.007440
2,P10 > P5✅5 > D10 > D5✅5 > 🪙❓ > 🪙❗,415,415/6001 [6.92%],45.159745,57.584601
3,P10 > P36 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,374,374/6001 [6.23%],61.949433,69.605391
4,P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,304,304/6001 [5.07%],49.121881,62.414359
...,...,...,...,...,...
334,P10 > P35 > P5✅7 > P5❌_ > P10 > P5✅5 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/6001 [0.02%],80.289248,80.289248
335,P10 > P32 > P5✅5 > D10 > D5❌2 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/6001 [0.02%],110.328472,110.328472
336,P10 > P5❌5 > P5❌0 > P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P31 > P5✅5 > 📨 > 📨 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/6001 [0.02%],127.293843,127.293843
337,P10 > P36 > P31 > P35 > P5✅7 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/6001 [0.02%],267.198241,267.198241
338,P10 > P5❌6 > P5❌0 > P10 > P5❌6 > P5❌0 > P10 > P36 > P31 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/6001 [0.02%],16.272523,16.272523

======================================================================

domestic_before_2018: 41 Abläufe

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,D10 > D5✅5 > 🪙❓ > 🪙❗,1392,1392/2240 [62.14%],6.311244,9.891926
1,D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,575,575/2240 [25.67%],7.310475,9.966244
2,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,57,57/2240 [2.54%],11.006597,17.590916
3,D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,40,40/2240 [1.79%],14.078148,22.539657
4,D20,34,34/2240 [1.52%],0.000000,0.000000
5,D10 > D5❌5 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,22,22/2240 [0.98%],10.602355,14.210254
6,D10 > D5✅5 > D5❌_,21,21/2240 [0.94%],0.807546,10.098172
7,D10 > D5❌5 > D5❌0,18,18/2240 [0.80%],1.284120,7.561087
8,D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,8,8/2240 [0.36%],57.310579,69.399656
9,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,8,8/2240 [0.36%],11.575752,15.939994
10,D10 > D5❌2 > D5❌0,8,8/2240 [0.36%],0.223079,0.825658
11,D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,7,7/2240 [0.31%],24.062037,56.966915
12,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0,6,6/2240 [0.27%],13.714219,17.157407
13,D10 > D5❌2 > D5❌0 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,5,5/2240 [0.22%],29.236400,26.042109
14,D10 > D5❌2 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,4,4/2240 [0.18%],6.982622,15.143860
15,D10 > D5✅5 > 🪙❓ > D5❌_,3,3/2240 [0.13%],29.876088,47.608318
16,D10 > D32 > D5❌5 > D5❌0,3,3/2240 [0.13%],12.084317,11.230015
17,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/2240 [0.09%],170.891238,170.891238
18,D10 > D5❌2 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/2240 [0.09%],222.709676,222.709676
19,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,2,2/2240 [0.09%],15.131047,15.131047
20,D10 > D32 > D5✅5 > D5❌_,2,2/2240 [0.09%],5.980897,5.980897
21,D10 > D5❌5 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,2,2/2240 [0.09%],34.567668,34.567668
22,D10 > D32 > D5✅5 > D5❌_ > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/2240 [0.04%],344.318148,344.318148
23,D10 > D5❌5 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/2240 [0.04%],62.025463,62.025463
24,D10 > D5✅5 > D5❌_ > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/2240 [0.04%],63.305845,63.305845
25,D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/2240 [0.04%],120.320012,120.320012
26,D10 > D5✅5 > D5❌_ > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/2240 [0.04%],172.995660,172.995660
27,D10 > D5✅5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/2240 [0.04%],17.064792,17.064792
28,D10 > D5✅5 > D5❌_ > D10 > D5✅5 > D5❌_,1,1/2240 [0.04%],2.179780,2.179780
29,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/2240 [0.04%],15.096065,15.096065
30,D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/2240 [0.04%],44.173125,44.173125
31,D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/2240 [0.04%],17.377685,17.377685
32,D10 > D5❌2 > D10 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/2240 [0.04%],8.374780,8.374780
33,D10 > D5❌5 > D5❌0 > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/2240 [0.04%],23.052303,23.052303
34,D10 > D45 > D5❌_,1,1/2240 [0.04%],0.793634,0.793634
35,D10 > D5✅5 > D5❌_ > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/2240 [0.04%],16.105567,16.105567
36,D10 > D5❌5 > 🪙❓ > 🪙❗ > D5❌0,1,1/2240 [0.04%],11.871516,11.871516
37,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > D5❌_,1,1/2240 [0.04%],47.078252,47.078252
38,D10 > D5✅5 > D5❌_ > D10 > D5❌5 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/2240 [0.04%],16.774051,16.774051
39,D20 > 🪙❓ > 🪙❗,1,1/2240 [0.04%],20.088113,20.088113
40,D10 > D42 > D5❌_,1,1/2240 [0.04%],4.134444,4.134444

======================================================================

domestic_from_2018: 63 Abläufe

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,4610,4610/8260 [55.81%],7.035087,9.273087
1,D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2472,2472/8260 [29.93%],10.232315,12.537336
2,D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,344,344/8260 [4.16%],11.103507,18.277019
3,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,186,186/8260 [2.25%],15.045718,22.277458
4,D10 > D5❌6 > D5❌0,174,174/8260 [2.11%],0.896800,8.415967
...,...,...,...,...,...
58,D10 > D36 > D5❌5 > D10 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/8260 [0.01%],18.062639,18.062639
59,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/8260 [0.01%],17.043009,17.043009
60,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/8260 [0.01%],27.107708,27.107708
61,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5,1,1/8260 [0.01%],2.101748,2.101748
62,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0,1,1/8260 [0.01%],0.166782,0.166782

======================================================================

int_without_trips_before_2018: 135 Abläufe

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,P10 > P5✅5 > D10 > D5✅5 > 🪙❓ > 🪙❗,415,415/1450 [28.62%],45.159745,57.584601
1,P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,304,304/1450 [20.97%],49.121881,62.414359
2,D10 > D5✅5 > 🪙❓ > 🪙❗,111,111/1450 [7.66%],7.304248,11.417226
3,P10 > P35 > P5✅7 > D10 > D35 > D5✅7 > 🪙❓ > 🪙❗,54,54/1450 [3.72%],86.334045,92.929796
4,P10 > P35 > P5✅7 > D10 > D5✅5 > 🪙❓ > 🪙❗,49,49/1450 [3.38%],77.219618,83.925764
...,...,...,...,...,...
130,P10 > P35 > P5✅7 > P5❌_ > P10 > P35 > P5✅7 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/1450 [0.07%],124.186539,124.186539
131,P10 > P35 > P5✅7 > P5❌_ > P10 > P5✅5 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/1450 [0.07%],80.289248,80.289248
132,P10 > P32 > P5✅5 > D10 > D5❌2 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/1450 [0.07%],110.328472,110.328472
133,P10 > P36 > P35 > P5✅7 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/1450 [0.07%],206.058611,206.058611
134,P10 > P5❌5 > P5❌0 > P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P31 > P5✅5 > 📨 > 📨 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/1450 [0.07%],127.293843,127.293843

======================================================================

int_without_trips_from_2018: 239 Abläufe

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,P10 > P36 > P5✅5 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1776,1776/4999 [35.53%],46.204144,60.051519
1,P10 > P36 > P31 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,877,877/4999 [17.54%],53.018403,63.007440
2,P10 > P36 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,374,374/4999 [7.48%],61.949433,69.605391
3,P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,243,243/4999 [4.86%],64.000451,71.458927
4,P10 > P36 > P5✅5 > 📨 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,141,141/4999 [2.82%],81.036042,89.833088
...,...,...,...,...,...
234,P10 > P36 > P31 > P35 > P5✅7 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/4999 [0.02%],136.199896,136.199896
235,P10 > P36 > P31 > P35 > P5✅7 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5✅7 > 🪙❓ > 🪙❗,1,1/4999 [0.02%],91.938472,91.938472
236,P10 > P36 > P31 > P5❌5 > P5❌0 > P10 > P5❌6 > P5❌0 > P10 > P36 > P31 > P5✅5 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/4999 [0.02%],57.180012,57.180012
237,P10 > P36 > P31 > P35 > P5✅7 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/4999 [0.02%],267.198241,267.198241
238,P10 > P5❌6 > P5❌0 > P10 > P5❌6 > P5❌0 > P10 > P36 > P31 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/4999 [0.02%],16.272523,16.272523

======================================================================

int_decl_only_without_trips_before_2018: 46 Abläufe

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,D10 > D5✅5 > 🪙❓ > 🪙❗,1503,1503/2422 [62.06%],6.344271,10.004573
1,D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,608,608/2422 [25.10%],7.311412,10.059960
2,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,63,63/2422 [2.60%],11.006597,16.917531
3,D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,41,41/2422 [1.69%],14.028715,22.234354
4,D20,39,39/2422 [1.61%],0.000000,0.000000
5,D10 > D5❌5 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,24,24/2422 [0.99%],10.602355,13.746820
6,D10 > D5✅5 > D5❌_,22,22/2422 [0.91%],0.811435,9.676225
7,D10 > D5❌5 > D5❌0,18,18/2422 [0.74%],1.284120,7.561087
8,D10 > D35 > D5✅7 > 🪙❓ > 🪙❗,14,14/2422 [0.58%],10.631001,10.623160
9,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,11,11/2422 [0.45%],12.250579,19.797135
10,D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,8,8/2422 [0.33%],25.683634,54.857743
11,D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,8,8/2422 [0.33%],57.310579,69.399656
12,D10 > D5❌2 > D5❌0,8,8/2422 [0.33%],0.223079,0.825658
13,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0,6,6/2422 [0.25%],13.714219,17.157407
14,D10 > D5❌2 > D5❌0 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,5,5/2422 [0.21%],29.236400,26.042109
15,D10 > D5❌2 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,4,4/2422 [0.17%],6.982622,15.143860
16,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,3,3/2422 [0.12%],11.104352,13.144965
17,D10 > D5✅5 > 🪙❓ > D5❌_,3,3/2422 [0.12%],29.876088,47.608318
18,D10 > D32 > D5❌5 > D5❌0,3,3/2422 [0.12%],12.084317,11.230015
19,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/2422 [0.08%],170.891238,170.891238
20,D10 > D5❌2 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/2422 [0.08%],222.709676,222.709676
21,D10 > D32 > D5✅5 > D5❌_,2,2/2422 [0.08%],5.980897,5.980897
22,D10 > D5❌5 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,2,2/2422 [0.08%],34.567668,34.567668
23,D10 > D32 > D5✅5 > D5❌_ > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/2422 [0.04%],344.318148,344.318148
24,D10 > D5❌5 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/2422 [0.04%],62.025463,62.025463
25,D10 > D5✅5 > D5❌_ > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/2422 [0.04%],63.305845,63.305845
26,D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/2422 [0.04%],120.320012,120.320012
27,D10 > D5✅5 > D5❌_ > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/2422 [0.04%],172.995660,172.995660
28,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/2422 [0.04%],16.255683,16.255683
29,D10 > D5✅5 > D5❌_ > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/2422 [0.04%],17.259421,17.259421
30,D10 > D35 > D5✅7 > D5❌_ > D10 > D35 > D5✅7 > 🪙❓ > 🪙❗,1,1/2422 [0.04%],48.153854,48.153854
31,D10 > D32 > D35 > D5✅7 > 🪙❓ > 🪙❗,1,1/2422 [0.04%],5.142280,5.142280
32,D10 > D5✅5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/2422 [0.04%],17.064792,17.064792
33,D10 > D5✅5 > D5❌_ > D10 > D5✅5 > D5❌_,1,1/2422 [0.04%],2.179780,2.179780
34,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/2422 [0.04%],15.096065,15.096065
35,D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/2422 [0.04%],44.173125,44.173125
36,D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/2422 [0.04%],17.377685,17.377685
37,D10 > D5❌2 > D10 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/2422 [0.04%],8.374780,8.374780
38,D10 > D5❌5 > D5❌0 > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/2422 [0.04%],23.052303,23.052303
39,D10 > D45 > D5❌_,1,1/2422 [0.04%],0.793634,0.793634
40,D10 > D5✅5 > D5❌_ > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/2422 [0.04%],16.105567,16.105567
41,D10 > D5❌5 > 🪙❓ > 🪙❗ > D5❌0,1,1/2422 [0.04%],11.871516,11.871516
42,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > D5❌_,1,1/2422 [0.04%],47.078252,47.078252
43,D10 > D5✅5 > D5❌_ > D10 > D5❌5 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/2422 [0.04%],16.774051,16.774051
44,D20 > 🪙❓ > 🪙❗,1,1/2422 [0.04%],20.088113,20.088113
45,D10 > D42 > D5❌_,1,1/2422 [0.04%],4.134444,4.134444

======================================================================

int_decl_only_without_trips_from_2018: 71 Abläufe

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,4698,4698/8526 [55.10%],7.047205,9.290455
1,D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2562,2562/8526 [30.05%],10.249063,12.558235
2,D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,373,373/8526 [4.37%],11.104410,18.221586
3,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,202,202/8526 [2.37%],15.061852,21.955652
4,D10 > D5❌6 > D5❌0,184,184/8526 [2.16%],1.042494,9.200748
...,...,...,...,...,...
66,D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5✅7 > 🪙❓ > 🪙❗,1,1/8526 [0.01%],24.283646,24.283646
67,D10 > D36 > D31 > D35 > D5✅7 > 🪙❓ > 🪙❗,1,1/8526 [0.01%],16.261296,16.261296
68,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5✅7 > 🪙❓ > 🪙❗,1,1/8526 [0.01%],23.783750,23.783750
69,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5✅7 > 🪙❓ > 🪙❗,1,1/8526 [0.01%],60.308565,60.308565
70,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0,1,1/8526 [0.01%],0.166782,0.166782

======================================================================

int_permit_without_trips_before_2018: 120 Abläufe

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,P10 > P5✅5 > D10 > D5✅5 > 🪙❓ > 🪙❗,415,415/1268 [32.73%],45.159745,57.584601
1,P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,304,304/1268 [23.97%],49.121881,62.414359
2,P10 > P35 > P5✅7 > D10 > D35 > D5✅7 > 🪙❓ > 🪙❗,54,54/1268 [4.26%],86.334045,92.929796
3,P10 > P35 > P5✅7 > D10 > D5✅5 > 🪙❓ > 🪙❗,49,49/1268 [3.86%],77.219618,83.925764
4,P10 > P32 > P5✅5 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,39,39/1268 [3.08%],40.306771,52.193221
...,...,...,...,...,...
115,P10 > P35 > P5✅7 > P5❌_ > P10 > P35 > P5✅7 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/1268 [0.08%],124.186539,124.186539
116,P10 > P35 > P5✅7 > P5❌_ > P10 > P5✅5 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/1268 [0.08%],80.289248,80.289248
117,P10 > P32 > P5✅5 > D10 > D5❌2 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/1268 [0.08%],110.328472,110.328472
118,P10 > P36 > P35 > P5✅7 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/1268 [0.08%],206.058611,206.058611
119,P10 > P5❌5 > P5❌0 > P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P31 > P5✅5 > 📨 > 📨 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/1268 [0.08%],127.293843,127.293843

======================================================================

int_permit_without_trips_from_2018: 220 Abläufe

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,P10 > P36 > P5✅5 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1776,1776/4733 [37.52%],46.204144,60.051519
1,P10 > P36 > P31 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,877,877/4733 [18.53%],53.018403,63.007440
2,P10 > P36 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,374,374/4733 [7.90%],61.949433,69.605391
3,P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,243,243/4733 [5.13%],64.000451,71.458927
4,P10 > P36 > P5✅5 > 📨 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,141,141/4733 [2.98%],81.036042,89.833088
...,...,...,...,...,...
215,P10 > P36 > P31 > P35 > P5✅7 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/4733 [0.02%],136.199896,136.199896
216,P10 > P36 > P31 > P35 > P5✅7 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5✅7 > 🪙❓ > 🪙❗,1,1/4733 [0.02%],91.938472,91.938472
217,P10 > P36 > P31 > P5❌5 > P5❌0 > P10 > P5❌6 > P5❌0 > P10 > P36 > P31 > P5✅5 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/4733 [0.02%],57.180012,57.180012
218,P10 > P36 > P31 > P35 > P5✅7 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/4733 [0.02%],267.198241,267.198241
219,P10 > P5❌6 > P5❌0 > P10 > P5❌6 > P5❌0 > P10 > P36 > P31 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/4733 [0.02%],16.272523,16.272523

======================================================================

int_without_trips_with_year_marker: 386 Abläufe

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,?? > P10 > P36 > P5✅5 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1776,1776/6449 [27.54%],206.646562,210.660984
1,?? > P10 > P36 > P31 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,877,877/6449 [13.60%],217.646597,218.192474
2,P10 > P5✅5 > D10 > D5✅5 > 🪙❓ > 🪙❗ > ??,407,407/6449 [6.31%],227.571065,216.088388
3,?? > P10 > P36 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,374,374/6449 [5.80%],236.646713,227.945621
4,P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗ > ??,293,293/6449 [4.54%],208.526146,202.947565
...,...,...,...,...,...
381,P10 > ?? > P36 > P35 > P5✅7 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],206.058611,206.058611
382,P10 > P32 > P5✅5 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > ?? > 🪙❗,1,1/6449 [0.02%],101.052674,101.052674
383,P10 > P5❌5 > ?? > P5❌0 > P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P31 > P5✅5 > 📨 > 📨 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],127.293843,127.293843
384,?? > P10 > P36 > P31 > P35 > P5✅7 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],276.646713,276.646713
385,?? > P10 > P5❌6 > P5❌0 > P10 > P5❌6 > P5❌0 > P10 > P36 > P31 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],66.688194,66.688194

======================================================================

dom_with_year_marker: 116 Abläufe

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,?? > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,4610,4610/10500 [43.90%],185.646910,195.518331
1,?? > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2472,2472/10500 [23.54%],185.646910,197.744868
2,D10 > D5✅5 > 🪙❓ > 🪙❗ > ??,1348,1348/10500 [12.84%],180.456557,176.635063
3,D10 > D32 > D5✅5 > 🪙❓ > 🪙❗ > ??,563,563/10500 [5.36%],188.567755,170.734077
4,?? > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,344,344/10500 [3.28%],199.647245,215.948360
...,...,...,...,...,...
111,D10 > D5✅5 > D5❌_ > D10 > D5❌5 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗ > ??,1,1/10500 [0.01%],342.085266,342.085266
112,D20 > 🪙❓ > 🪙❗ > ??,1,1/10500 [0.01%],233.441690,233.441690
113,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > ?? > 🪙❓ > 🪙❗,1,1/10500 [0.01%],172.390556,172.390556
114,D10 > D42 > D5❌_ > ??,1,1/10500 [0.01%],65.529363,65.529363
115,?? > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0,1,1/10500 [0.01%],39.609884,39.609884

In [18]:
start_end(logs)

### Trace-Varianten je Log: nur Declaration

Alle anderen Events werden vor der Variantenbildung entfernt. Die Ablaeufe verwenden die Kurzcodes aus der Legende oben; die Anteile beziehen sich auf Traces mit Declaration-Events.

In [19]:
declaration_variants = {}
with pd.option_context("display.max_rows", None, "display.max_colwidth", None):
    for name, log in logs.items():
        declaration_events = log[log["concept:name"].str.contains(r"\bDeclaration\b", na=False)]
        declaration_variants[name] = variants(declaration_events)
        #print("=" * 70)
        #print(f"\n{name}: {len(declaration_variants[name])} Declaration-Ablaeufe")
        #display(declaration_variants[name])

In [20]:
import re
from collections import Counter
from python_analysis.functions import variants

declaration_events = logs["domestic"][
    logs["domestic"]["concept:name"].str.contains(
        r"\bDeclaration\b", na=False
    )
]

def split_variants(log, event: str):
    counts = Counter()
    for row in variants(log).itertuples(index=False):
        # D10 bleibt erhalten; ein D10 am Trace-Anfang erzeugt keinen leeren Teil.
        parts = re.split(r" > (?="+event+"(?: > |$))", row.Ablauf)
        for part in parts:
            counts[part] += row.Traces

    split_variants = (
        pd.DataFrame(counts.items(), columns=["Ablauf", "Teil-Traces"])
        .sort_values("Teil-Traces", ascending=False, ignore_index=True)
    )
    total = split_variants["Teil-Traces"].sum()
    split_variants["Anteil"] = split_variants["Teil-Traces"].map(
        lambda n: f"{n}/{total} [{n / total:.2%}]"
    )

    return split_variants

with pd.option_context("display.max_rows", None, "display.max_colwidth", None):
    df = split_variants(declaration_events, "D10") # Declaration Submitted by EMPLOYEE
    display(df)

                           Ablauf  Teil-Traces               Anteil
0                D10 > D36 > D5✅5         5133  5133/11666 [44.00%]
1          D10 > D36 > D31 > D5✅5         2788  2788/11666 [23.90%]
2                      D10 > D5✅5         1462  1462/11666 [12.53%]
3               D10 > D5❌6 > D5❌0          928    928/11666 [7.95%]
4                D10 > D32 > D5✅5          659    659/11666 [5.65%]
5         D10 > D36 > D5❌5 > D5❌0          185    185/11666 [1.59%]
6                             D20          135    135/11666 [1.16%]
7               D10 > D5❌2 > D5❌0           85     85/11666 [0.73%]
8               D10 > D5✅5 > D5❌_           74     74/11666 [0.63%]
9               D10 > D5❌5 > D5❌0           60     60/11666 [0.51%]
10        D10 > D36 > D5❌1 > D5❌0           58     58/11666 [0.50%]
11  D10 > D36 > D31 > D5❌5 > D5❌0           31     31/11666 [0.27%]
12                     D10 > D5❌6           24     24/11666 [0.21%]
13        D10 > D32 > D5✅5 > D5❌_           15     15/11666 [0.13%]
14        D10 > D32 > D5❌5 > D5❌0           11     11/11666 [0.09%]
15                     D10 > D5❌0            7      7/11666 [0.06%]
16               D10 > D36 > D5❌5            5      5/11666 [0.04%]
17               D10 > D36 > D5❌1            1      1/11666 [0.01%]
18                      D10 > D46            1      1/11666 [0.01%]
19         D10 > D36 > D31 > D5❌5            1      1/11666 [0.01%]
20                     D10 > D5❌2            1      1/11666 [0.01%]
21               D10 > D45 > D5❌_            1      1/11666 [0.01%]
22               D10 > D42 > D5❌_            1      1/11666 [0.01%]

In [21]:
with pd.option_context("display.max_rows", None, "display.max_colwidth", None):
    print("=" * 35 + " dom_log_base " + "=" * 35)
    df_variants = variants(logs["domestic"])
    df_split = split_variants(logs["domestic"], "D20") # Declaration Submitted by EMPLOYEE
    display(df_variants.loc[df_variants["Ablauf"].str.contains("D20", regex=False, na=False)])
    display(df_split.loc[df_split["Ablauf"].str.contains("D20", regex=False, na=False)])

with pd.option_context("display.max_rows", None, "display.max_colwidth", None):
    print("=" * 35 + " int_log_base " + "=" * 35)
    df_variants = variants(logs["int_without_trips"])
    df_split = split_variants(logs["int_without_trips"], "D20") # Declaration Submitted by EMPLOYEE
    display(df_variants.loc[df_variants["Ablauf"].str.contains("D20", regex=False, na=False)])
    display(df_split.loc[df_split["Ablauf"].str.contains("D20", regex=False, na=False)])

=================================== dom_log_base ===================================

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
7,D20,134,134/10500 [1.28%],0.000000,0.000000
96,D20 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],20.088113,20.088113

           Ablauf  Teil-Traces             Anteil
7             D20          134  134/10500 [1.28%]
96  D20 > 🪙❓ > 🪙❗            1    1/10500 [0.01%]

=================================== int_log_base ===================================

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
32,P10 > P36 > P5✅5 > D20,24,24/6449 [0.37%],46.631684,45.412224
49,P10 > P36 > P31 > P5✅5 > D20,11,11/6449 [0.17%],41.559630,59.455667
52,D20,10,10/6449 [0.16%],0.000000,0.000000
56,P10 > P36 > P5✅5 > 📨 > D20,9,9/6449 [0.14%],60.088356,75.457049
87,P10 > P5✅5 > D20,5,5/6449 [0.08%],25.812338,44.782604
94,P10 > P36 > P31 > P35 > P5✅7 > D20,4,4/6449 [0.06%],37.481707,37.222948
113,P10 > P36 > P31 > P5✅5 > 📨 > D20,3,3/6449 [0.05%],61.113889,65.276871
181,P10 > P35 > P5✅7 > D20,2,2/6449 [0.03%],18.943189,18.943189
185,P10 > P5✅5 > D20 > P5❌_,2,2/6449 [0.03%],102.834844,102.834844
220,P10 > P36 > P31 > P5✅5 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D20,1,1/6449 [0.02%],93.954641,93.954641
223,P10 > P36 > P35 > P5✅7 > 📨 > D20,1,1/6449 [0.02%],116.943796,116.943796
313,P10 > P35 > P5✅7 > D20 > P5❌_,1,1/6449 [0.02%],65.112824,65.112824
338,P10 > P32 > P5✅5 > D20,1,1/6449 [0.02%],64.161354,64.161354
361,P10 > P5✅5 > 📨 > D20,1,1/6449 [0.02%],101.086007,101.086007

         Ablauf  Teil-Traces           Anteil
12          D20           72  72/6514 [1.11%]
115  D20 > P5❌_            3   3/6514 [0.05%]

In [22]:
with pd.option_context("display.max_rows", None, "display.max_colwidth", None):
    df_variants = variants(logs["domestic"])
    display(df_variants.loc[df_variants["Ablauf"].str.contains("🪙", regex=False, na=False)])

    df_variants = variants(logs["int_without_trips"])
    display(df_variants.loc[df_variants["Ablauf"].str.contains("🪙", regex=False, na=False)])

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,4618,4618/10500 [43.98%],7.036163,9.377247
1,D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2473,2473/10500 [23.55%],10.232593,12.550129
2,D10 > D5✅5 > 🪙❓ > 🪙❗,1392,1392/10500 [13.26%],6.311244,9.891926
3,D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,575,575/10500 [5.48%],7.310475,9.966244
4,D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,345,345/10500 [3.29%],11.104410,18.572796
5,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,188,188/10500 [1.79%],15.061852,23.858456
8,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,77,77/10500 [0.73%],13.290833,20.007310
9,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,57,57/10500 [0.54%],11.006597,17.590916
10,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,49,49/10500 [0.47%],15.790660,19.509727
11,D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,40,40/10500 [0.38%],14.078148,22.539657
12,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,36,36/10500 [0.34%],13.601227,29.425902
14,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,29,29/10500 [0.28%],19.011644,32.301541
15,D10 > D5❌5 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,22,22/10500 [0.21%],10.602355,14.210254
17,D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,20,20/10500 [0.19%],15.762066,26.014595
19,D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,14,14/10500 [0.13%],11.132720,11.639786
21,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,10,10/10500 [0.10%],23.688866,23.787127
23,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,8,8/10500 [0.08%],11.575752,15.939994
25,D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,7,7/10500 [0.07%],24.062037,56.966915
26,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,6,6/10500 [0.06%],29.725012,33.983030
27,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,6,6/10500 [0.06%],16.639468,23.221435
30,D10 > D5❌2 > D5❌0 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,5,5/10500 [0.05%],29.236400,26.042109
32,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,4,4/10500 [0.04%],43.667836,40.539447
33,D10 > D36 > D5✅5 > 🪙❗,4,4/10500 [0.04%],48.788900,105.456111
34,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,4,4/10500 [0.04%],16.746337,17.709789
35,D10 > D5❌2 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,4,4/10500 [0.04%],6.982622,15.143860
36,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,3,3/10500 [0.03%],28.035486,37.867018
37,D10 > D5❌6 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,3,3/10500 [0.03%],13.314201,81.505027
41,D10 > D5✅5 > 🪙❓ > D5❌_,3,3/10500 [0.03%],29.876088,47.608318
43,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/10500 [0.02%],8.521568,8.521568
44,D10 > D5❌2 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/10500 [0.02%],222.709676,222.709676
45,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/10500 [0.02%],7.152188,7.152188
46,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/10500 [0.02%],90.345689,90.345689
48,D10 > D36 > D31 > D5✅5 > 🪙❗,2,2/10500 [0.02%],55.245521,55.245521
50,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,2,2/10500 [0.02%],15.131047,15.131047
52,D10 > D5❌5 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,2,2/10500 [0.02%],34.567668,34.567668
53,D10 > D32 > D5✅5 > D5❌_ > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],344.318148,344.318148
54,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],15.041076,15.041076
55,D10 > D5❌5 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],62.025463,62.025463
56,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],7.079178,7.079178
58,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],24.138831,24.138831
59,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D10 > D46 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],33.812755,33.812755
61,D10 > D5✅5 > D5❌_ > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],63.305845,63.305845
62,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],45.214120,45.214120
63,D10 > D5✅5 > D5❌_ > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],172.995660,172.995660
65,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],44.378229,44.378229
67,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],27.020891,27.020891
68,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],36.154919,36.154919
70,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],53.327697,53.327697
71,D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],44.902118,44.902118
72,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],65.106829,65.106829
73,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],48.133009,48.133009
75,D10 > D36 > D5❌5 > D10 > D36 > D5✅5 > 🪙❗,1,1/10500 [0.01%],66.298032,66.298032
77,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],17.154861,17.154861
80,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],13.042951,13.042951
81,D10 > D36 > D5❌5 > D10 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],18.062639,18.062639
82,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],17.043009,17.043009
83,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],27.107708,27.107708
85,D10 > D5✅5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],17.064792,17.064792
87,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],15.096065,15.096065
88,D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],17.377685,17.377685
89,D10 > D5❌2 > D10 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],8.374780,8.374780
90,D10 > D5❌5 > D5❌0 > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],23.052303,23.052303
92,D10 > D5✅5 > D5❌_ > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],16.105567,16.105567
93,D10 > D5❌5 > 🪙❓ > 🪙❗ > D5❌0,1,1/10500 [0.01%],11.871516,11.871516
95,D10 > D5✅5 > D5❌_ > D10 > D5❌5 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],16.774051,16.774051
96,D20 > 🪙❓ > 🪙❗,1,1/10500 [0.01%],20.088113,20.088113

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,P10 > P36 > P5✅5 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1776,1776/6449 [27.54%],46.204144,60.051519
1,P10 > P36 > P31 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,877,877/6449 [13.60%],53.018403,63.007440
2,P10 > P5✅5 > D10 > D5✅5 > 🪙❓ > 🪙❗,415,415/6449 [6.44%],45.159745,57.584601
3,P10 > P36 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,374,374/6449 [5.80%],61.949433,69.605391
4,P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,304,304/6449 [4.71%],49.121881,62.414359
5,P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,243,243/6449 [3.77%],64.000451,71.458927
6,P10 > P36 > P5✅5 > 📨 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,141,141/6449 [2.19%],81.036042,89.833088
7,D10 > D5✅5 > 🪙❓ > 🪙❗,111,111/6449 [1.72%],7.304248,11.417226
8,P10 > P36 > P35 > P5✅7 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,109,109/6449 [1.69%],91.364769,99.606850
9,P10 > P36 > P31 > P35 > P5✅7 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,91,91/6449 [1.41%],82.271146,96.219958
10,D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,90,90/6449 [1.40%],12.421742,13.132257
11,D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,88,88/6449 [1.36%],8.222847,10.200336
12,P10 > P36 > P31 > P5✅5 > 📨 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,67,67/6449 [1.04%],85.226505,98.020395
14,P10 > P36 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,58,58/6449 [0.90%],62.680017,72.828918
15,P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,55,55/6449 [0.85%],66.098056,71.590875
16,P10 > P36 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,54,54/6449 [0.84%],81.186435,87.934826
17,P10 > P35 > P5✅7 > D10 > D35 > D5✅7 > 🪙❓ > 🪙❗,54,54/6449 [0.84%],86.334045,92.929796
18,P10 > P35 > P5✅7 > D10 > D5✅5 > 🪙❓ > 🪙❗,49,49/6449 [0.76%],77.219618,83.925764
19,P10 > P36 > P31 > P5✅5 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,47,47/6449 [0.73%],108.011667,118.353200
20,P10 > P32 > P5✅5 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,39,39/6449 [0.60%],40.306771,52.193221
21,P10 > P5✅5 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,35,35/6449 [0.54%],59.055660,77.571604
23,D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,33,33/6449 [0.51%],8.314676,11.692897
24,P10 > P5✅5 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,32,32/6449 [0.50%],97.365191,135.693192
25,P10 > P36 > P35 > P5✅7 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,31,31/6449 [0.48%],103.284838,108.975465
26,P10 > P36 > P35 > P5✅7 > D10 > D36 > D35 > D5✅7 > 🪙❓ > 🪙❗,30,30/6449 [0.47%],68.523252,78.035266
27,P10 > P36 > P5✅5 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,29,29/6449 [0.45%],79.157894,90.240670
28,D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,29,29/6449 [0.45%],13.139294,17.564031
29,P10 > P36 > P5✅5 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,26,26/6449 [0.40%],89.518744,113.376529
30,P10 > P5❌6 > P5❌0 > P10 > P36 > P5✅5 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,25,25/6449 [0.39%],28.264433,50.888999
31,P10 > P5✅5 > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,25,25/6449 [0.39%],62.365602,74.538307
33,P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,23,23/6449 [0.36%],121.253727,119.723671
34,P10 > P36 > P31 > P35 > P5✅7 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,22,22/6449 [0.34%],98.168837,112.129532
35,P10 > P36 > P5❌5 > P5❌0 > P10 > P36 > P5✅5 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,21,21/6449 [0.33%],42.821678,51.590226
36,P10 > P36 > P35 > P5✅7 > D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5✅7 > 🪙❓ > 🪙❗,21,21/6449 [0.33%],73.125174,88.034673
37,P10 > P36 > P31 > P5✅5 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,21,21/6449 [0.33%],90.865602,96.929432
38,P10 > P32 > P5✅5 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,20,20/6449 [0.31%],95.890156,108.684623
39,P10 > P32 > P5✅5 > D10 > D5✅5 > 🪙❓ > 🪙❗,19,19/6449 [0.29%],83.163368,79.592552
40,P10 > P35 > P5✅7 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,17,17/6449 [0.26%],175.962477,169.390832
41,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,16,16/6449 [0.25%],17.062772,18.214664
42,P10 > P5❌2 > P5❌0 > P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,16,16/6449 [0.25%],98.609826,94.403513
43,P10 > P36 > P31 > P35 > P5✅7 > D10 > D36 > D31 > D35 > D5✅7 > 🪙❓ > 🪙❗,15,15/6449 [0.23%],52.170150,69.003150
44,D10 > D35 > D5✅7 > 🪙❓ > 🪙❗,14,14/6449 [0.22%],10.631001,10.623160
45,P10 > P5❌6 > P5❌0 > P10 > P36 > P31 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,14,14/6449 [0.22%],37.218947,36.738592
46,P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,13,13/6449 [0.20%],69.842674,90.415531
47,P10 > P36 > P31 > P35 > P5✅7 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5✅7 > 🪙❓ > 🪙❗,12,12/6449 [0.19%],88.338929,93.200441
48,P10 > P36 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,11,11/6449 [0.17%],81.030856,90.274252
50,D10 > D36 > D35 > D5✅7 > 🪙❓ > 🪙❗,11,11/6449 [0.17%],14.899167,16.316387
51,P10 > P36 > P31 > P5✅5 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,10,10/6449 [0.16%],62.179468,61.337572
54,P10 > P36 > P31 > P5✅5 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,10,10/6449 [0.16%],61.649439,76.892847
55,P10 > P36 > P5✅5 > 📨 > 📨 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,9,9/6449 [0.14%],34.257616,113.931157
57,P10 > P36 > P35 > P5✅7 > 📨 > D10 > D36 > D35 > D5✅7 > 🪙❓ > 🪙❗,9,9/6449 [0.14%],101.968148,105.654952
59,P10 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,9,9/6449 [0.14%],82.045463,125.520638
60,P10 > P36 > P5✅5 > D10 > D36 > D35 > D5✅7 > 🪙❓ > 🪙❗,8,8/6449 [0.12%],62.142766,62.954298
61,P10 > P35 > P5✅7 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,8,8/6449 [0.12%],224.158125,200.532373
62,P10 > P36 > P35 > P5✅7 > 📨 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,7,7/6449 [0.11%],106.068171,118.610455
63,P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,7,7/6449 [0.11%],80.225694,84.312273
64,P10 > P36 > P31 > P5✅5 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,7,7/6449 [0.11%],110.069699,122.187733
65,P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P31 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,7,7/6449 [0.11%],84.951331,85.768904
66,P10 > P5❌5 > P5❌0 > P10 > P5✅5 > D10 > D5✅5 > 🪙❓ > 🪙❗,7,7/6449 [0.11%],52.094884,48.078955
67,P10 > P5❌6 > P5❌0 > P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,6,6/6449 [0.09%],41.145307,51.269145
68,P10 > P36 > P31 > P35 > P5✅7 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,6,6/6449 [0.09%],120.447569,121.059113
69,P10 > P5❌6 > P5❌0 > P10 > P36 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,6,6/6449 [0.09%],78.608628,81.300133
70,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,6,6/6449 [0.09%],11.185602,10.520374
71,P10 > P36 > P5❌5 > P5❌0 > P10 > P36 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,6,6/6449 [0.09%],82.625440,85.015363
72,P10 > P36 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,6,6/6449 [0.09%],53.816562,62.338497
74,P10 > P32 > P5✅5 > D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,6,6/6449 [0.09%],58.129473,83.984772
75,P10 > P32 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,6,6/6449 [0.09%],65.640787,72.232222
76,P10 > P5✅5 > P5❌_ > P10 > P5✅5 > D10 > D5✅5 > 🪙❓ > 🪙❗,6,6/6449 [0.09%],71.330087,75.342544
77,P10 > P36 > P31 > P5❌5 > P5❌0 > P10 > P36 > P31 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,5,5/6449 [0.08%],69.169074,90.415884
78,P10 > P36 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,5,5/6449 [0.08%],67.049919,68.749741
79,P10 > P36 > P31 > P35 > P5✅7 > 📨 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,5,5/6449 [0.08%],102.139850,97.865472
80,P10 > P36 > P31 > P5✅5 > 📨 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,5,5/6449 [0.08%],81.079606,84.883657
81,P10 > P36 > P35 > P5✅7 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,5,5/6449 [0.08%],143.256354,136.600120
83,P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P5✅5 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,5,5/6449 [0.08%],51.273426,52.964313
86,P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,5,5/6449 [0.08%],52.244225,64.090947
88,P10 > P5✅5 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,5,5/6449 [0.08%],51.238634,52.095789
89,P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > 🪙❓ > P5❌_ > 🪙❗,5,5/6449 [0.08%],90.090903,84.907579
90,P10 > P35 > P5✅7 > D10 > D36 > D35 > D5✅7 > 🪙❓ > 🪙❗,5,5/6449 [0.08%],74.087014,106.099875
91,P10 > P5✅5 > D10 > D5✅5 > 🪙❓ > P5❌_ > 🪙❗,5,5/6449 [0.08%],84.361412,68.723738
92,P10 > P36 > 📨 > P5✅5 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,4,4/6449 [0.06%],32.162402,30.943035
93,P10 > P36 > P5✅5 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,4,4/6449 [0.06%],89.242749,91.125518
95,P10 > P36 > P31 > P5✅5 > 📨 > 📨 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,4,4/6449 [0.06%],205.566817,198.252885
96,P10 > P36 > P31 > P35 > P5✅7 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,4,4/6449 [0.06%],94.213113,133.938304
97,P10 > P36 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,4,4/6449 [0.06%],111.579462,99.314071
98,P10 > P36 > P31 > P35 > P5✅7 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5✅7 > 🪙❓ > 🪙❗,4,4/6449 [0.06%],99.731447,94.665718
99,P10 > P36 > P35 > P5✅7 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,4,4/6449 [0.06%],123.236221,148.270240
100,P10 > P36 > P5❌5 > P5❌0 > P10 > P36 > P31 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,4,4/6449 [0.06%],82.025648,87.394404
101,P10 > P35 > P5✅7 > D10 > D35 > D5✅7 > D5❌_ > D10 > D35 > D5✅7 > 🪙❓ > 🪙❗,4,4/6449 [0.06%],92.741985,103.960174
102,P10 > P32 > P35 > P5✅7 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,4,4/6449 [0.06%],150.088900,153.108061
103,P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,4,4/6449 [0.06%],88.470168,86.104928
104,P10 > P32 > P5✅5 > P5❌_ > P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,4,4/6449 [0.06%],211.632436,170.632740
105,P10 > P35 > P5✅7 > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,4,4/6449 [0.06%],84.124196,89.399873
106,P10 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,4,4/6449 [0.06%],89.686400,98.684812
107,P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,3,3/6449 [0.05%],97.173067,104.362631
108,P10 > P36 > P5✅5 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,3,3/6449 [0.05%],77.060694,78.655208
110,P10 > P36 > P35 > P5✅7 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5✅7 > 🪙❓ > 🪙❗,3,3/6449 [0.05%],55.817419,73.312404
111,P10 > P36 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5✅7 > 🪙❓ > 🪙❗,3,3/6449 [0.05%],97.866701,99.697469
112,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,3,3/6449 [0.05%],40.120405,30.082843
114,P10 > P36 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5✅7 > 🪙❓ > 🪙❗,3,3/6449 [0.05%],89.173206,103.142882
115,P10 > P36 > P35 > P5✅7 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,3,3/6449 [0.05%],104.299780,107.947878
117,P10 > P5❌6 > P5❌0 > P10 > P36 > P5✅5 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,3,3/6449 [0.05%],80.084537,79.475571
118,P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,3,3/6449 [0.05%],92.132789,93.727585
119,P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P31 > P5✅5 > 📨 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,3,3/6449 [0.05%],74.402350,94.939522
121,P10 > P36 > P5❌5 > P5❌0 > P10 > P36 > P5✅5 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,3,3/6449 [0.05%],155.152211,144.381474
122,P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,3,3/6449 [0.05%],77.392188,122.594915
124,P10 > P35 > P5✅7 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,3,3/6449 [0.05%],75.327222,95.590355
125,P10 > P5❌6 > P5❌0 > P10 > P36 > P35 > P5✅7 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],98.706406,98.706406
126,P10 > P5❌6 > P10 > P5❌0 > P10 > P36 > P31 > P5✅5 > 📨 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],58.649277,58.649277
129,D10 > D5❌5 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],8.649045,8.649045
130,P10 > P36 > P31 > P5❌5 > P5❌0 > P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],100.516771,100.516771
131,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],12.058970,12.058970
132,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],20.485104,20.485104
133,D10 > D36 > D5✅5 > 🪙❗ > 🪙❓,2,2/6449 [0.03%],80.565550,80.565550
134,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],31.743281,31.743281
135,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5✅7 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],26.388657,26.388657
136,P10 > P36 > P5❌5 > P5❌0 > P10 > P36 > P35 > P5✅7 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],111.184115,111.184115
137,P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],68.177303,68.177303
138,P10 > P36 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],100.024734,100.024734
139,P10 > P36 > P35 > P5✅7 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],143.093200,143.093200
140,P10 > P36 > 📨 > P31 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],48.204450,48.204450
141,P10 > P36 > P31 > P35 > P5✅7 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],122.021898,122.021898
142,P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],95.602222,95.602222
143,P10 > P36 > P31 > P5❌5 > P5❌0 > P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],103.432650,103.432650
144,P10 > P36 > P31 > P5❌5 > P5❌0 > P10 > P36 > P31 > P5✅5 > 📨 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],59.637135,59.637135
145,P10 > P36 > P31 > P5❌5 > P5❌0 > P10 > P36 > P31 > P5✅5 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],94.071823,94.071823
146,P10 > P36 > P5❌5 > P5❌0 > P10 > P36 > P35 > P5✅7 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],112.641256,112.641256
147,P10 > P36 > P31 > 📨 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],44.244016,44.244016
148,P10 > P36 > P35 > P5✅7 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],197.400694,197.400694
149,P10 > P36 > P35 > P5✅7 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D35 > D5✅7 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],86.171047,86.171047
150,P10 > P36 > P5✅5 > D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],105.630480,105.630480
151,P10 > P36 > P5❌5 > P5❌0 > P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],69.662188,69.662188
152,P10 > P5❌6 > P5❌0 > P10 > P36 > P31 > P35 > P5✅7 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],59.570712,59.570712
153,P10 > P36 > P5✅5 > D10 > D5❌6 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],97.715822,97.715822
154,P10 > P36 > P5✅5 > 📨 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],92.150365,92.150365
155,P10 > P36 > P31 > P35 > P5✅7 > D10 > D36 > D35 > D5✅7 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],62.067477,62.067477
156,P10 > P36 > P5✅5 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],116.037807,116.037807
157,P10 > P36 > P31 > P5✅5 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],109.477083,109.477083
158,P10 > P5❌6 > P5❌0 > P10 > P36 > P31 > P5✅5 > 📨 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],25.655758,25.655758
159,P10 > P36 > P5✅5 > 📨 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],67.220475,67.220475
160,P10 > P36 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],90.549537,90.549537
161,P10 > P36 > P31 > P5✅5 > D10 > D36 > D31 > D35 > D5✅7 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],58.753484,58.753484
162,P10 > P36 > P5✅5 > 📨 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],192.225949,192.225949
163,P10 > P36 > P31 > P35 > P5✅7 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],288.345359,288.345359
164,P10 > P36 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5✅7 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],77.205093,77.205093
165,P10 > P5❌5 > P5❌0 > P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P31 > P5✅5 > 📨 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],133.168993,133.168993
166,P10 > P5❌2 > P5❌0 > P10 > P32 > P5✅5 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],70.123223,70.123223
167,P10 > P5✅5 > D10 > D5❌5 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],76.731215,76.731215
168,P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > P5❌_ > 🪙❓ > 🪙❗,2,2/6449 [0.03%],112.001626,112.001626
169,P10 > P5❌5 > P5❌0 > P10 > P35 > P5✅7 > D10 > D35 > D5✅7 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],136.508015,136.508015
170,P10 > P35 > P5✅7 > D10 > D5❌5 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],57.250405,57.250405
171,P10 > P5❌2 > P5❌0 > P10 > P32 > P35 > P5✅7 > D10 > D32 > D35 > D5✅7 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],164.698495,164.698495
172,P10 > P32 > P5❌5 > P5❌0 > P10 > P32 > P5✅5 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],76.063663,76.063663
174,P10 > P35 > P5✅7 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],190.212454,190.212454
175,P10 > P32 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],211.077222,211.077222
176,P10 > P5✅5 > 📨 > 📨 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],179.442182,179.442182
177,P10 > P35 > P5✅7 > P5❌_ > P10 > P35 > P5✅7 > D10 > D35 > D5✅7 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],69.271933,69.271933
178,P10 > P32 > P5✅5 > D10 > D5❌2 > D5❌0 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],69.567668,69.567668
179,P10 > P32 > P35 > P5✅7 > D10 > D32 > D5✅7 > D35 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],103.599398,103.599398
180,P10 > P5✅5 > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],56.546580,56.546580
184,P10 > P32 > P5✅5 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],99.837384,99.837384
186,P10 > P32 > P5❌5 > P5❌0 > P10 > P32 > P5✅5 > D10 > D5✅5 > 🪙❓ > 🪙❗,2,2/6449 [0.03%],85.376157,85.376157
187,P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],126.328229,126.328229
188,P10 > P5❌6 > P5❌0 > P10 > P36 > P31 > P5✅5 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],14.290752,14.290752
189,P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❗,1,1/6449 [0.02%],59.188252,59.188252
190,P10 > P36 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],86.120706,86.120706
191,P10 > P36 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗ > 📨 > 📨,1,1/6449 [0.02%],153.755208,153.755208
192,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],16.255683,16.255683
193,D10 > D5✅5 > D5❌_ > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],17.259421,17.259421
194,D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],40.093542,40.093542
196,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],9.172801,9.172801
197,D10 > D35 > D5✅7 > D5❌_ > D10 > D35 > D5✅7 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],48.153854,48.153854
198,D10 > D32 > D35 > D5✅7 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],5.142280,5.142280
199,D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],10.022199,10.022199
201,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D35 > D5✅7 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],134.298032,134.298032
202,D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5✅7 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],24.283646,24.283646
203,D10 > D36 > D31 > D35 > D5✅7 > 🪙❓ > 🪙❗,1,1/6449 [0.02%],16.261296,16.261296

In [23]:
with pd.option_context("display.max_rows", None, "display.max_colwidth", None):
    df_variants = variants(declaration_events)
    df_split = split_variants(declaration_events, "D5❌") # Declaration Submitted by EMPLOYEE
    display(df_variants.loc[df_variants["Ablauf"].str.contains("D5❌", regex=False, na=False)])
    display(df_split.loc[df_split["Ablauf"].str.contains("D5❌", regex=False, na=False)])

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
4,D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5,345,345/10500 [3.29%],5.750509,12.156122
5,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5,188,188/10500 [1.79%],7.846615,17.185605
6,D10 > D5❌6 > D5❌0,174,174/10500 [1.66%],0.896800,8.415967
8,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5✅5,77,77/10500 [0.73%],6.949479,13.736680
9,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5,57,57/10500 [0.54%],3.586481,6.598261
10,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5✅5,49,49/10500 [0.47%],10.724641,14.485624
11,D10 > D5✅5 > D5❌_ > D10 > D5✅5,40,40/10500 [0.38%],7.113987,15.835213
12,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5,36,36/10500 [0.34%],6.630764,23.878389
13,D10 > D36 > D5❌5 > D5❌0,31,31/10500 [0.30%],3.970845,8.258822
14,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5,29,29/10500 [0.28%],13.120602,24.490311
15,D10 > D5✅5 > D5❌_,24,24/10500 [0.23%],1.948513,14.786941
16,D10 > D5❌5 > D5❌0 > D10 > D5✅5,22,22/10500 [0.21%],3.450596,6.117397
17,D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5✅5,20,20/10500 [0.19%],12.497043,21.375817
18,D10 > D5❌5 > D5❌0,19,19/10500 [0.18%],1.515752,7.787951
19,D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5✅5,14,14/10500 [0.13%],5.985301,4.523817
20,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0,11,11/10500 [0.10%],16.879421,29.447851
21,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5✅5,10,10/10500 [0.10%],19.632824,19.364917
22,D10 > D36 > D5❌1 > D5❌0,8,8/10500 [0.08%],3.347749,3.422457
23,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5✅5,8,8/10500 [0.08%],6.462795,6.608864
24,D10 > D5❌2 > D5❌0,8,8/10500 [0.08%],0.223079,0.825658
25,D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5,7,7/10500 [0.07%],15.137164,47.757088
26,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5✅5,6,6/10500 [0.06%],17.456782,25.906723
27,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5✅5,6,6/10500 [0.06%],10.454439,17.597106
28,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0,6,6/10500 [0.06%],13.714219,17.157407
29,D10 > D5❌6,5,5/10500 [0.05%],114.757766,159.781819
30,D10 > D5❌2 > D5❌0 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5,5,5/10500 [0.05%],11.995324,18.251507
31,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0,4,4/10500 [0.04%],8.779606,8.779835
32,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5,4,4/10500 [0.04%],19.347269,22.257358
33,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5✅5,4,4/10500 [0.04%],8.995642,9.691343
34,D10 > D5❌2 > D5❌0 > D10 > D5✅5,4,4/10500 [0.04%],3.688108,11.584323
35,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5✅5,3,3/10500 [0.03%],20.555741,31.111208
36,D10 > D5❌6 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5,3,3/10500 [0.03%],8.036100,77.607577
37,D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0,3,3/10500 [0.03%],51.697928,48.307172
38,D10 > D36 > D31 > D5❌5 > D5❌0,3,3/10500 [0.03%],6.975648,6.889425
39,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0,3,3/10500 [0.03%],71.948704,71.947091
40,D10 > D32 > D5❌5 > D5❌0,3,3/10500 [0.03%],12.084317,11.230015
41,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5✅5,2,2/10500 [0.02%],4.372031,4.372031
42,D10 > D5❌2 > D5❌0 > D10 > D36 > D5✅5,2,2/10500 [0.02%],217.484363,217.484363
43,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D5✅5,2,2/10500 [0.02%],2.883183,2.883183
44,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5,2,2/10500 [0.02%],85.333924,85.333924
45,D10 > D5❌6 > D10 > D5❌6 > D5❌0,2,2/10500 [0.02%],2.609421,2.609421
46,D10 > D36 > D5❌5,2,2/10500 [0.02%],9.421424,9.421424
47,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5,2,2/10500 [0.02%],6.528432,6.528432
48,D10 > D32 > D5✅5 > D5❌_,2,2/10500 [0.02%],5.980897,5.980897
49,D10 > D5❌5 > D5❌0 > D10 > D32 > D5✅5,2,2/10500 [0.02%],30.556834,30.556834
50,D10 > D32 > D5✅5 > D5❌_ > D10 > D36 > D31 > D5✅5,1,1/10500 [0.01%],337.101956,337.101956
51,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5✅5,1,1/10500 [0.01%],6.714387,6.714387
52,D10 > D5❌5 > D5❌0 > D10 > D36 > D5✅5,1,1/10500 [0.01%],53.858727,53.858727
53,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5✅5,1,1/10500 [0.01%],3.802280,3.802280
54,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D5❌0,1,1/10500 [0.01%],13.017859,13.017859
55,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5✅5,1,1/10500 [0.01%],19.694792,19.694792
56,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D10 > D46 > D10 > D36 > D31 > D5✅5,1,1/10500 [0.01%],27.605706,27.605706
57,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0,1,1/10500 [0.01%],22.742639,22.742639
58,D10 > D5✅5 > D5❌_ > D10 > D36 > D5✅5,1,1/10500 [0.01%],53.523611,53.523611
59,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D31 > D5✅5,1,1/10500 [0.01%],42.899826,42.899826
60,D10 > D5✅5 > D5❌_ > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5,1,1/10500 [0.01%],171.679826,171.679826
61,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0,1,1/10500 [0.01%],153.018322,153.018322
62,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5✅5,1,1/10500 [0.01%],41.249641,41.249641
63,D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/10500 [0.01%],64.170833,64.170833
64,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5,1,1/10500 [0.01%],20.934780,20.934780
65,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5✅5,1,1/10500 [0.01%],28.841574,28.841574
66,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌0,1,1/10500 [0.01%],7.757998,7.757998
67,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5✅5,1,1/10500 [0.01%],48.817106,48.817106
68,D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5,1,1/10500 [0.01%],40.888970,40.888970
69,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5✅5,1,1/10500 [0.01%],58.026447,58.026447
70,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5,1,1/10500 [0.01%],45.858565,45.858565
71,D10 > D5❌6 > D10 > D36 > D5❌5 > D5❌0,1,1/10500 [0.01%],1.225035,1.225035
72,D10 > D36 > D5❌5 > D10 > D36 > D5✅5,1,1/10500 [0.01%],10.151829,10.151829
73,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0,1,1/10500 [0.01%],21.926898,21.926898
74,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D36 > D5✅5,1,1/10500 [0.01%],9.898704,9.898704
75,D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/10500 [0.01%],20.824352,20.824352
76,D10 > D36 > D31 > D5❌5,1,1/10500 [0.01%],5.089850,5.089850
77,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D31 > D5✅5,1,1/10500 [0.01%],10.289769,10.289769
78,D10 > D36 > D5❌5 > D10 > D5❌0 > D10 > D36 > D5✅5,1,1/10500 [0.01%],6.912975,6.912975
79,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5,1,1/10500 [0.01%],14.647789,14.647789
80,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5✅5,1,1/10500 [0.01%],22.097500,22.097500
81,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5,1,1/10500 [0.01%],2.101748,2.101748
82,D10 > D5✅5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5,1,1/10500 [0.01%],13.705278,13.705278
83,D10 > D5✅5 > D5❌_ > D10 > D5✅5 > D5❌_,1,1/10500 [0.01%],2.179780,2.179780
84,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0 > D10 > D5✅5,1,1/10500 [0.01%],8.987986,8.987986
85,D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5,1,1/10500 [0.01%],14.276667,14.276667
86,D10 > D5❌2 > D10 > D5❌0 > D10 > D32 > D5✅5,1,1/10500 [0.01%],1.066100,1.066100
87,D10 > D5❌5 > D5❌0 > D10 > D5✅5 > D5❌_ > D10 > D5✅5,1,1/10500 [0.01%],12.882697,12.882697
88,D10 > D45 > D5❌_,1,1/10500 [0.01%],0.793634,0.793634
89,D10 > D5✅5 > D5❌_ > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > D5❌_ > D10 > D5✅5,1,1/10500 [0.01%],9.021412,9.021412
90,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > D5❌_,1,1/10500 [0.01%],47.078252,47.078252
91,D10 > D5✅5 > D5❌_ > D10 > D5❌5 > D5❌0 > D10 > D5✅5,1,1/10500 [0.01%],10.510729,10.510729
92,D10 > D42 > D5❌_,1,1/10500 [0.01%],4.134444,4.134444
93,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0,1,1/10500 [0.01%],0.166782,0.166782

,Ablauf,Teil-Traces,Anteil
4,D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5,345,345/10500 [3.29%]
5,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5,188,188/10500 [1.79%]
6,D10 > D5❌6 > D5❌0,174,174/10500 [1.66%]
8,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5✅5,77,77/10500 [0.73%]
9,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5,57,57/10500 [0.54%]
10,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5✅5,49,49/10500 [0.47%]
11,D10 > D5✅5 > D5❌_ > D10 > D5✅5,40,40/10500 [0.38%]
12,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5,36,36/10500 [0.34%]
13,D10 > D36 > D5❌5 > D5❌0,31,31/10500 [0.30%]
14,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5,29,29/10500 [0.28%]
15,D10 > D5✅5 > D5❌_,24,24/10500 [0.23%]
16,D10 > D5❌5 > D5❌0 > D10 > D5✅5,22,22/10500 [0.21%]
17,D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5✅5,20,20/10500 [0.19%]
18,D10 > D5❌5 > D5❌0,19,19/10500 [0.18%]
19,D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5✅5,14,14/10500 [0.13%]
20,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0,11,11/10500 [0.10%]
21,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5✅5,10,10/10500 [0.10%]
22,D10 > D36 > D5❌1 > D5❌0,8,8/10500 [0.08%]
23,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5✅5,8,8/10500 [0.08%]
24,D10 > D5❌2 > D5❌0,8,8/10500 [0.08%]
25,D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5,7,7/10500 [0.07%]
26,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5✅5,6,6/10500 [0.06%]
27,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5✅5,6,6/10500 [0.06%]
28,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0,6,6/10500 [0.06%]
29,D10 > D5❌6,5,5/10500 [0.05%]
30,D10 > D5❌2 > D5❌0 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5,5,5/10500 [0.05%]
31,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0,4,4/10500 [0.04%]
32,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5,4,4/10500 [0.04%]
33,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5✅5,4,4/10500 [0.04%]
34,D10 > D5❌2 > D5❌0 > D10 > D5✅5,4,4/10500 [0.04%]
35,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5✅5,3,3/10500 [0.03%]
36,D10 > D5❌6 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5,3,3/10500 [0.03%]
37,D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0,3,3/10500 [0.03%]
38,D10 > D36 > D31 > D5❌5 > D5❌0,3,3/10500 [0.03%]
39,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0,3,3/10500 [0.03%]
40,D10 > D32 > D5❌5 > D5❌0,3,3/10500 [0.03%]
41,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5✅5,2,2/10500 [0.02%]
42,D10 > D5❌2 > D5❌0 > D10 > D36 > D5✅5,2,2/10500 [0.02%]
43,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D5✅5,2,2/10500 [0.02%]
44,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5,2,2/10500 [0.02%]
45,D10 > D5❌6 > D10 > D5❌6 > D5❌0,2,2/10500 [0.02%]
46,D10 > D36 > D5❌5,2,2/10500 [0.02%]
47,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5,2,2/10500 [0.02%]
48,D10 > D32 > D5✅5 > D5❌_,2,2/10500 [0.02%]
49,D10 > D5❌5 > D5❌0 > D10 > D32 > D5✅5,2,2/10500 [0.02%]
50,D10 > D32 > D5✅5 > D5❌_ > D10 > D36 > D31 > D5✅5,1,1/10500 [0.01%]
51,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5✅5,1,1/10500 [0.01%]
52,D10 > D5❌5 > D5❌0 > D10 > D36 > D5✅5,1,1/10500 [0.01%]
53,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5✅5,1,1/10500 [0.01%]
54,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D5❌0,1,1/10500 [0.01%]
55,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5✅5,1,1/10500 [0.01%]
56,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D10 > D46 > D10 > D36 > D31 > D5✅5,1,1/10500 [0.01%]
57,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0,1,1/10500 [0.01%]
58,D10 > D5✅5 > D5❌_ > D10 > D36 > D5✅5,1,1/10500 [0.01%]
59,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D31 > D5✅5,1,1/10500 [0.01%]
60,D10 > D5✅5 > D5❌_ > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5,1,1/10500 [0.01%]
61,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0,1,1/10500 [0.01%]
62,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5✅5,1,1/10500 [0.01%]
63,D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/10500 [0.01%]
64,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5,1,1/10500 [0.01%]
65,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5✅5,1,1/10500 [0.01%]
66,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌0,1,1/10500 [0.01%]
67,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5✅5,1,1/10500 [0.01%]
68,D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5,1,1/10500 [0.01%]
69,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5✅5,1,1/10500 [0.01%]
70,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5,1,1/10500 [0.01%]
71,D10 > D5❌6 > D10 > D36 > D5❌5 > D5❌0,1,1/10500 [0.01%]
72,D10 > D36 > D5❌5 > D10 > D36 > D5✅5,1,1/10500 [0.01%]
73,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0,1,1/10500 [0.01%]
74,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D36 > D5✅5,1,1/10500 [0.01%]
75,D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/10500 [0.01%]
76,D10 > D36 > D31 > D5❌5,1,1/10500 [0.01%]
77,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D31 > D5✅5,1,1/10500 [0.01%]
78,D10 > D36 > D5❌5 > D10 > D5❌0 > D10 > D36 > D5✅5,1,1/10500 [0.01%]
79,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5,1,1/10500 [0.01%]
80,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5✅5,1,1/10500 [0.01%]
81,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5,1,1/10500 [0.01%]
82,D10 > D5✅5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5,1,1/10500 [0.01%]
83,D10 > D5✅5 > D5❌_ > D10 > D5✅5 > D5❌_,1,1/10500 [0.01%]
84,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0 > D10 > D5✅5,1,1/10500 [0.01%]
85,D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5,1,1/10500 [0.01%]
86,D10 > D5❌2 > D10 > D5❌0 > D10 > D32 > D5✅5,1,1/10500 [0.01%]
87,D10 > D5❌5 > D5❌0 > D10 > D5✅5 > D5❌_ > D10 > D5✅5,1,1/10500 [0.01%]
88,D10 > D45 > D5❌_,1,1/10500 [0.01%]
89,D10 > D5✅5 > D5❌_ > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > D5❌_ > D10 > D5✅5,1,1/10500 [0.01%]
90,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > D5❌_,1,1/10500 [0.01%]
91,D10 > D5✅5 > D5❌_ > D10 > D5❌5 > D5❌0 > D10 > D5✅5,1,1/10500 [0.01%]
92,D10 > D42 > D5❌_,1,1/10500 [0.01%]
93,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0,1,1/10500 [0.01%]

In [24]:
dom_base_neighbors = direct_neighborhood(logs["domestic"])
int_base_neighbors = direct_neighborhood(logs["int_without_trips"])
display(dom_base_neighbors)
display(int_base_neighbors)

,Vorbereich,Nachbereich
Code,,
D10,"{D5❌_, D5❌5, D5❌2, D46, D5❌6, D5❌0, D5❌1}","{D32, D42, D5❌5, D5❌2, D46, D5❌6, D5❌0, D45, D..."
D20,{},{🪙❓}
D31,{D36},"{D5❌5, D5✅5}"
D32,{D10},"{D5❌5, D5✅5}"
D36,{D10},"{D31, D5❌5, D5❌1, D5✅5}"
D42,{D10},{D5❌_}
D45,{D10},{D5❌_}
D46,{D10},{D10}
D5✅5,"{D31, D10, D32, D36}","{D5❌_, 🪙❓, 🪙❗}"
D5❌0,"{D5❌5, D5❌2, 🪙❗, D5❌6, D10, D5❌1}",{D10}
D5❌1,{D36},"{D10, D5❌0}"
D5❌2,{D10},"{D10, D5❌0}"
D5❌5,"{D31, D10, D32, D36}","{D10, D5❌0, 🪙❓}"
D5❌6,{D10},"{D10, D5❌0}"
D5❌_,"{D42, 🪙❓, D45, D5✅5}",{D10}
🪙❓,"{D5❌5, D20, D5✅5}","{D5❌_, 🪙❗}"
🪙❗,"{🪙❓, D5✅5}",{D5❌0}

,Vorbereich,Nachbereich
Code,,
D10,"{P5✅5, D5❌_, 📨, P35, D5❌5, P5✅7, D5❌6, D5❌0, P32}","{D5✅7, D32, P5❌_, D5❌5, D5❌2, D5✅5, D5❌6, D5❌0..."
D20,"{P5✅5, D5❌0, 📨, P5✅7}",{P5❌_}
D31,{D36},"{D35, D5❌5, D5✅5}"
D32,"{P5✅5, D10}","{D5❌5, D5✅7, D35, D5✅5}"
D35,"{D5✅7, D32, D31, D10, D36}","{D5✅7, D5❌7, 🪙❓}"
D36,{D10},"{P5❌_, D5❌5, D5✅5, D31, D5❌1, D35}"
D5✅5,"{D32, P5❌_, D31, D10, D36}","{D5❌_, 🪙❓, P5❌_, 🪙❗}"
D5✅7,"{D10, D32, D35}","{D5❌_, 🪙❓, D35}"
D5❌0,"{D5❌7, P5❌_, D5❌5, D5❌2, D5❌6, D10, D5❌1}","{P5❌_, D10, D20}"
D5❌1,{D36},{D5❌0}
D5❌2,{D10},"{P5❌_, D5❌0}"
D5❌5,"{D31, D10, D32, D36}","{D10, D5❌0}"
D5❌6,{D10},"{D10, D5❌0}"
D5❌7,{D35},{D5❌0}
D5❌_,"{D5✅7, D5✅5}","{P5❌_, D10}"
P10,"{P5❌5, P5❌_, P5❌6, P5❌0}","{P5✅5, P5❌2, P36, P5❌6, P5❌0, P35, P32, P5❌5}"
P31,"{P36, 📨}","{P5✅5, 📨, P35, P5✅7, P5❌5}"
P32,"{P5✅5, P10}","{P5✅5, P35, P5✅7, D10, P5❌5}"
P35,"{P36, P10, P5✅7, P31, P32}","{D10, 📨, P5✅7, P5❌7}"
P36,{P10},"{P5✅5, 📨, P5❌1, P35, P31, P5❌5}"
P5✅5,"{P36, 📨, P10, P31, P32}","{📨, D32, D20, P5❌_, D10, P32}"
P5✅7,"{P31, P32, P35}","{📨, P35, D20, P5❌_, D10}"
P5❌0,"{P5❌2, P5❌6, P5❌7, P5❌1, P10, P5❌5}",{P10}
P5❌1,{P36},{P5❌0}
P5❌2,{P10},{P5❌0}
P5❌5,"{P10, P31, P36, P32}","{P10, P5❌0}"
P5❌6,{P10},"{P10, P5❌0}"
P5❌7,{P35},{P5❌0}
P5❌_,"{P5✅5, D5❌_, 🪙❓, D5❌2, P5✅7, D20, D5✅5, D10, D...","{🪙❓, P10, 🪙❗, D5❌0, D5✅5}"
📨,"{P5✅5, 📨, P36, P35, P5✅7, 🪙❗, P31}","{P5✅5, 📨, D20, D10, P31}"
🪙❓,"{D5✅7, D5✅5, 🪙❗, P5❌_, D35}","{P5❌_, 🪙❗}"
🪙❗,"{P5❌_, 🪙❓, D5✅5}","{🪙❓, 📨}"

In [25]:
neighbors_dom_decl = direct_neighborhood(logs["domestic"].loc[logs["domestic"]["concept:name"].str.contains("Declaration", na=False)])
neighbors_int_decl = direct_neighborhood(logs["international"].loc[logs["international"]["concept:name"].str.contains("Declaration", na=False)])

In [26]:
display(neighbors_dom_decl.loc[neighbors_dom_decl.index.str.contains("D5❌")])
display(neighbors_dom_decl.loc[neighbors_dom_decl.index.str.contains("D10")])
print("*" *70)
display(neighbors_int_decl.loc[neighbors_int_decl.index.str.contains("D5❌")])
display(neighbors_int_decl.loc[neighbors_int_decl.index.str.contains("D10")])

                         Vorbereich  Nachbereich
Code
D5❌0  {D5❌5, D5❌2, D5❌6, D10, D5❌1}        {D10}
D5❌1                          {D36}  {D10, D5❌0}
D5❌2                          {D10}  {D10, D5❌0}
D5❌5           {D31, D10, D32, D36}  {D10, D5❌0}
D5❌6                          {D10}  {D10, D5❌0}
D5❌_               {D42, D45, D5✅5}        {D10}

,Vorbereich,Nachbereich
Code,,
D10,"{D5❌_, D5❌5, D5❌2, D46, D5❌6, D5❌0, D5❌1}","{D32, D42, D5❌5, D5❌2, D46, D5❌6, D5❌0, D45, D..."

**********************************************************************

                               Vorbereich  Nachbereich
Code
D5❌0  {D5❌7, D5❌5, D5❌2, D5❌6, D10, D5❌1}   {D10, D20}
D5❌1                                {D36}       {D5❌0}
D5❌2                                {D10}       {D5❌0}
D5❌5                 {D31, D10, D32, D36}  {D10, D5❌0}
D5❌6                                {D10}  {D10, D5❌0}
D5❌7                                {D35}       {D5❌0}
D5❌_                         {D5✅7, D5✅5}        {D10}

,Vorbereich,Nachbereich
Code,,
D10,"{D5❌6, D5❌0, D5❌_, D5❌5}","{D5✅7, D32, D5❌5, D5❌2, D5✅5, D5❌6, D5❌0, D36,..."

In [27]:
log = logs["domestic"]
declarations = log.loc[
    log["concept:name"].str.startswith("Declaration ", na=False)
]
display(predecessor_times(declarations, target="D5❌0").style.format({
    "Min_Tage": "{:.3f}",
    "Max_Tage": "{:.3f}",
    "Median_Tage": "{:.3f}",
    "Durchschnitt_Tage": "{:.3f}",
}))
display(successor_times(declarations, target="D5❌0").style.format({
    "Min_Tage": "{:.3f}",
    "Max_Tage": "{:.3f}",
    "Median_Tage": "{:.3f}",
    "Durchschnitt_Tage": "{:.3f}",
}))

In [28]:
from python_analysis.functions import rejection_triples

display(rejection_triples(logs["domestic"]))

Domestic: \
D5x0 | kommt von D5x* in 1349 von 1357 Fällen (99,41%) | geht auf Trace-Ende oder D10 \
D5x1 | kommt von D36 (100%) |
D5x2 | kommt von D10 (100%) |
D5x5 | kommt nach D10 () oder D3* () |
D5x6 | Kommt von D10 (100%)
D5x_ |

In [29]:
display(rejection_triples(logs["int_without_trips"]))

In [30]:
display(rejection_triples(logs["int_decl_only_without_trips"]))

In [31]:
display(rejection_triples(logs["int_permit_without_trips"]))

In [32]:
from python_analysis.functions import bottleneck_analysis, event_code

log = logs["domestic"]
intervals = bottleneck_analysis(log)["intervals"].copy()
intervals["Von"] = intervals["from_activity"].map(event_code)
intervals["Nach"] = intervals["to_activity"].map(event_code)

stats = (
    intervals.groupby(["Von", "Nach"])
    .agg(
        Anzahl=("elapsed_days", "size"),
        Min_Tage=("elapsed_days", "min"),
        Max_Tage=("elapsed_days", "max"),
    )
    .reset_index()
)

zero = stats.loc[
    stats["Min_Tage"].eq(0) & stats["Max_Tage"].eq(0)
]

for activity in sorted(log["concept:name"].map(event_code).unique()):
    before = zero.loc[zero["Nach"].eq(activity)]
    after = zero.loc[zero["Von"].eq(activity)]

    if before.empty and after.empty:
        continue

    print(f"\n=== {activity} ===")

    if not before.empty:
        print("Vorbereich:")
        display(
            before.drop(columns="Nach")
            .set_index("Von")
            .rename_axis("Voraktivitaet")
        )

    if not after.empty:
        print("Nachbereich:")
        display(
            after.drop(columns="Von")
            .set_index("Nach")
            .rename_axis("Nachaktivitaet")
        )

In [33]:
from python_analysis.functions import bottleneck_analysis, event_code

log = logs["international"]
intervals = bottleneck_analysis(log)["intervals"].copy()
intervals["Von"] = intervals["from_activity"].map(event_code)
intervals["Nach"] = intervals["to_activity"].map(event_code)

stats = (
    intervals.groupby(["Von", "Nach"])
    .agg(
        Anzahl=("elapsed_days", "size"),
        Min_Tage=("elapsed_days", "min"),
        Max_Tage=("elapsed_days", "max"),
    )
    .reset_index()
)

zero = stats.loc[
    stats["Min_Tage"].eq(0) & stats["Max_Tage"].eq(0)
]

for activity in sorted(log["concept:name"].map(event_code).unique()):
    before = zero.loc[zero["Nach"].eq(activity)]
    after = zero.loc[zero["Von"].eq(activity)]

    if before.empty and after.empty:
        continue

    print(f"\n=== {activity} ===")

    if not before.empty:
        print("Vorbereich:")
        display(
            before.drop(columns="Nach")
            .set_index("Von")
            .rename_axis("Voraktivitaet")
        )

    if not after.empty:
        print("Nachbereich:")
        display(
            after.drop(columns="Von")
            .set_index("Nach")
            .rename_axis("Nachaktivitaet")
        )

=== D35 ===
Vorbereich:

               Anzahl  Min_Tage  Max_Tage
Voraktivitaet
D5✅7                3       0.0       0.0

=== D5✅7 ===
Nachbereich:

                Anzahl  Min_Tage  Max_Tage
Nachaktivitaet
D35                  3       0.0       0.0

=== P32 ===
Vorbereich:

               Anzahl  Min_Tage  Max_Tage
Voraktivitaet
P5✅5                1       0.0       0.0

=== P35 ===
Vorbereich:

               Anzahl  Min_Tage  Max_Tage
Voraktivitaet
P5✅7                3       0.0       0.0

=== P5✅5 ===
Nachbereich:

                Anzahl  Min_Tage  Max_Tage
Nachaktivitaet
P32                  1       0.0       0.0

=== P5✅7 ===
Nachbereich:

                Anzahl  Min_Tage  Max_Tage
Nachaktivitaet
P35                  3       0.0       0.0

mögliche Kopplung zeigen deine drei Paare:

 Beobachteter Übergang | Mögliche Interpretation

 D5✅7 → D35 | Finale Declaration-Freigabe durch Direktor setzt Supervisor-Freigabe mit \
 P5✅7 → P35 | Finale Permit-Freigabe durch Direktor setzt Supervisor-Freigabe mit \
 P5✅5 → P32 | Finale Permit-Freigabe durch Supervisor setzt Pre-Approver-Freigabe mit

könnte auch eine einzige Systemaktion mit zwei Logeinträgen sein, statt zweier tatsächlich separat ausgeführter Arbeitsschritte.

In [34]:
log = logs["domestic"]
declarations = log.loc[
    log["concept:name"].str.startswith("Declaration ", na=False)
]
display(predecessor_times(declarations, target="D5❌_").style.format({
    "Min_Tage": "{:.3f}",
    "Max_Tage": "{:.3f}",
    "Median_Tage": "{:.3f}",
    "Durchschnitt_Tage": "{:.3f}",
}))
display(successor_times(declarations, target="D5❌_").style.format({
    "Min_Tage": "{:.3f}",
    "Max_Tage": "{:.3f}",
    "Median_Tage": "{:.3f}",
    "Durchschnitt_Tage": "{:.3f}",
}))
log = logs["international"]
declarations = log.loc[
    log["concept:name"].str.startswith("Declaration ", na=False)
]
display(predecessor_times(declarations, target="D5❌_").style.format({
    "Min_Tage": "{:.3f}",
    "Max_Tage": "{:.3f}",
    "Median_Tage": "{:.3f}",
    "Durchschnitt_Tage": "{:.3f}",
}))
display(successor_times(declarations, target="D5❌_").style.format({
    "Min_Tage": "{:.3f}",
    "Max_Tage": "{:.3f}",
    "Median_Tage": "{:.3f}",
    "Durchschnitt_Tage": "{:.3f}",
}))

In [35]:
log = int_log_base  # alternativ: dom_log_base
case_id = "case:concept:name"
activities = ["Request Payment", "Payment Handled", "Send Reminder"]

counts = (
    log.loc[log["concept:name"].isin(activities)]
    .groupby([case_id, "concept:name"])
    .size()
    .unstack(fill_value=0)
    .reindex(columns=activities, fill_value=0)
)

repeated = counts.loc[counts.gt(1).any(axis=1)]

# Vollständige Traces behalten, nicht nur die drei gesuchten Aktivitäten.
matching_traces = (
    log.loc[log[case_id].isin(repeated.index)]
    .sort_values([case_id, "time:timestamp"], kind="stable")
)

print(f"{len(repeated)} von {log[case_id].nunique()} Traces betroffen")

with pd.option_context("display.max_rows", None, "display.max_colwidth", None):
    display(repeated)                  # Häufigkeit jeder Aktivität je Fall
    display(variants(matching_traces)) # Vollständige Abläufe als Kurzcodes + Häufigkeit

28 von 6449 Traces betroffen

concept:name       Request Payment  Payment Handled  Send Reminder
case:concept:name
declaration 1126                 1                1              2
declaration 13321                1                1              2
declaration 1544                 1                1              2
declaration 1886                 1                1              2
declaration 27582                1                1              2
declaration 31495                1                1              2
declaration 31697                1                1              2
declaration 43745                1                1              2
declaration 44042                1                1              2
declaration 47171                1                1              2
declaration 60554                1                1              2
declaration 62845                1                1              2
declaration 65318                1                1              2
declaration 65871                1                1              2
declaration 67654                1                1              2
declaration 6997                 1                1              2
declaration 7022                 1                1              2
declaration 78732                1                1              2
declaration 79012                1                1              2
declaration 79028                1                1              2
declaration 79326                1                1              2
declaration 79849                1                1              2
declaration 84048                1                1              2
declaration 85792                1                1              2
declaration 8721                 1                1              2
declaration 8731                 1                1              2
declaration 8772                 1                1              2
declaration 8994                 1                1              2

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,T⬆️ > T⬇️ > P10 > P36 > P5✅5 > 📨 > 📨 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,5,5/28 [17.86%],359.771655,310.354938
1,P10 > P36 > P5✅5 > T⬆️ > T⬇️ > 📨 > 📨 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,4,4/28 [14.29%],225.530943,218.980139
2,P10 > P36 > P31 > P5✅5 > T⬆️ > T⬇️ > 📨 > 📨 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,3,3/28 [10.71%],217.167836,215.113032
3,P10 > P5✅5 > T⬆️ > T⬇️ > 📨 > 📨 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/28 [7.14%],179.442182,179.442182
4,P10 > P36 > P5✅5 > D10 > T⬆️ > T⬇️ > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗ > 📨 > 📨,1,1/28 [3.57%],153.755208,153.755208
5,T⬆️ > P10 > P36 > P31 > P5✅5 > T⬇️ > 📨 > 📨 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/28 [3.57%],147.688519,147.688519
6,P10 > P36 > P31 > P5✅5 > T⬆️ > T⬇️ > 📨 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/28 [3.57%],223.049907,223.049907
7,P10 > P36 > P5✅5 > T⬆️ > T⬇️ > 📨 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/28 [3.57%],209.213634,209.213634
8,T⬆️ > P10 > P36 > P5✅5 > T⬇️ > 📨 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/28 [3.57%],175.771863,175.771863
9,P10 > P36 > P5✅5 > T⬆️ > T⬇️ > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗ > 📨 > 📨,1,1/28 [3.57%],127.222465,127.222465
10,T⬆️ > P10 > P5❌5 > T⬇️ > P5❌0 > P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P31 > P5✅5 > 📨 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/28 [3.57%],168.688553,168.688553
11,T⬆️ > T⬇️ > P10 > P5❌5 > P5❌0 > P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P31 > P5✅5 > 📨 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/28 [3.57%],140.688553,140.688553
12,T⬆️ > P10 > P5✅5 > T⬇️ > 📨 > 📨 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/28 [3.57%],125.688322,125.688322
13,P10 > P32 > P5✅5 > T⬆️ > T⬇️ > 📨 > 📨 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/28 [3.57%],220.202222,220.202222
14,P10 > P35 > P5✅7 > T⬆️ > T⬇️ > 📨 > 📨 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/28 [3.57%],145.709248,145.709248
15,P10 > P35 > P5✅7 > T⬆️ > T⬇️ > 📨 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/28 [3.57%],189.046898,189.046898
16,P10 > P32 > P5✅5 > T⬆️ > T⬇️ > 📨 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/28 [3.57%],189.277917,189.277917
17,P10 > P5❌5 > T⬆️ > T⬇️ > P5❌0 > P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P31 > P5✅5 > 📨 > 📨 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/28 [3.57%],127.293843,127.293843

Trip:
Startet trip -> End trip
Keine Abhängigkeiten, parallel zum Rest

Payment:

Aufgabe 2

Aufgabe 3

Aufgabe 4

Aufgabe 5

Aufgabe 6

Aufgabe 7

Aufgabe 8

Aufgabe 9

Aufgabe 10

Aufgabe 11

In [36]:
from python_analysis.functions import rejection_timeline

analyses = {}

for name, log, entity in [
    ("Domestic Declaration", logs["domestic"], "Declaration"),
    ("International Declaration", logs["int_decl_only_without_trips"], "Declaration"),
    ("International Permit", logs["int_permit_without_trips"], "Permit")]:
    result = rejection_timeline(log, entity=entity)
    analyses[name] = result

    print(f"\n=== {name} ===")
    with pd.option_context("display.max_rows", None, "display.max_colwidth", None):
        display(result["summary"].round(3))

=== Domestic Declaration ===

                                      Anzahl  Traces  Median_vor_Tage  \
Monat   Voraktivitaet Nachaktivitaet
2017-01 D5❌2          D10                  4       4            1.364
        D5❌5          D10                  2       2            1.464
2017-02 D10           D10                  1       1            0.000
        D5❌2          D10                  4       4            1.195
        D5❌5          <Trace-Ende>         2       2            0.537
                      D10                  4       4            4.801
2017-03 D5❌2          D10                  9       8            0.063
        D5❌5          D10                  3       3            3.616
2017-04 D5❌2          D10                  6       6            1.156
        D5❌5          <Trace-Ende>         2       2            5.252
                      D10                  4       4            0.577
2017-05 D5❌2          <Trace-Ende>         1       1            2.678
                      D10                 12      11            1.420
        D5❌5          <Trace-Ende>         2       2            0.109
                      D10                  6       6            3.137
2017-06 D5❌2          <Trace-Ende>         1       1            0.242
                      D10                  8       8            2.354
        D5❌5          D10                  1       1            0.010
2017-07 D5❌2          D10                  7       7            1.288
        D5❌5          <Trace-Ende>         1       1            5.310
                      D10                  2       2            0.150
2017-08 D5❌5          D10                  1       1            4.100
2017-09 D5❌2          D10                  2       2            0.547
        D5❌5          <Trace-Ende>         4       4            1.032
                      D10                  5       4            1.957
2017-10 D5❌2          <Trace-Ende>         4       4            0.903
                      D10                 12      10            1.065
        D5❌5          D10                  4       4            0.668
2017-11 D5❌2          D10                  7       7            0.255
        D5❌5          <Trace-Ende>         1       1            0.050
                      D10                  3       3            1.583
2017-12 D5❌2          <Trace-Ende>         2       2            0.103
                      D10                  6       6            1.494
        D5❌5          <Trace-Ende>        10      10           11.787
                      D10                  8       8            0.752
        🪙❗            <Trace-Ende>         1       1            1.625
2018-01 D5❌1          <Trace-Ende>         6       6            0.673
                      D10                  1       1            0.214
        D5❌5          <Trace-Ende>         6       6           28.955
                      D10                  7       6            0.424
        D5❌6          <Trace-Ende>         9       9            1.689
                      D10                 33      32            1.190
2018-02 D5❌1          <Trace-Ende>         1       1            1.884
                      D10                 12      11            4.923
        D5❌5          <Trace-Ende>         3       3            5.186
                      D10                 22      21            1.116
        D5❌6          <Trace-Ende>        12      12            0.431
                      D10                 34      33            0.904
2018-03 D5❌1          D10                  3       3            2.114
        D5❌5          <Trace-Ende>         7       7            0.698
                      D10                 18      18            0.951
        D5❌6          <Trace-Ende>        12      12            0.655
                      D10                 37      32            0.878
2018-04 D10           D10                  2       2            0.000
        D5❌1          <Trace-Ende>         1       1            0.033
                      D10                  4       4            0.523
        D5❌5          <Trace-Ende>         1       1            8.912
                      D10                 19      19            0.932
        D5❌6          <Trace-Ende>         8       8            0.160
                      D10                 44      40            0.758
2018-05 D5❌1          <Trace-Ende>         2       2            2.011
                      D10                  2       2            1.815
        D5❌5          <Trace-Ende>         4       4            0.593
                      D10                  9       9            2.037
        D5❌6          <Trace-Ende>        11      11            1.774
                      D10                 69      61            0.579
2018-06 D5❌1          <Trace-Ende>         1       1            5.213
                      D10                  4       4            1.072
        D5❌5          <Trace-Ende>         3       3            3.287
                      D10                 20      20            0.747
        D5❌6          <Trace-Ende>        20      20            0.520
                      D10                 98      88            0.747
2018-07 D10           <Trace-Ende>         1       1            0.000
                      D10                  1       1            0.000
        D5❌1          D10                  4       4            1.380
        D5❌5          <Trace-Ende>         3       3            3.295
                      D10                  9       9            1.037
        D5❌6          <Trace-Ende>        20      20            0.573
                      D10                123     111            1.017
2018-08 D5❌1          D10                  1       1            0.156
        D5❌5          <Trace-Ende>         1       1            0.092
                      D10                  4       4            3.016
        D5❌6          <Trace-Ende>         8       8            0.699
                      D10                 45      41            1.765
2018-09 D5❌5          <Trace-Ende>         7       7            0.993
                      D10                 10      10            3.527
        D5❌6          <Trace-Ende>        11      11            2.905
                      D10                 64      54            1.138
2018-10 D5❌1          <Trace-Ende>         1       1            1.027
                      D10                  4       4            3.335
        D5❌5          <Trace-Ende>         5       5            2.052
                      D10                 25      24            1.798
        D5❌6          <Trace-Ende>        33      33            2.248
                      D10                 51      46            0.980
2018-11 D10           D10                  1       1            0.000
        D5❌1          <Trace-Ende>         1       1            6.370
                      D10                  3       3            0.553
        D5❌5          <Trace-Ende>         2       2            5.650
                      D10                 17      16            1.277
        D5❌6          <Trace-Ende>        24      24            0.877
                      D10                 65      62            0.942
2018-12 D10           D10                  1       1            0.000
        D5❌1          D10                  7       7            0.839
        D5❌5          <Trace-Ende>         1       1            0.736
                      D10                 18      18            0.307
        D5❌6          <Trace-Ende>        28      28            0.889
                      D10                 69      66            1.011

                                      Median_nach_Tage  Null_vor_Anteil  \
Monat   Voraktivitaet Nachaktivitaet
2017-01 D5❌2          D10                        0.115              0.0
        D5❌5          D10                        0.157              0.0
2017-02 D10           D10                        0.011              0.0
        D5❌2          D10                        0.034              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        2.200              0.0
2017-03 D5❌2          D10                        0.007              0.0
        D5❌5          D10                        0.050              0.0
2017-04 D5❌2          D10                        0.013              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.386              0.0
2017-05 D5❌2          <Trace-Ende>                 NaN              0.0
                      D10                        3.441              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        2.375              0.0
2017-06 D5❌2          <Trace-Ende>                 NaN              0.0
                      D10                        0.274              0.0
        D5❌5          D10                        0.014              0.0
2017-07 D5❌2          D10                        0.009              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.004              0.0
2017-08 D5❌5          D10                        0.089              0.0
2017-09 D5❌2          D10                        0.003              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.214              0.0
2017-10 D5❌2          <Trace-Ende>                 NaN              0.0
                      D10                        0.115              0.0
        D5❌5          D10                        1.425              0.0
2017-11 D5❌2          D10                        0.085              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.055              0.0
2017-12 D5❌2          <Trace-Ende>                 NaN              0.0
                      D10                        0.161              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        1.063              0.0
        🪙❗            <Trace-Ende>                 NaN              0.0
2018-01 D5❌1          <Trace-Ende>                 NaN              0.0
                      D10                      140.855              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.619              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        0.110              0.0
2018-02 D5❌1          <Trace-Ende>                 NaN              0.0
                      D10                        1.093              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.397              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        0.894              0.0
2018-03 D5❌1          D10                        0.012              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.070              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        0.125              0.0
2018-04 D10           D10                        0.010              0.0
        D5❌1          <Trace-Ende>                 NaN              0.0
                      D10                        0.014              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.031              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        0.113              0.0
2018-05 D5❌1          <Trace-Ende>                 NaN              0.0
                      D10                        0.150              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.035              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        0.065              0.0
2018-06 D5❌1          <Trace-Ende>                 NaN              0.0
                      D10                        0.011              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.669              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        0.465              0.0
2018-07 D10           <Trace-Ende>                 NaN              0.0
                      D10                        0.014              0.0
        D5❌1          D10                        3.116              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.677              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        1.022              0.0
2018-08 D5❌1          D10                        0.740              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        9.394              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        1.450              0.0
2018-09 D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        4.084              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        0.141              0.0
2018-10 D5❌1          <Trace-Ende>                 NaN              0.0
                      D10                        0.483              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.133              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        0.171              0.0
2018-11 D10           D10                        1.103              0.0
        D5❌1          <Trace-Ende>                 NaN              0.0
                      D10                        0.386              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.131              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        0.195              0.0
2018-12 D10           D10                        0.001              0.0
        D5❌1          D10                        0.400              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.079              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        0.107              0.0

                                     Null_nach_Anteil  Anteil_im_Monat
Monat   Voraktivitaet Nachaktivitaet
2017-01 D5❌2          D10                         0.0            0.667
        D5❌5          D10                         0.0            0.333
2017-02 D10           D10                         0.0            0.091
        D5❌2          D10                         0.0            0.364
        D5❌5          <Trace-Ende>                NaN            0.182
                      D10                         0.0            0.364
2017-03 D5❌2          D10                         0.0            0.750
        D5❌5          D10                         0.0            0.250
2017-04 D5❌2          D10                         0.0            0.500
        D5❌5          <Trace-Ende>                NaN            0.167
                      D10                         0.0            0.333
2017-05 D5❌2          <Trace-Ende>                NaN            0.048
                      D10                         0.0            0.571
        D5❌5          <Trace-Ende>                NaN            0.095
                      D10                         0.0            0.286
2017-06 D5❌2          <Trace-Ende>                NaN            0.100
                      D10                         0.0            0.800
        D5❌5          D10                         0.0            0.100
2017-07 D5❌2          D10                         0.0            0.700
        D5❌5          <Trace-Ende>                NaN            0.100
                      D10                         0.0            0.200
2017-08 D5❌5          D10                         0.0            1.000
2017-09 D5❌2          D10                         0.0            0.182
        D5❌5          <Trace-Ende>                NaN            0.364
                      D10                         0.0            0.455
2017-10 D5❌2          <Trace-Ende>                NaN            0.200
                      D10                         0.0            0.600
        D5❌5          D10                         0.0            0.200
2017-11 D5❌2          D10                         0.0            0.636
        D5❌5          <Trace-Ende>                NaN            0.091
                      D10                         0.0            0.273
2017-12 D5❌2          <Trace-Ende>                NaN            0.074
                      D10                         0.0            0.222
        D5❌5          <Trace-Ende>                NaN            0.370
                      D10                         0.0            0.296
        🪙❗            <Trace-Ende>                NaN            0.037
2018-01 D5❌1          <Trace-Ende>                NaN            0.097
                      D10                         0.0            0.016
        D5❌5          <Trace-Ende>                NaN            0.097
                      D10                         0.0            0.113
        D5❌6          <Trace-Ende>                NaN            0.145
                      D10                         0.0            0.532
2018-02 D5❌1          <Trace-Ende>                NaN            0.012
                      D10                         0.0            0.143
        D5❌5          <Trace-Ende>                NaN            0.036
                      D10                         0.0            0.262
        D5❌6          <Trace-Ende>                NaN            0.143
                      D10                         0.0            0.405
2018-03 D5❌1          D10                         0.0            0.039
        D5❌5          <Trace-Ende>                NaN            0.091
                      D10                         0.0            0.234
        D5❌6          <Trace-Ende>                NaN            0.156
                      D10                         0.0            0.481
2018-04 D10           D10                         0.0            0.025
        D5❌1          <Trace-Ende>                NaN            0.013
                      D10                         0.0            0.051
        D5❌5          <Trace-Ende>                NaN            0.013
                      D10                         0.0            0.241
        D5❌6          <Trace-Ende>                NaN            0.101
                      D10                         0.0            0.557
2018-05 D5❌1          <Trace-Ende>                NaN            0.021
                      D10                         0.0            0.021
        D5❌5          <Trace-Ende>                NaN            0.041

=== International Declaration ===

                                      Anzahl  Traces  Median_vor_Tage  \
Monat   Voraktivitaet Nachaktivitaet
2017-01 D5❌2          D10                  5       5            1.811
        D5❌5          D10                  4       3            1.914
2017-02 D10           D10                  1       1            0.000
        D5❌2          D10                  6       6            0.637
        D5❌5          <Trace-Ende>         2       2            0.537
                      D10                  8       8            5.194
2017-03 D5❌2          D10                 10       9            0.090
        D5❌5          D10                  3       3            3.616
2017-04 D5❌2          D10                  8       8            1.582
        D5❌5          <Trace-Ende>         2       2            5.252
                      D10                  4       4            0.577
2017-05 D5❌2          <Trace-Ende>         1       1            2.678
                      D10                 13      12            0.795
        D5❌5          <Trace-Ende>         2       2            0.109
                      D10                  6       6            3.137
2017-06 D5❌2          <Trace-Ende>         1       1            0.242
                      D10                  8       8            2.354
        D5❌5          D10                  2       2            0.154
2017-07 D5❌2          D10                  7       7            1.288
        D5❌5          <Trace-Ende>         1       1            5.310
                      D10                  2       2            0.150
2017-08 D5❌5          D10                  1       1            4.100
2017-09 D5❌2          D10                  2       2            0.547
        D5❌5          <Trace-Ende>         4       4            1.032
                      D10                  5       4            1.957
2017-10 D5❌2          <Trace-Ende>         4       4            0.903
                      D10                 12      10            1.065
        D5❌5          D10                  4       4            0.668
2017-11 D5❌2          D10                  7       7            0.255
        D5❌5          <Trace-Ende>         1       1            0.050
                      D10                  3       3            1.583
2017-12 D5❌2          <Trace-Ende>         2       2            0.103
                      D10                  6       6            1.494
        D5❌5          <Trace-Ende>        10      10           11.787
                      D10                  8       8            0.752
        🪙❗            <Trace-Ende>         1       1            1.625
2018-01 D5❌1          <Trace-Ende>         6       6            0.673
                      D10                  1       1            0.214
        D5❌5          <Trace-Ende>         6       6           28.955
                      D10                  9       8            0.503
        D5❌6          <Trace-Ende>        11      11            2.930
                      D10                 38      37            1.144
2018-02 D5❌1          <Trace-Ende>         1       1            1.884
                      D10                 12      11            4.923
        D5❌5          <Trace-Ende>         4       4            5.154
                      D10                 22      21            1.116
        D5❌6          <Trace-Ende>        13      13            0.720
                      D10                 57      54            1.170
2018-03 D5❌1          D10                  3       3            2.114
        D5❌5          <Trace-Ende>         7       7            0.698
                      D10                 18      18            0.951
        D5❌6          <Trace-Ende>        15      15            1.150
                      D10                 51      43            1.415
2018-04 D10           D10                  2       2            0.000
        D5❌1          <Trace-Ende>         1       1            0.033
                      D10                  4       4            0.523
        D5❌5          <Trace-Ende>         1       1            8.912
                      D10                 19      19            0.932
        D5❌6          <Trace-Ende>        10      10            0.622
                      D10                 53      49            0.911
2018-05 D5❌1          <Trace-Ende>         2       2            2.011
                      D10                  3       3            1.124
        D5❌5          <Trace-Ende>         4       4            0.593
                      D10                  9       9            2.037
        D5❌6          <Trace-Ende>        11      11            1.774
                      D10                 70      62            0.633
2018-06 D5❌1          <Trace-Ende>         1       1            5.213
                      D10                  4       4            1.072
        D5❌5          <Trace-Ende>         3       3            3.287
                      D10                 20      20            0.747
        D5❌6          <Trace-Ende>        20      20            0.520
                      D10                 99      89            0.739
2018-07 D10           <Trace-Ende>         1       1            0.000
                      D10                  1       1            0.000
        D5❌1          D10                  4       4            1.380
        D5❌5          <Trace-Ende>         3       3            3.295
                      D10                  9       9            1.037
        D5❌6          <Trace-Ende>        20      20            0.573
                      D10                123     111            1.017
2018-08 D5❌1          D10                  1       1            0.156
        D5❌5          <Trace-Ende>         1       1            0.092
                      D10                  4       4            3.016
        D5❌6          <Trace-Ende>        10      10            1.127
                      D10                 45      41            1.765
2018-09 D5❌5          <Trace-Ende>         7       7            0.993
                      D10                 11      11            5.051
        D5❌6          <Trace-Ende>        11      11            2.905
                      D10                 67      57            1.519
2018-10 D5❌1          <Trace-Ende>         1       1            1.027
                      D10                  4       4            3.335
        D5❌5          <Trace-Ende>         5       5            2.052
                      D10                 25      24            1.798
        D5❌6          <Trace-Ende>        33      33            2.248
                      D10                 53      48            0.980
2018-11 D10           D10                  1       1            0.000
        D5❌1          <Trace-Ende>         1       1            6.370
                      D10                  3       3            0.553
        D5❌5          <Trace-Ende>         2       2            5.650
                      D10                 17      16            1.277
        D5❌6          <Trace-Ende>        24      24            0.877
                      D10                 66      63            0.938
2018-12 D10           D10                  1       1            0.000
        D5❌1          D10                  7       7            0.839
        D5❌5          <Trace-Ende>         1       1            0.736
                      D10                 18      18            0.307
        D5❌6          <Trace-Ende>        28      28            0.889
                      D10                 73      68            0.877

                                      Median_nach_Tage  Null_vor_Anteil  \
Monat   Voraktivitaet Nachaktivitaet
2017-01 D5❌2          D10                        0.068              0.0
        D5❌5          D10                        0.158              0.0
2017-02 D10           D10                        0.011              0.0
        D5❌2          D10                        0.026              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        2.799              0.0
2017-03 D5❌2          D10                        0.007              0.0
        D5❌5          D10                        0.050              0.0
2017-04 D5❌2          D10                        0.135              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.386              0.0
2017-05 D5❌2          <Trace-Ende>                 NaN              0.0
                      D10                        3.006              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        2.375              0.0
2017-06 D5❌2          <Trace-Ende>                 NaN              0.0
                      D10                        0.274              0.0
        D5❌5          D10                        0.346              0.0
2017-07 D5❌2          D10                        0.009              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.004              0.0
2017-08 D5❌5          D10                        0.089              0.0
2017-09 D5❌2          D10                        0.003              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.214              0.0
2017-10 D5❌2          <Trace-Ende>                 NaN              0.0
                      D10                        0.115              0.0
        D5❌5          D10                        1.425              0.0
2017-11 D5❌2          D10                        0.085              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.055              0.0
2017-12 D5❌2          <Trace-Ende>                 NaN              0.0
                      D10                        0.161              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        1.063              0.0
        🪙❗            <Trace-Ende>                 NaN              0.0
2018-01 D5❌1          <Trace-Ende>                 NaN              0.0
                      D10                      140.855              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.618              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        0.106              0.0
2018-02 D5❌1          <Trace-Ende>                 NaN              0.0
                      D10                        1.093              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.397              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        0.371              0.0
2018-03 D5❌1          D10                        0.012              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.070              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        0.235              0.0
2018-04 D10           D10                        0.010              0.0
        D5❌1          <Trace-Ende>                 NaN              0.0
                      D10                        0.014              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.031              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        0.154              0.0
2018-05 D5❌1          <Trace-Ende>                 NaN              0.0
                      D10                        0.104              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.035              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        0.069              0.0
2018-06 D5❌1          <Trace-Ende>                 NaN              0.0
                      D10                        0.011              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.669              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        0.358              0.0
2018-07 D10           <Trace-Ende>                 NaN              0.0
                      D10                        0.014              0.0
        D5❌1          D10                        3.116              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.677              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        1.022              0.0
2018-08 D5❌1          D10                        0.740              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        9.394              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        1.450              0.0
2018-09 D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        7.117              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        0.142              0.0
2018-10 D5❌1          <Trace-Ende>                 NaN              0.0
                      D10                        0.483              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.133              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        0.174              0.0
2018-11 D10           D10                        1.103              0.0
        D5❌1          <Trace-Ende>                 NaN              0.0
                      D10                        0.386              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.131              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        0.186              0.0
2018-12 D10           D10                        0.001              0.0
        D5❌1          D10                        0.400              0.0
        D5❌5          <Trace-Ende>                 NaN              0.0
                      D10                        0.079              0.0
        D5❌6          <Trace-Ende>                 NaN              0.0
                      D10                        0.109              0.0

                                     Null_nach_Anteil  Anteil_im_Monat
Monat   Voraktivitaet Nachaktivitaet
2017-01 D5❌2          D10                         0.0            0.556
        D5❌5          D10                         0.0            0.444
2017-02 D10           D10                         0.0            0.059
        D5❌2          D10                         0.0            0.353
        D5❌5          <Trace-Ende>                NaN            0.118
                      D10                         0.0            0.471
2017-03 D5❌2          D10                         0.0            0.769
        D5❌5          D10                         0.0            0.231
2017-04 D5❌2          D10                         0.0            0.571
        D5❌5          <Trace-Ende>                NaN            0.143
                      D10                         0.0            0.286
2017-05 D5❌2          <Trace-Ende>                NaN            0.045
                      D10                         0.0            0.591
        D5❌5          <Trace-Ende>                NaN            0.091
                      D10                         0.0            0.273
2017-06 D5❌2          <Trace-Ende>                NaN            0.091
                      D10                         0.0            0.727
        D5❌5          D10                         0.0            0.182
2017-07 D5❌2          D10                         0.0            0.700
        D5❌5          <Trace-Ende>                NaN            0.100
                      D10                         0.0            0.200
2017-08 D5❌5          D10                         0.0            1.000
2017-09 D5❌2          D10                         0.0            0.182
        D5❌5          <Trace-Ende>                NaN            0.364
                      D10                         0.0            0.455
2017-10 D5❌2          <Trace-Ende>                NaN            0.200
                      D10                         0.0            0.600
        D5❌5          D10                         0.0            0.200
2017-11 D5❌2          D10                         0.0            0.636
        D5❌5          <Trace-Ende>                NaN            0.091
                      D10                         0.0            0.273
2017-12 D5❌2          <Trace-Ende>                NaN            0.074
                      D10                         0.0            0.222
        D5❌5          <Trace-Ende>                NaN            0.370
                      D10                         0.0            0.296
        🪙❗            <Trace-Ende>                NaN            0.037
2018-01 D5❌1          <Trace-Ende>                NaN            0.085
                      D10                         0.0            0.014
        D5❌5          <Trace-Ende>                NaN            0.085
                      D10                         0.0            0.127
        D5❌6          <Trace-Ende>                NaN            0.155
                      D10                         0.0            0.535
2018-02 D5❌1          <Trace-Ende>                NaN            0.009
                      D10                         0.0            0.110
        D5❌5          <Trace-Ende>                NaN            0.037
                      D10                         0.0            0.202
        D5❌6          <Trace-Ende>                NaN            0.119
                      D10                         0.0            0.523
2018-03 D5❌1          D10                         0.0            0.032
        D5❌5          <Trace-Ende>                NaN            0.074
                      D10                         0.0            0.191
        D5❌6          <Trace-Ende>                NaN            0.160
                      D10                         0.0            0.543
2018-04 D10           D10                         0.0            0.022
        D5❌1          <Trace-Ende>                NaN            0.011
                      D10                         0.0            0.044
        D5❌5          <Trace-Ende>                NaN            0.011
                      D10                         0.0            0.211
        D5❌6          <Trace-Ende>                NaN            0.111
                      D10                         0.0            0.589
2018-05 D5❌1          <Trace-Ende>                NaN            0.020
                      D10                         0.0            0.030
        D5❌5          <Trace-Ende>                NaN            0.040

=== International Permit ===

                                      Anzahl  Traces  Median_vor_Tage  \
Monat   Voraktivitaet Nachaktivitaet
2017-01 P5❌5          P10                  1       1            0.065
2017-03 P5❌2          P10                  3       3            2.834
        P5❌5          P10                  3       3            0.638
2017-04 P5❌2          P10                  8       7            0.040
        P5❌5          P10                  1       1            4.148
2017-05 P5❌2          P10                  4       4            0.752
        P5❌5          P10                  7       7            2.233
2017-06 P5❌2          P10                  3       3            0.040
        P5❌5          P10                  1       1            0.597
2017-07 P5❌5          P10                  2       2            2.112
2017-08 P5❌2          P10                  1       1            4.847
        P5❌5          P10                  1       1            0.025
2017-09 P5❌2          P10                  5       5            0.826
2017-10 P5❌5          P10                  3       3            7.974
2017-11 P5❌2          P10                  1       1            5.070
2018-01 P5❌1          P10                  4       3            0.828
        P5❌5          P10                  3       3           29.787
2018-02 P5❌1          P10                  2       2            3.982
        P5❌5          P10                  1       1            1.230
        P5❌6          P10                  6       5            1.105
2018-03 P5❌1          P10                  5       5            1.801
        P5❌5          P10                  4       4            1.013
        P5❌6          P10                  4       4            1.533
2018-04 P5❌1          P10                  2       2            0.922
        P5❌5          P10                 10      10            4.121
        P5❌6          P10                  2       2            0.787
2018-05 P5❌5          P10                  7       7            0.970
        P5❌6          P10                 11      11            0.548
2018-06 P5❌1          P10                  6       6            1.361
        P5❌5          P10                  9       9            5.105
        P5❌6          P10                 16      16            0.727
2018-07 P5❌1          P10                  5       5            1.105
        P5❌5          P10                 13      13            5.000
        P5❌6          P10                 10      10            1.196
2018-08 P10           P10                  2       2            0.015
        P5❌1          P10                  2       2            1.630
        P5❌5          P10                  4       4            0.598
        P5❌6          P10                 12      11            0.539
2018-09 P5❌5          P10                  7       7            0.954
        P5❌6          P10                  8       8            0.792
        P5❌7          P10                  1       1            5.014
2018-10 P5❌1          P10                  2       2            5.112
        P5❌5          P10                  8       8            0.735
        P5❌6          P10                  6       6            1.486
2018-11 P5❌1          P10                  3       3            2.908
        P5❌5          P10                  5       5            0.734
        P5❌6          P10                  4       4            0.769
2018-12 P5❌5          P10                  1       1            1.126
        P5❌6          P10                  2       2            0.525

                                      Median_nach_Tage  Null_vor_Anteil  \
Monat   Voraktivitaet Nachaktivitaet
2017-01 P5❌5          P10                        0.007              0.0
2017-03 P5❌2          P10                        0.042              0.0
        P5❌5          P10                        0.733              0.0
2017-04 P5❌2          P10                        0.007              0.0
        P5❌5          P10                        0.731              0.0
2017-05 P5❌2          P10                        0.055              0.0
        P5❌5          P10                        0.047              0.0
2017-06 P5❌2          P10                        0.059              0.0
        P5❌5          P10                        0.043              0.0
2017-07 P5❌5          P10                       11.744              0.0
2017-08 P5❌2          P10                        0.001              0.0
        P5❌5          P10                        0.006              0.0
2017-09 P5❌2          P10                        2.457              0.0
2017-10 P5❌5          P10                        0.885              0.0
2017-11 P5❌2          P10                       10.848              0.0
2018-01 P5❌1          P10                        0.092              0.0
        P5❌5          P10                        3.079              0.0
2018-02 P5❌1          P10                        5.648              0.0
        P5❌5          P10                        0.713              0.0
        P5❌6          P10                        0.019              0.0
2018-03 P5❌1          P10                        6.858              0.0
        P5❌5          P10                        1.022              0.0
        P5❌6          P10                        4.680              0.0
2018-04 P5❌1          P10                        9.623              0.0
        P5❌5          P10                        0.052              0.0
        P5❌6          P10                        0.076              0.0
2018-05 P5❌5          P10                        0.255              0.0
        P5❌6          P10                        0.897              0.0
2018-06 P5❌1          P10                        0.575              0.0
        P5❌5          P10                        4.183              0.0
        P5❌6          P10                        0.060              0.0
2018-07 P5❌1          P10                        1.870              0.0
        P5❌5          P10                        3.011              0.0
        P5❌6          P10                        7.653              0.0
2018-08 P10           P10                        4.227              0.0
        P5❌1          P10                        2.404              0.0
        P5❌5          P10                        0.004              0.0
        P5❌6          P10                        1.907              0.0
2018-09 P5❌5          P10                        0.031              0.0
        P5❌6          P10                        4.467              0.0
        P5❌7          P10                        1.007              0.0
2018-10 P5❌1          P10                       12.717              0.0
        P5❌5          P10                        1.319              0.0
        P5❌6          P10                        0.031              0.0
2018-11 P5❌1          P10                        0.003              0.0
        P5❌5          P10                        1.020              0.0
        P5❌6          P10                        2.700              0.0
2018-12 P5❌5          P10                        0.010              0.0
        P5❌6          P10                        3.649              0.0

                                      Null_nach_Anteil  Anteil_im_Monat
Monat   Voraktivitaet Nachaktivitaet
2017-01 P5❌5          P10                          0.0            1.000
2017-03 P5❌2          P10                          0.0            0.500
        P5❌5          P10                          0.0            0.500
2017-04 P5❌2          P10                          0.0            0.889
        P5❌5          P10                          0.0            0.111
2017-05 P5❌2          P10                          0.0            0.364
        P5❌5          P10                          0.0            0.636
2017-06 P5❌2          P10                          0.0            0.750
        P5❌5          P10                          0.0            0.250
2017-07 P5❌5          P10                          0.0            1.000
2017-08 P5❌2          P10                          0.0            0.500
        P5❌5          P10                          0.0            0.500
2017-09 P5❌2          P10                          0.0            1.000
2017-10 P5❌5          P10                          0.0            1.000
2017-11 P5❌2          P10                          0.0            1.000
2018-01 P5❌1          P10                          0.0            0.571
        P5❌5          P10                          0.0            0.429
2018-02 P5❌1          P10                          0.0            0.222
        P5❌5          P10                          0.0            0.111
        P5❌6          P10                          0.0            0.667
2018-03 P5❌1          P10                          0.0            0.385
        P5❌5          P10                          0.0            0.308
        P5❌6          P10                          0.0            0.308
2018-04 P5❌1          P10                          0.0            0.143
        P5❌5          P10                          0.0            0.714
        P5❌6          P10                          0.0            0.143
2018-05 P5❌5          P10                          0.0            0.389
        P5❌6          P10                          0.0            0.611
2018-06 P5❌1          P10                          0.0            0.194
        P5❌5          P10                          0.0            0.290
        P5❌6          P10                          0.0            0.516
2018-07 P5❌1          P10                          0.0            0.179
        P5❌5          P10                          0.0            0.464
        P5❌6          P10                          0.0            0.357
2018-08 P10           P10                          0.0            0.100
        P5❌1          P10                          0.0            0.100
        P5❌5          P10                          0.0            0.200
        P5❌6          P10                          0.0            0.600
2018-09 P5❌5          P10                          0.0            0.438
        P5❌6          P10                          0.0            0.500
        P5❌7          P10                          0.0            0.062
2018-10 P5❌1          P10                          0.0            0.125
        P5❌5          P10                          0.0            0.500
        P5❌6          P10                          0.0            0.375
2018-11 P5❌1          P10                          0.0            0.250
        P5❌5          P10                          0.0            0.417
        P5❌6          P10                          0.0            0.333
2018-12 P5❌5          P10                          0.0            0.333
        P5❌6          P10                          0.0            0.667

In [37]:
from python_analysis.functions import rejections_without_employee_followup
from python_analysis.functions import variants

missing_employee_followup = {}
for name in ("domestic", "international"):
    result = rejections_without_employee_followup(logs[name])
    missing_employee_followup[name] = result
    print(f"{name}: {len(result['cases'])} Traces mit insgesamt {len(result['events'])} Treffern")
    matching_traces = logs[name].loc[
        logs[name]["case:concept:name"].isin(result["cases"].index)
        & ~logs[name]["concept:name"].isin({"Start trip", "End trip"})
    ]
    with pd.option_context("display.max_rows", None, "display.max_colwidth", None):
        display(variants(matching_traces))

domestic: 115 Traces mit insgesamt 124 Treffern

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,40,40/115 [34.78%],14.078148,22.539657
1,D10 > D5✅5 > D5❌_,21,21/115 [18.26%],0.807546,10.098172
2,D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,7,7/115 [6.09%],24.062037,56.966915
3,D10 > D5❌6,5,5/115 [4.35%],114.757766,159.781819
4,D10 > D5❌6 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,3,3/115 [2.61%],13.314201,81.505027
5,D10 > D5✅5 > 🪙❓ > D5❌_,3,3/115 [2.61%],29.876088,47.608318
6,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/115 [1.74%],7.152188,7.152188
7,D10 > D5❌6 > D10 > D5❌6 > D5❌0,2,2/115 [1.74%],2.609421,2.609421
8,D10 > D36 > D5❌5,2,2/115 [1.74%],9.421424,9.421424
9,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,2,2/115 [1.74%],15.131047,15.131047
10,D10 > D32 > D5✅5 > D5❌_,2,2/115 [1.74%],5.980897,5.980897
11,D10 > D32 > D5✅5 > D5❌_ > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/115 [0.87%],344.318148,344.318148
12,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D10 > D46 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/115 [0.87%],33.812755,33.812755
13,D10 > D5✅5 > D5❌_ > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/115 [0.87%],63.305845,63.305845
14,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/115 [0.87%],45.214120,45.214120
15,D10 > D5✅5 > D5❌_ > D10 > D5❌6 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/115 [0.87%],172.995660,172.995660
16,D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/115 [0.87%],64.170833,64.170833
17,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌0,1,1/115 [0.87%],7.757998,7.757998
18,D10 > D5❌6 > D10 > D36 > D5❌5 > D5❌0,1,1/115 [0.87%],1.225035,1.225035
19,D10 > D36 > D5❌5 > D10 > D36 > D5✅5 > 🪙❗,1,1/115 [0.87%],66.298032,66.298032
20,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/115 [0.87%],17.154861,17.154861
21,D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/115 [0.87%],20.824352,20.824352
22,D10 > D36 > D31 > D5❌5,1,1/115 [0.87%],5.089850,5.089850
23,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/115 [0.87%],13.042951,13.042951
24,D10 > D36 > D5❌5 > D10 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/115 [0.87%],18.062639,18.062639
25,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5,1,1/115 [0.87%],2.101748,2.101748
26,D10 > D5✅5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/115 [0.87%],17.064792,17.064792
27,D10 > D5✅5 > D5❌_ > D10 > D5✅5 > D5❌_,1,1/115 [0.87%],2.179780,2.179780
28,D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/115 [0.87%],17.377685,17.377685
29,D10 > D5❌2 > D10 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/115 [0.87%],8.374780,8.374780
30,D10 > D5❌5 > D5❌0 > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/115 [0.87%],23.052303,23.052303
31,D10 > D45 > D5❌_,1,1/115 [0.87%],0.793634,0.793634
32,D10 > D5✅5 > D5❌_ > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/115 [0.87%],16.105567,16.105567
33,D10 > D5❌5 > 🪙❓ > 🪙❗ > D5❌0,1,1/115 [0.87%],11.871516,11.871516
34,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > D5❌_,1,1/115 [0.87%],47.078252,47.078252
35,D10 > D5✅5 > D5❌_ > D10 > D5❌5 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/115 [0.87%],16.774051,16.774051
36,D10 > D42 > D5❌_,1,1/115 [0.87%],4.134444,4.134444

international: 166 Traces mit insgesamt 178 Treffern

,Ablauf,Traces,Anteil,Median (Tage),Durchschnitt (Tage)
0,P10 > P5✅5 > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,25,25/166 [15.06%],62.365602,74.538307
1,P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,23,23/166 [13.86%],121.253727,119.723671
2,P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > D5❌_,9,9/166 [5.42%],79.934699,67.688011
3,P10 > P5✅5 > P5❌_ > P10 > P5✅5 > D10 > D5✅5 > 🪙❓ > 🪙❗,6,6/166 [3.61%],71.330087,75.342544
4,P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > 🪙❓ > P5❌_ > 🪙❗,5,5/166 [3.01%],90.090903,84.907579
5,P10 > P5✅5 > D10 > D5✅5 > 🪙❓ > P5❌_ > 🪙❗,5,5/166 [3.01%],84.361412,68.723738
6,P10 > P35 > P5✅7 > D10 > D35 > D5✅7 > D5❌_ > D10 > D35 > D5✅7 > 🪙❓ > 🪙❗,4,4/166 [2.41%],92.741985,103.960174
7,P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,4,4/166 [2.41%],88.470168,86.104928
8,P10 > P32 > P5✅5 > P5❌_ > P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,4,4/166 [2.41%],211.632436,170.632740
9,P10 > P35 > P5✅7 > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,4,4/166 [2.41%],84.124196,89.399873
10,P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,3,3/166 [1.81%],92.132789,93.727585
11,P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,3,3/166 [1.81%],77.392188,122.594915
12,P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > D5❌_ > P5❌_,3,3/166 [1.81%],126.895231,121.879190
13,P10 > P5❌6 > P10 > P5❌0 > P10 > P36 > P31 > P5✅5 > 📨 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/166 [1.20%],58.649277,58.649277
14,P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,2,2/166 [1.20%],68.177303,68.177303
15,P10 > P36 > P5✅5 > D10 > D5❌6 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,2,2/166 [1.20%],97.715822,97.715822
16,P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > P5❌_ > 🪙❓ > 🪙❗,2,2/166 [1.20%],112.001626,112.001626
17,P10 > P35 > P5✅7 > P5❌_ > P10 > P35 > P5✅7 > D10 > D35 > D5✅7 > 🪙❓ > 🪙❗,2,2/166 [1.20%],69.271933,69.271933
18,P10 > P5✅5 > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,2,2/166 [1.20%],56.546580,56.546580
19,P10 > P5✅5 > D10 > D5✅5 > D5❌_,2,2/166 [1.20%],35.094433,35.094433
20,P10 > P32 > P5✅5 > D10 > D5❌2 > D5❌0 > P5❌_,2,2/166 [1.20%],89.869884,89.869884
21,P10 > P32 > P5✅5 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,2,2/166 [1.20%],99.837384,99.837384
22,P10 > P5✅5 > D20 > P5❌_,2,2/166 [1.20%],102.834844,102.834844
23,P10 > P36 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],86.120706,86.120706
24,D10 > D5✅5 > D5❌_ > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],17.259421,17.259421
25,D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],40.093542,40.093542
26,D10 > D5✅5 > D5❌_,1,1/166 [0.60%],0.815324,0.815324
27,D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],9.172801,9.172801
28,D10 > D35 > D5✅7 > D5❌_ > D10 > D35 > D5✅7 > 🪙❓ > 🪙❗,1,1/166 [0.60%],48.153854,48.153854
29,D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],10.022199,10.022199
30,P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],70.280382,70.280382
31,P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/166 [0.60%],5.673229,5.673229
32,P10 > P36 > P5✅5 > 📨 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],123.067743,123.067743
33,P10 > P36 > P31 > P35 > P5✅7 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/166 [0.60%],54.778241,54.778241
34,P10 > P36 > P5✅5 > D10 > D36 > D5❌5,1,1/166 [0.60%],24.965035,24.965035
35,P10 > P36 > P31 > P5❌5 > P10 > P36 > P31 > P5✅5 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],83.099259,83.099259
36,P10 > P36 > P31 > P5✅5 > 📨 > D10 > D5❌6 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],29.051053,29.051053
37,P10 > P36 > P31 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D36 > D31 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],147.185671,147.185671
38,P10 > P36 > P5✅5 > D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],58.137303,58.137303
39,P10 > P36 > P5✅5 > 📨 > D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],97.070613,97.070613
40,P10 > P36 > P5✅5 > D10 > D36 > D5❌5 > D10 > D36 > D5❌5 > D5❌0,1,1/166 [0.60%],48.158507,48.158507
41,P10 > P36 > P5✅5 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/166 [0.60%],47.951262,47.951262
42,P10 > P36 > P5✅5 > D10 > D36 > P5❌_ > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],45.081296,45.081296
43,P10 > P36 > P31 > 📨 > P5✅5 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/166 [0.60%],62.820301,62.820301
44,P10 > P36 > P5✅5 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/166 [0.60%],274.857720,274.857720
45,P10 > P36 > P31 > P35 > P5✅7 > D10 > D36 > D31 > D5❌5 > D10 > D36 > D31 > D5✅5 > 🪙❗,1,1/166 [0.60%],244.294769,244.294769
46,P10 > P32 > P35 > P5✅7 > D10 > D32 > D35 > D5✅7 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],98.133530,98.133530
47,P10 > P35 > P5✅7 > P5❌_ > P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],247.237685,247.237685
48,P10 > P35 > P5✅7 > D10 > P5❌_ > P10 > P32 > P5✅5 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],195.237662,195.237662
49,P10 > P35 > P5✅7 > D10 > D35 > D5✅7 > D5❌_ > D10 > D35 > D5❌7 > D5❌0 > D10 > D35 > D5✅7 > 🪙❓ > 🪙❗,1,1/166 [0.60%],87.063032,87.063032
50,P10 > P32 > P35 > P5✅7 > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],148.109421,148.109421
51,P10 > P35 > P5✅7 > D20 > P5❌_,1,1/166 [0.60%],65.112824,65.112824
52,P10 > P32 > P35 > P5✅7 > D10 > D5❌2 > D5❌0 > D10 > D35 > D5✅7 > D5❌_ > D10 > D5✅7 > D35 > 🪙❓ > 🪙❗,1,1/166 [0.60%],138.237199,138.237199
53,P10 > P32 > P5✅5 > P5❌_ > P10 > P5✅5 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],51.224421,51.224421
54,P10 > P35 > P5✅7 > D10 > D32 > D35 > D5✅7 > D5❌_ > D10 > D32 > D35 > D5✅7 > 🪙❓ > 🪙❗,1,1/166 [0.60%],214.210336,214.210336
55,P10 > P5✅5 > P5❌_ > P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],220.276817,220.276817
56,P10 > P32 > P5✅5 > D10 > D32 > D5❌5 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],68.194039,68.194039
57,P10 > P32 > P5✅5 > D10 > D5✅5 > D5❌_,1,1/166 [0.60%],108.148148,108.148148
58,P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > D5❌_ > D10 > D36 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],182.315949,182.315949
59,P10 > P5✅5 > D10 > D5✅5 > P5❌_ > 🪙❓ > 🪙❗,1,1/166 [0.60%],84.361412,84.361412
60,P10 > P32 > P5✅5 > D10 > D5❌2 > P5❌_ > D5❌0,1,1/166 [0.60%],158.203576,158.203576
61,P10 > P5❌5 > P5❌0 > P10 > P5✅5 > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],86.807581,86.807581
62,P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],107.091424,107.091424
63,P10 > P5✅5 > D10 > D5❌5 > D5❌0 > D10 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],31.100428,31.100428
64,P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],55.221019,55.221019
65,P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D32 > D5✅5 > D5❌_ > D10 > D32 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],132.302257,132.302257
66,P10 > P5✅5 > P5❌_ > P10 > P5✅5 > P5❌_ > P10 > P5✅5 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],52.234745,52.234745
67,P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > D5❌_ > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],24.267384,24.267384
68,P10 > P32 > P5✅5 > D10 > D32 > D5✅5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],52.017650,52.017650
69,P10 > P35 > P5✅7 > P5❌_ > P10 > P35 > P5✅7 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],124.186539,124.186539
70,P10 > P35 > P5✅7 > P5❌_ > P10 > P5✅5 > D10 > D5✅5 > 🪙❓ > 🪙❗,1,1/166 [0.60%],80.289248,80.289248

In [38]:
#ACHTUNG- 2. und 3. Spaltung sind hier nur Eventmengen, keine Traces
events = pd.concat([
    logs["domestic"].assign(Log="domestic"),
    logs["int_without_trips"].assign(Log="international"),
], ignore_index=True)

events["Monat"] = pd.to_datetime(
    events["time:timestamp"], utc=True
).dt.strftime("%Y-%m")

trace_counts = (
    events.drop_duplicates(["Log", "case:concept:name", "Monat"])
    .groupby("Monat")
    .size()
    .rename("Traces insgesamt")
)

missing = events.loc[
    events["concept:name"].str.endswith("REJECTED by MISSING", na=False)
]

rejections = pd.crosstab(missing["Monat"], missing["concept:name"])

display(
    trace_counts.to_frame()
    .join(rejections)
    .fillna(0)
    .astype(int)
    .sort_index()
)

,Traces insgesamt,Declaration REJECTED by MISSING,Permit REJECTED by MISSING
Monat,,,
2017-01,278,14,0
2017-02,441,7,0
2017-03,495,0,0
2017-04,439,11,0
2017-05,557,19,5
2017-06,599,16,1
2017-07,497,24,12
2017-08,356,17,3
2017-09,561,40,4
2017-10,581,20,3
2017-11,535,13,8
2017-12,454,9,6
2018-01,1319,4,0
2018-02,1795,0,1
2018-03,2020,0,0
2018-04,2061,0,0
2018-05,1907,0,0
2018-06,2261,0,0
2018-07,2105,0,0
2018-08,1405,0,0
2018-09,1883,0,0
2018-10,2157,0,0
2018-11,1953,0,0
2018-12,1626,0,0
2019-01,423,0,0
2019-02,35,0,0
2019-03,2,0,0
2019-04,6,0,0
2019-06,1,0,0
2019-07,1,0,0
2019-08,1,0,0

In [39]:
log = logs["domestic"]

cases = (
    log.assign(Budget_Owner=log["org:role"].eq("BUDGET OWNER"))
    .groupby("case:concept:name")
    .agg(
        BudgetNumber=("case:BudgetNumber", "first"),
        Amount=("case:Amount", "first"),
        Budget_Owner=("Budget_Owner", "any"),
    )
)

cases["Budget_Owner"] = cases["Budget_Owner"].map({
    True: "beteiligt",
    False: "nicht beteiligt",
})

result = (
    cases.groupby(["BudgetNumber", "Budget_Owner"], dropna=False)
    .agg(
        Traces=("Amount", "size"),
        Mit_Betrag=("Amount", "count"),
        Min_Amount=("Amount", "min"),
        Max_Amount=("Amount", "max"),
    )
)

with pd.option_context("display.max_rows", None):
    display(result.style.format({
        "Min_Amount": "{:.2f}",
        "Max_Amount": "{:.2f}",
        "Spannweite": "{:.2f}",
    }, na_rep="—"))


log = logs["international"]
cases = (
    log.assign(Budget_Owner=log["org:role"].eq("BUDGET OWNER"))
    .groupby("case:concept:name")
    .agg(
        BudgetNumber=("case:BudgetNumber", "first"),
        Amount=("case:Amount", "first"),
        Budget_Owner=("Budget_Owner", "any"),
    )
)

cases["Budget_Owner"] = cases["Budget_Owner"].map({
    True: "beteiligt",
    False: "nicht beteiligt",
})

result = (
    cases.groupby(["BudgetNumber", "Budget_Owner"], dropna=False)
    .agg(
        Traces=("Amount", "size"),
        set_Betrag=("Amount", "count"),
        Min_Amount=("Amount", "min"),
        Max_Amount=("Amount", "max"),
    )
)

with pd.option_context("display.max_rows", None):
    display(result.style.format({
        "Min_Amount": "{:.2f}",
        "Max_Amount": "{:.2f}",
        "Spannweite": "{:.2f}",
    }, na_rep="—"))