In [2]:
%load_ext autoreload
%autoreload 2
import sys, warnings
sys.path.append('..')
warnings.filterwarnings('ignore')

import pandas as pd
import pm4py
from pm4py.visualization.petri_net import visualizer as pn_visualizer
from python_analysis.functions import (
    read_log, distinct_values, show_trace_rows, unique_analysis, field_summary, traces_without,
    trace_share, start_end, event_code_legend, variants,
    activity_table, equivalence_classes, template, cover_table, assign_classes,
    metric, discover_and_evaluate, compare, combine_partitions, style_stats,
    discover_inductive_noise_twentieth, discover_ilp, discover_powl, discover_inductive_noise_tenth,
    process_durations, bottleneck_analysis, rejection_analysis, unexpected_behavior,
    conformance_analysis, compare_declarations,
)

============================================================

  Welcome to PM4Py — Community Version
  Open-Source License (AGPL v3)

  📚 Docs & Examples:
     https://processintelligence.solutions/pm4py

  ⚖️  License: AGPL v3 — Commercial use requires open-sourcing your application.
     Business use without open-sourcing? A commercial license is available:
     https://processintelligence.solutions/pm4py#licensing

============================================================

In [3]:
##Daten lesen
dom_log_base = read_log('../data/DomesticDeclarations.xes')
int_log_base = read_log('../data/InternationalDeclarations.xes')

dummy = int_log_base["case:Permit id"].ne(int_log_base["case:Permit ID"])
decl_and_permit = int_log_base[~dummy].copy()
international_only_decl = int_log_base[dummy].copy()
declarations_only = pd.concat(
    [dom_log_base.assign(**{"case:source": "domestic"}),
     international_only_decl.assign(**{"case:source": "international"})],
    ignore_index=True,
).sort_values(["case:concept:name", "time:timestamp"], kind="stable", ignore_index=True)

logs = {"domestic": dom_log_base,
        "domestic_without_D20": dom_log_base[~dom_log_base["concept:name"].eq("Declaration SAVED by EMPLOYEE")],
        "international": int_log_base,
        "decl_only": declarations_only,
        "decl_only_without_trips": declarations_only[~declarations_only["concept:name"].isin({"Start trip", "End trip"})],
        "decl_and_permit": decl_and_permit,
        "decl_and_permit_without_trips": decl_and_permit[~decl_and_permit["concept:name"].isin({"Start trip", "End trip"})],
        "decl_and_permit_without_trips_or_D20": decl_and_permit[~decl_and_permit["concept:name"].isin({"Start trip", "End trip", "Declaration SAVED by EMPLOYEE"})],
        "international_only_decl": international_only_decl,
        "international_only_decl_without_trips": international_only_decl[~international_only_decl["concept:name"].isin({"Start trip", "End trip"})],
        "international_only_decl_without_trips_or_D20": international_only_decl[~international_only_decl["concept:name"].isin({"Start trip", "End trip", "Declaration SAVED by EMPLOYEE"})],
        }

parsing log, completed traces :: 100%|██████████| 10500/10500 [00:01<00:00, 8031.13it/s]
parsing log, completed traces :: 100%|██████████| 6449/6449 [00:01<00:00, 3580.33it/s]

In [4]:
##Datenfelder je Trace / Event
field_summary(logs).style \
    .set_caption("Datenfelder je Trace / Event") \
    .set_properties(**{"text-align": "left"})

In [5]:
print("\nDomestic Log (10500):")
for f in dom_log_base.columns:
    print(str(f) + ' : '+ str(len(distinct_values(dom_log_base, f))))

print("\nInternational Log (6449):")
for f in int_log_base.columns:
    print(str(f) + ' : '+ str(len(distinct_values(int_log_base, f))))

Domestic Log (10500):
id : 56437
org:resource : 2
concept:name : 17
time:timestamp : 45403
org:role : 7
case:id : 10500
case:concept:name : 10500
case:BudgetNumber : 1
case:DeclarationNumber : 10049
case:Amount : 8326

International Log (6449):
id : 69073
org:resource : 2
concept:name : 34
time:timestamp : 51270
org:role : 8
case:Permit travel permit number : 5596
case:DeclarationNumber : 6190
case:Amount : 6100
case:RequestedAmount : 6100
case:Permit TaskNumber : 6
case:Permit BudgetNumber : 207
case:OriginalAmount : 6100
case:Permit ProjectNumber : 825
case:concept:name : 6449
case:Permit OrganizationalEntity : 27
case:travel permit number : 6033
case:Permit RequestedBudget : 5259
case:id : 6449
case:Permit ID : 6028
case:Permit id : 5608
case:BudgetNumber : 719
case:Permit ActivityNumber : 145
case:AdjustedAmount : 6101

In [6]:
unique_analysis(int_log_base, ["case:OriginalAmount", "case:AdjustedAmount", "case:RequestedAmount", "case:Amount"])

,case:OriginalAmount,case:AdjustedAmount,case:RequestedAmount,case:Amount,traces
0,0.000000,0.000000,0.000000,0.000000,2251
1,45.654385,45.654385,45.654385,45.654385,73
2,64.473928,64.473928,64.473928,64.473928,72
3,49.536371,49.536371,49.536371,49.536371,58
4,35.122357,35.122357,35.122357,35.122357,52

True     6448
False       1
Name: count, dtype: int64

,case:id,case:OriginalAmount,case:AdjustedAmount,case:RequestedAmount,case:Amount
0,declaration 54434,0.0,100.494292,0.0,0.0

['declaration 54434']

In [7]:
#Permit Dummy Analyse 448 Traces
problematic = set(unique_analysis(int_log_base, ["case:Permit id", "case:Permit ID"]))
without_permit = traces_without(int_log_base, "Permit")

print("Traces ohne Permit-Event:", len(without_permit))
print("problematic_traces:", len(problematic))
print("Gleiche Menge:", without_permit == problematic)
print("Nur ohne Permit:", sorted(without_permit - problematic))
print("Nur in problematic_traces:", sorted(problematic - without_permit))

        case:Permit id       case:Permit ID  traces
0  travel permit 73562  travel permit 73562     170
1  travel permit 53343  travel permit 53343     140
2  travel permit 32577  travel permit 32577     115
3  travel permit 45618  travel permit 45618      98
4  travel permit 64232  travel permit 64232      84

True     6001
False     448
Name: count, dtype: int64

                case:id     case:Permit id        case:Permit ID
0    declaration 143637  travel permit 423  travel permit 143640
1    declaration 143644  travel permit 423  travel permit 143647
2    declaration 143578  travel permit 423  travel permit 143581
3    declaration 143585  travel permit 423  travel permit 143588
4    declaration 143657  travel permit 423  travel permit 143660
..                  ...                ...                   ...
443  declaration 147452  travel permit 423  travel permit 147455
444  declaration 147470  travel permit 423  travel permit 147473
445  declaration 147487  travel permit 423  travel permit 147490
446  declaration 147507  travel permit 423  travel permit 147509
447  declaration 147514  travel permit 423  travel permit 147517

[448 rows x 3 columns]

Traces ohne Permit-Event: 448
problematic_traces: 448
Gleiche Menge: True
Nur ohne Permit: []
Nur in problematic_traces: []

In [8]:
# Erst alle Aktivitäten anzeigen
event_types = pd.concat([pd.Series(dom_log_base["concept:name"].values), pd.Series(int_log_base["concept:name"].values)]).drop_duplicates().reset_index(drop=True).sort_values(ignore_index=True)
display(event_types)

# Dann Relationen finden: Wörter mit identischer Aktivitätsmenge bilden eine Äquivalenzklasse
acts = activity_table({"domestic": dom_log_base, "international": int_log_base})
eq = equivalence_classes(acts)
display(eq)

# Masken/Templates je Klasse definieren
eq["template"] = eq["members"].apply(template)
display(eq)

# Unnötige Masken entfernen, weil sie alles/nichts matchen
filtered_groups = eq[~eq["template"].str.fullmatch(r"[\s%]*", na=True)]
display(filtered_groups)

# Gruppen an Masken definieren, die genau jede Aktivität genau einmal abdecken
covers = cover_table(filtered_groups, set(acts.index))
display(covers)

acts["entity_classes"] = assign_classes(acts, filtered_groups, covers.at[1, "ids"])
acts["activity_classes"] = assign_classes(acts, filtered_groups, covers.at[11, "ids"])

0         Declaration APPROVED by ADMINISTRATION
1           Declaration APPROVED by BUDGET OWNER
2           Declaration APPROVED by PRE_APPROVER
3             Declaration APPROVED by SUPERVISOR
4         Declaration FINAL_APPROVED by DIRECTOR
5       Declaration FINAL_APPROVED by SUPERVISOR
6     Declaration FOR_APPROVAL by ADMINISTRATION
7       Declaration FOR_APPROVAL by PRE_APPROVER
8         Declaration FOR_APPROVAL by SUPERVISOR
9         Declaration REJECTED by ADMINISTRATION
10          Declaration REJECTED by BUDGET OWNER
11              Declaration REJECTED by DIRECTOR
12              Declaration REJECTED by EMPLOYEE
13               Declaration REJECTED by MISSING
14          Declaration REJECTED by PRE_APPROVER
15            Declaration REJECTED by SUPERVISOR
16                 Declaration SAVED by EMPLOYEE
17             Declaration SUBMITTED by EMPLOYEE
18                                      End trip
19                               Payment Handled
20             Permit APPROVED by ADMINISTRATION
21               Permit APPROVED by BUDGET OWNER
22               Permit APPROVED by PRE_APPROVER
23                 Permit APPROVED by SUPERVISOR
24             Permit FINAL_APPROVED by DIRECTOR
25           Permit FINAL_APPROVED by SUPERVISOR
26             Permit REJECTED by ADMINISTRATION
27               Permit REJECTED by BUDGET OWNER
28                   Permit REJECTED by DIRECTOR
29                   Permit REJECTED by EMPLOYEE
30                    Permit REJECTED by MISSING
31               Permit REJECTED by PRE_APPROVER
32                 Permit REJECTED by SUPERVISOR
33                  Permit SUBMITTED by EMPLOYEE
34                               Request Payment
35                                 Send Reminder
36                                    Start trip
dtype: str

,words,n,domestic,international,members
0,MEMBER STAFF,34,36353,59347,"[Declaration APPROVED by ADMINISTRATION, Decla..."
1,BY,32,36353,46449,"[Declaration APPROVED by ADMINISTRATION, Decla..."
2,DECLARATION,18,36353,25890,"[Declaration APPROVED by ADMINISTRATION, Decla..."
3,PERMIT,14,0,20559,"[Permit APPROVED by ADMINISTRATION, Permit APP..."
4,REJECTED,14,2846,4192,"[Declaration REJECTED by ADMINISTRATION, Decla..."
5,APPROVED,8,11707,15516,"[Declaration APPROVED by ADMINISTRATION, Decla..."
6,EMPLOYEE,7,13031,29338,"[Declaration REJECTED by EMPLOYEE, Declaration..."
7,SUPERVISOR,7,10425,12535,"[Declaration APPROVED by SUPERVISOR, Declarati..."
8,ADMINISTRATION,5,9155,11508,"[Declaration APPROVED by ADMINISTRATION, Decla..."
9,PRE_APPROVER,5,772,1255,"[Declaration APPROVED by PRE_APPROVER, Declara..."
10,BUDGET OWNER,4,2879,3668,"[Declaration APPROVED by BUDGET OWNER, Declara..."
11,DIRECTOR,4,0,897,"[Declaration FINAL_APPROVED by DIRECTOR, Decla..."
12,FINAL_APPROVED,4,10131,12312,"[Declaration FINAL_APPROVED by DIRECTOR, Decla..."
13,FOR_APPROVAL,3,3,0,"[Declaration FOR_APPROVAL by ADMINISTRATION, D..."
14,SYSTEM UNDEFINED,3,20084,12804,"[Payment Handled, Request Payment, Send Reminder]"
15,MISSING,2,91,146,"[Declaration REJECTED by MISSING, Permit REJEC..."
16,PAYMENT,2,20084,12370,"[Payment Handled, Request Payment]"
17,SUBMITTED,2,11531,14354,"[Declaration SUBMITTED by EMPLOYEE, Permit SUB..."
18,TRIP,2,0,12898,"[End trip, Start trip]"
19,END,1,0,6449,[End trip]
20,HANDLED,1,10044,6187,[Payment Handled]
21,REMINDER SEND,1,0,434,[Send Reminder]
22,REQUEST,1,10040,6183,[Request Payment]
23,SAVED,1,135,75,[Declaration SAVED by EMPLOYEE]
24,START,1,0,6449,[Start trip]

,words,n,domestic,international,members,template
0,MEMBER STAFF,34,36353,59347,"[Declaration APPROVED by ADMINISTRATION, Decla...",%
1,BY,32,36353,46449,"[Declaration APPROVED by ADMINISTRATION, Decla...",% by %
2,DECLARATION,18,36353,25890,"[Declaration APPROVED by ADMINISTRATION, Decla...",Declaration % by %
3,PERMIT,14,0,20559,"[Permit APPROVED by ADMINISTRATION, Permit APP...",Permit % by %
4,REJECTED,14,2846,4192,"[Declaration REJECTED by ADMINISTRATION, Decla...",% REJECTED by %
5,APPROVED,8,11707,15516,"[Declaration APPROVED by ADMINISTRATION, Decla...",% APPROVED by %
6,EMPLOYEE,7,13031,29338,"[Declaration REJECTED by EMPLOYEE, Declaration...",%
7,SUPERVISOR,7,10425,12535,"[Declaration APPROVED by SUPERVISOR, Declarati...",% by SUPERVISOR
8,ADMINISTRATION,5,9155,11508,"[Declaration APPROVED by ADMINISTRATION, Decla...",% by ADMINISTRATION
9,PRE_APPROVER,5,772,1255,"[Declaration APPROVED by PRE_APPROVER, Declara...",% by PRE_APPROVER
10,BUDGET OWNER,4,2879,3668,"[Declaration APPROVED by BUDGET OWNER, Declara...",% by BUDGET OWNER
11,DIRECTOR,4,0,897,"[Declaration FINAL_APPROVED by DIRECTOR, Decla...",% by DIRECTOR
12,FINAL_APPROVED,4,10131,12312,"[Declaration FINAL_APPROVED by DIRECTOR, Decla...",% FINAL_APPROVED by %
13,FOR_APPROVAL,3,3,0,"[Declaration FOR_APPROVAL by ADMINISTRATION, D...",Declaration FOR_APPROVAL by %
14,SYSTEM UNDEFINED,3,20084,12804,"[Payment Handled, Request Payment, Send Reminder]",%
15,MISSING,2,91,146,"[Declaration REJECTED by MISSING, Permit REJEC...",% REJECTED by MISSING
16,PAYMENT,2,20084,12370,"[Payment Handled, Request Payment]",% Payment %
17,SUBMITTED,2,11531,14354,"[Declaration SUBMITTED by EMPLOYEE, Permit SUB...",% SUBMITTED by EMPLOYEE
18,TRIP,2,0,12898,"[End trip, Start trip]",% trip
19,END,1,0,6449,[End trip],End trip
20,HANDLED,1,10044,6187,[Payment Handled],Payment Handled
21,REMINDER SEND,1,0,434,[Send Reminder],Send Reminder
22,REQUEST,1,10040,6183,[Request Payment],Request Payment
23,SAVED,1,135,75,[Declaration SAVED by EMPLOYEE],Declaration SAVED by EMPLOYEE
24,START,1,0,6449,[Start trip],Start trip

,words,n,domestic,international,members,template
1,BY,32,36353,46449,"[Declaration APPROVED by ADMINISTRATION, Decla...",% by %
2,DECLARATION,18,36353,25890,"[Declaration APPROVED by ADMINISTRATION, Decla...",Declaration % by %
3,PERMIT,14,0,20559,"[Permit APPROVED by ADMINISTRATION, Permit APP...",Permit % by %
4,REJECTED,14,2846,4192,"[Declaration REJECTED by ADMINISTRATION, Decla...",% REJECTED by %
5,APPROVED,8,11707,15516,"[Declaration APPROVED by ADMINISTRATION, Decla...",% APPROVED by %
7,SUPERVISOR,7,10425,12535,"[Declaration APPROVED by SUPERVISOR, Declarati...",% by SUPERVISOR
8,ADMINISTRATION,5,9155,11508,"[Declaration APPROVED by ADMINISTRATION, Decla...",% by ADMINISTRATION
9,PRE_APPROVER,5,772,1255,"[Declaration APPROVED by PRE_APPROVER, Declara...",% by PRE_APPROVER
10,BUDGET OWNER,4,2879,3668,"[Declaration APPROVED by BUDGET OWNER, Declara...",% by BUDGET OWNER
11,DIRECTOR,4,0,897,"[Declaration FINAL_APPROVED by DIRECTOR, Decla...",% by DIRECTOR
12,FINAL_APPROVED,4,10131,12312,"[Declaration FINAL_APPROVED by DIRECTOR, Decla...",% FINAL_APPROVED by %
13,FOR_APPROVAL,3,3,0,"[Declaration FOR_APPROVAL by ADMINISTRATION, D...",Declaration FOR_APPROVAL by %
15,MISSING,2,91,146,"[Declaration REJECTED by MISSING, Permit REJEC...",% REJECTED by MISSING
16,PAYMENT,2,20084,12370,"[Payment Handled, Request Payment]",% Payment %
17,SUBMITTED,2,11531,14354,"[Declaration SUBMITTED by EMPLOYEE, Permit SUB...",% SUBMITTED by EMPLOYEE
18,TRIP,2,0,12898,"[End trip, Start trip]",% trip
19,END,1,0,6449,[End trip],End trip
20,HANDLED,1,10044,6187,[Payment Handled],Payment Handled
21,REMINDER SEND,1,0,434,[Send Reminder],Send Reminder
22,REQUEST,1,10040,6183,[Request Payment],Request Payment
23,SAVED,1,135,75,[Declaration SAVED by EMPLOYEE],Declaration SAVED by EMPLOYEE
24,START,1,0,6449,[Start trip],Start trip

,n_groups,groups,ids
0,4,"[BY, PAYMENT, TRIP, REMINDER SEND]","[1, 16, 18, 21]"
1,5,"[DECLARATION, PERMIT, PAYMENT, TRIP, REMINDER ...","[2, 3, 16, 18, 21]"
2,5,"[BY, TRIP, HANDLED, REMINDER SEND, REQUEST]","[1, 18, 20, 21, 22]"
3,5,"[BY, PAYMENT, END, REMINDER SEND, START]","[1, 16, 19, 21, 24]"
4,6,"[DECLARATION, PERMIT, TRIP, HANDLED, REMINDER ...","[2, 3, 18, 20, 21, 22]"
5,6,"[DECLARATION, PERMIT, PAYMENT, END, REMINDER S...","[2, 3, 16, 19, 21, 24]"
6,6,"[BY, END, HANDLED, REMINDER SEND, REQUEST, START]","[1, 19, 20, 21, 22, 24]"
7,7,"[DECLARATION, PERMIT, END, HANDLED, REMINDER S...","[2, 3, 19, 20, 21, 22, 24]"
8,9,"[REJECTED, APPROVED, FINAL_APPROVED, FOR_APPRO...","[4, 5, 12, 13, 16, 17, 18, 21, 23]"
9,10,"[REJECTED, APPROVED, FINAL_APPROVED, FOR_APPRO...","[4, 5, 12, 13, 17, 18, 20, 21, 22, 23]"
10,10,"[REJECTED, APPROVED, FINAL_APPROVED, FOR_APPRO...","[4, 5, 12, 13, 16, 17, 19, 21, 23, 24]"
11,11,"[REJECTED, APPROVED, FINAL_APPROVED, FOR_APPRO...","[4, 5, 12, 13, 17, 19, 20, 21, 22, 23, 24]"

Menschliche Bewertung:
| index | Ausschlusskriterium? | Bewertung |
|-------|----------------------|-----------|
| 0     |Ja, durch "By" -> Permit/Declaration fälschlich zusammengefasst||
| 1     || Sehr gut, genau 5 Gruppen für 5 "menschlich erkennbare" [Entitätsklassen]|
| 2     |Ja, durch "By", s. (1)||
| 3     |Ja, durch "By", s. (1)||
| 4     |Ja, Aktivitäten und Entitäten werden gemischt "End, Payment, Start, etc."||
| 5     ||Ist okay, im Prinzip Gruppe (1), aber mit extra Aufteilung von "%Payment%-Aktivitäten"|
| 6     |Ja, durch "By", s. (1)||
| 7     |s. (4)||
| 8     |Ja, ähnlich zu (4) werden Aktivitäten und Entitäten gemischt (Trip, Reminder, Payment + Submitted, Approval...)||
| 9     |Ja, ebenfalls noch Entitäten (Trip) und Aktivitäten||
| 10    ||Fast gültig, es verbleiben noch eine zwei, die eineindeutige Aktivität (Reminder Send) und Payment, sonst alles abgedeckt|
| 11    ||Teilt wie bei (1) zu (5) nur das Payment auf, wodurch aber nur noch eine Entität mit eindeutiger Aktivität verbleibt -> Perfekt als [Aktivitätenklassen]|


Es verbleibt noch ein Problem, was nicht direkt ersichtlich ist: Durch die vorhandenen Matcher entsteht bei der Betrachtung der Events in ihren Klassen ein Informationsverlust bei den Aktivitäten durch den Matcher "%APPROVED %", deswegen darf beim Aufbau der Klassen nicht einfach eine Transformation zu Buchstaben erfolgen, sondern der Unterstrich beibehalten werden.

Die entstehenden Gruppierungen zeigen außerdem direkt auf, dass eindeutige Unterscheidungen nach Akteuren nicht zu einer allgemeingültigen bijektiven Abbildung führen und demnach nicht **eigenständig** geeignet für isolierte Analysen sind.

In [9]:
acts.groupby(["entity_classes", "activity_classes"])[["domestic", "international"]].sum()

                                                  domestic  international
entity_classes     activity_classes
% Payment %        Payment Handled                   10044           6187
                   Request Payment                   10040           6183
% trip             End trip                              0           6449
                   Start trip                            0           6449
Declaration % by % % APPROVED by %                   11707           7739
                   % FINAL_APPROVED by %             10131           6291
                   % REJECTED by %                    2846           3686
                   % SUBMITTED by EMPLOYEE           11531           8099
                   Declaration FOR_APPROVAL by %         3              0
                   Declaration SAVED by EMPLOYEE       135             75
Permit % by %      % APPROVED by %                       0           7777
                   % FINAL_APPROVED by %                 0           6021
                   % REJECTED by %                       0            506
                   % SUBMITTED by EMPLOYEE               0           6255
Send Reminder      Send Reminder                         0            434

In [10]:
trace_share(logs, "concept:name")

In [11]:
display(event_code_legend(logs))

with pd.option_context("display.max_colwidth", None):
    for name, log in logs.items():
        table = variants(log)
        print("" + "=" * 70)
        print(f"\n{name}: {len(table)} Abläufe")
        display(table)

                                  concept:name  Code
0       Declaration APPROVED by ADMINISTRATION   D36
1         Declaration APPROVED by BUDGET OWNER   D31
2         Declaration APPROVED by PRE_APPROVER   D32
3           Declaration APPROVED by SUPERVISOR   D35
4       Declaration FINAL_APPROVED by DIRECTOR  D5☑7
5     Declaration FINAL_APPROVED by SUPERVISOR  D5☑5
6   Declaration FOR_APPROVAL by ADMINISTRATION   D46
7     Declaration FOR_APPROVAL by PRE_APPROVER   D42
8       Declaration FOR_APPROVAL by SUPERVISOR   D45
9       Declaration REJECTED by ADMINISTRATION  D5❌6
10        Declaration REJECTED by BUDGET OWNER  D5❌1
11            Declaration REJECTED by DIRECTOR  D5❌7
12            Declaration REJECTED by EMPLOYEE  D5❌0
13             Declaration REJECTED by MISSING  D5❌_
14        Declaration REJECTED by PRE_APPROVER  D5❌2
15          Declaration REJECTED by SUPERVISOR  D5❌5
16               Declaration SAVED by EMPLOYEE   D20
17           Declaration SUBMITTED by EMPLOYEE   D10
18                                    End trip   T⬇️
19                             Payment Handled    🪙❗
20           Permit APPROVED by ADMINISTRATION   P36
21             Permit APPROVED by BUDGET OWNER   P31
22             Permit APPROVED by PRE_APPROVER   P32
23               Permit APPROVED by SUPERVISOR   P35
24           Permit FINAL_APPROVED by DIRECTOR  P5☑7
25         Permit FINAL_APPROVED by SUPERVISOR  P5☑5
26           Permit REJECTED by ADMINISTRATION  P5❌6
27             Permit REJECTED by BUDGET OWNER  P5❌1
28                 Permit REJECTED by DIRECTOR  P5❌7
29                 Permit REJECTED by EMPLOYEE  P5❌0
30                  Permit REJECTED by MISSING  P5❌_
31             Permit REJECTED by PRE_APPROVER  P5❌2
32               Permit REJECTED by SUPERVISOR  P5❌5
33                Permit SUBMITTED by EMPLOYEE   P10
34                             Request Payment    🪙❓
35                               Send Reminder     📨
36                                  Start trip   T⬆️

======================================================================

domestic: 99 Abläufe

,Ablauf,Traces,Anteil
0,D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,4618,4618/10500 [43.98%]
1,D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,2473,2473/10500 [23.55%]
2,D10 > D5☑5 > 🪙❓ > 🪙❗,1392,1392/10500 [13.26%]
3,D10 > D32 > D5☑5 > 🪙❓ > 🪙❗,575,575/10500 [5.48%]
4,D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,345,345/10500 [3.29%]
...,...,...,...
94,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_,1,1/10500 [0.01%]
95,D10 > D5☑5 > D5❌_ > D10 > D5❌5 > D5❌0 > D10 > D5☑5 > 🪙❓ > 🪙❗,1,1/10500 [0.01%]
96,D20 > 🪙❓ > 🪙❗,1,1/10500 [0.01%]
97,D10 > D42 > D5❌_,1,1/10500 [0.01%]
98,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0,1,1/10500 [0.01%]

======================================================================

domestic_without_D20: 98 Abläufe

,Ablauf,Traces,Anteil
0,D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,4618,4618/10366 [44.55%]
1,D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,2473,2473/10366 [23.86%]
2,D10 > D5☑5 > 🪙❓ > 🪙❗,1392,1392/10366 [13.43%]
3,D10 > D32 > D5☑5 > 🪙❓ > 🪙❗,575,575/10366 [5.55%]
4,D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,345,345/10366 [3.33%]
...,...,...,...
93,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_,1,1/10366 [0.01%]
94,D10 > D5☑5 > D5❌_ > D10 > D5❌5 > D5❌0 > D10 > D5☑5 > 🪙❓ > 🪙❗,1,1/10366 [0.01%]
95,🪙❓ > 🪙❗,1,1/10366 [0.01%]
96,D10 > D42 > D5❌_,1,1/10366 [0.01%]
97,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0,1,1/10366 [0.01%]

======================================================================

international: 753 Abläufe

,Ablauf,Traces,Anteil
0,P10 > P36 > P5☑5 > T⬆️ > T⬇️ > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,1369,1369/6449 [21.23%]
1,P10 > P36 > P31 > P5☑5 > T⬆️ > T⬇️ > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,624,624/6449 [9.68%]
2,P10 > P5☑5 > T⬆️ > T⬇️ > D10 > D5☑5 > 🪙❓ > 🪙❗,361,361/6449 [5.60%]
3,P10 > P36 > P5☑5 > T⬆️ > T⬇️ > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,311,311/6449 [4.82%]
4,P10 > P32 > P5☑5 > T⬆️ > T⬇️ > D10 > D32 > D5☑5 > 🪙❓ > 🪙❗,254,254/6449 [3.94%]
...,...,...,...
748,P10 > P36 > P35 > P5☑7 > T⬆️ > D10 > D5❌6 > T⬇️ > D5❌0 > D10 > D36 > D35 > D5☑7 > 🪙❓ > 🪙❗,1,1/6449 [0.02%]
749,T⬆️ > T⬇️ > P10 > P36 > P35 > P5☑7 > D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5☑7 > 🪙❓ > 🪙❗,1,1/6449 [0.02%]
750,P10 > P36 > P31 > P35 > P5☑7 > T⬆️ > T⬇️ > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,1,1/6449 [0.02%]
751,P10 > P36 > P5☑5 > T⬆️ > T⬇️ > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7 > 🪙❓ > 🪙❗,1,1/6449 [0.02%]
752,T⬆️ > T⬇️ > P10 > P5❌6 > P5❌0 > P10 > P5❌6 > P5❌0 > P10 > P36 > P31 > P5☑5 > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,1,1/6449 [0.02%]

======================================================================

decl_only: 154 Abläufe

,Ablauf,Traces,Anteil
0,D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,4618,4618/10948 [42.18%]
1,D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,2473,2473/10948 [22.59%]
2,D10 > D5☑5 > 🪙❓ > 🪙❗,1392,1392/10948 [12.71%]
3,D10 > D32 > D5☑5 > 🪙❓ > 🪙❗,575,575/10948 [5.25%]
4,D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,345,345/10948 [3.15%]
...,...,...,...
149,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_,1,1/10948 [0.01%]
150,D10 > D5☑5 > D5❌_ > D10 > D5❌5 > D5❌0 > D10 > D5☑5 > 🪙❓ > 🪙❗,1,1/10948 [0.01%]
151,D20 > 🪙❓ > 🪙❗,1,1/10948 [0.01%]
152,D10 > D42 > D5❌_,1,1/10948 [0.01%]
153,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0,1,1/10948 [0.01%]

======================================================================

decl_only_without_trips: 112 Abläufe

,Ablauf,Traces,Anteil
0,D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,4706,4706/10948 [42.99%]
1,D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,2563,2563/10948 [23.41%]
2,D10 > D5☑5 > 🪙❓ > 🪙❗,1503,1503/10948 [13.73%]
3,D10 > D32 > D5☑5 > 🪙❓ > 🪙❗,608,608/10948 [5.55%]
4,D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,374,374/10948 [3.42%]
...,...,...,...
107,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_,1,1/10948 [0.01%]
108,D10 > D5☑5 > D5❌_ > D10 > D5❌5 > D5❌0 > D10 > D5☑5 > 🪙❓ > 🪙❗,1,1/10948 [0.01%]
109,D20 > 🪙❓ > 🪙❗,1,1/10948 [0.01%]
110,D10 > D42 > D5❌_,1,1/10948 [0.01%]
111,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0,1,1/10948 [0.01%]

======================================================================

decl_and_permit: 698 Abläufe

,Ablauf,Traces,Anteil
0,P10 > P36 > P5☑5 > T⬆️ > T⬇️ > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,1369,1369/6001 [22.81%]
1,P10 > P36 > P31 > P5☑5 > T⬆️ > T⬇️ > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,624,624/6001 [10.40%]
2,P10 > P5☑5 > T⬆️ > T⬇️ > D10 > D5☑5 > 🪙❓ > 🪙❗,361,361/6001 [6.02%]
3,P10 > P36 > P5☑5 > T⬆️ > T⬇️ > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,311,311/6001 [5.18%]
4,P10 > P32 > P5☑5 > T⬆️ > T⬇️ > D10 > D32 > D5☑5 > 🪙❓ > 🪙❗,254,254/6001 [4.23%]
...,...,...,...
693,P10 > P36 > P35 > P5☑7 > T⬆️ > D10 > D5❌6 > T⬇️ > D5❌0 > D10 > D36 > D35 > D5☑7 > 🪙❓ > 🪙❗,1,1/6001 [0.02%]
694,T⬆️ > T⬇️ > P10 > P36 > P35 > P5☑7 > D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5☑7 > 🪙❓ > 🪙❗,1,1/6001 [0.02%]
695,P10 > P36 > P31 > P35 > P5☑7 > T⬆️ > T⬇️ > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,1,1/6001 [0.02%]
696,P10 > P36 > P5☑5 > T⬆️ > T⬇️ > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7 > 🪙❓ > 🪙❗,1,1/6001 [0.02%]
697,T⬆️ > T⬇️ > P10 > P5❌6 > P5❌0 > P10 > P5❌6 > P5❌0 > P10 > P36 > P31 > P5☑5 > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,1,1/6001 [0.02%]

======================================================================

decl_and_permit_without_trips: 339 Abläufe

,Ablauf,Traces,Anteil
0,P10 > P36 > P5☑5 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,1776,1776/6001 [29.60%]
1,P10 > P36 > P31 > P5☑5 > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,877,877/6001 [14.61%]
2,P10 > P5☑5 > D10 > D5☑5 > 🪙❓ > 🪙❗,415,415/6001 [6.92%]
3,P10 > P36 > P5☑5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,374,374/6001 [6.23%]
4,P10 > P32 > P5☑5 > D10 > D32 > D5☑5 > 🪙❓ > 🪙❗,304,304/6001 [5.07%]
...,...,...,...
334,P10 > P35 > P5☑7 > P5❌_ > P10 > P5☑5 > D10 > D5☑5 > 🪙❓ > 🪙❗,1,1/6001 [0.02%]
335,P10 > P32 > P5☑5 > D10 > D5❌2 > D5❌0 > D10 > D5☑5 > 🪙❓ > 🪙❗,1,1/6001 [0.02%]
336,P10 > P5❌5 > P5❌0 > P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P31 > P5☑5 > 📨 > 📨 > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,1,1/6001 [0.02%]
337,P10 > P36 > P31 > P35 > P5☑7 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,1,1/6001 [0.02%]
338,P10 > P5❌6 > P5❌0 > P10 > P5❌6 > P5❌0 > P10 > P36 > P31 > P5☑5 > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,1,1/6001 [0.02%]

======================================================================

decl_and_permit_without_trips_or_D20: 338 Abläufe

,Ablauf,Traces,Anteil
0,P10 > P36 > P5☑5 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,1776,1776/6001 [29.60%]
1,P10 > P36 > P31 > P5☑5 > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,877,877/6001 [14.61%]
2,P10 > P5☑5 > D10 > D5☑5 > 🪙❓ > 🪙❗,415,415/6001 [6.92%]
3,P10 > P36 > P5☑5 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,374,374/6001 [6.23%]
4,P10 > P32 > P5☑5 > D10 > D32 > D5☑5 > 🪙❓ > 🪙❗,304,304/6001 [5.07%]
...,...,...,...
333,P10 > P35 > P5☑7 > P5❌_ > P10 > P5☑5 > D10 > D5☑5 > 🪙❓ > 🪙❗,1,1/6001 [0.02%]
334,P10 > P32 > P5☑5 > D10 > D5❌2 > D5❌0 > D10 > D5☑5 > 🪙❓ > 🪙❗,1,1/6001 [0.02%]
335,P10 > P5❌5 > P5❌0 > P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P5❌1 > P5❌0 > P10 > P36 > P31 > P5☑5 > 📨 > 📨 > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,1,1/6001 [0.02%]
336,P10 > P36 > P31 > P35 > P5☑7 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,1,1/6001 [0.02%]
337,P10 > P5❌6 > P5❌0 > P10 > P5❌6 > P5❌0 > P10 > P36 > P31 > P5☑5 > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,1,1/6001 [0.02%]

======================================================================

international_only_decl: 55 Abläufe

,Ablauf,Traces,Anteil
0,D10 > D5☑5 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,111,111/448 [24.78%]
1,D10 > D36 > D5☑5 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,79,79/448 [17.63%]
2,D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,75,75/448 [16.74%]
3,D10 > D32 > D5☑5 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,33,33/448 [7.37%]
4,D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,21,21/448 [4.69%]
5,D10 > D35 > D5☑7 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,14,14/448 [3.12%]
6,T⬆️ > T⬇️ > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,12,12/448 [2.68%]
7,D10 > D36 > D35 > D5☑7 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,11,11/448 [2.46%]
8,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,9,9/448 [2.01%]
9,D20 > T⬆️ > T⬇️,8,8/448 [1.79%]
10,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,6,6/448 [1.34%]
11,D10 > D5❌6 > D5❌0 > T⬆️ > T⬇️,6,6/448 [1.34%]
12,T⬆️ > T⬇️ > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,6,6/448 [1.34%]
13,T⬆️ > T⬇️ > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,4,4/448 [0.89%]
14,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5☑5 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,3,3/448 [0.67%]
15,T⬆️ > T⬇️ > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,3,3/448 [0.67%]
16,D10 > D5❌5 > D5❌0 > D10 > D5☑5 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,2,2/448 [0.45%]
17,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,2,2/448 [0.45%]
18,D10 > D5❌6 > T⬆️ > T⬇️ > D5❌0,2,2/448 [0.45%]
19,D10 > D36 > D5☑5 > T⬆️ > T⬇️ > 🪙❗ > 🪙❓,2,2/448 [0.45%]
20,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,2,2/448 [0.45%]
21,T⬆️ > T⬇️ > D10 > D5❌6 > D5❌0,2,2/448 [0.45%]
22,T⬆️ > T⬇️ > D20,2,2/448 [0.45%]
23,D10 > D36 > D31 > D5☑5 > T⬆️ > 🪙❓ > 🪙❗ > T⬇️,2,2/448 [0.45%]
24,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0 > D10 > D32 > D5☑5 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,1,1/448 [0.22%]
25,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_ > D10 > D5☑5 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,1,1/448 [0.22%]
26,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,1,1/448 [0.22%]
27,D10 > D5☑5 > D5❌_ > T⬆️ > T⬇️,1,1/448 [0.22%]
28,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,1,1/448 [0.22%]
29,D10 > D35 > D5☑7 > D5❌_ > D10 > D35 > D5☑7 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,1,1/448 [0.22%]
30,D10 > D32 > D35 > D5☑7 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,1,1/448 [0.22%]
31,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,1,1/448 [0.22%]
32,D10 > D5❌6 > D5❌0 > T⬆️ > D10 > D36 > D5☑5 > T⬇️ > 🪙❓ > 🪙❗,1,1/448 [0.22%]
33,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,1,1/448 [0.22%]
34,D10 > D36 > D31 > D5❌5 > D5❌0 > T⬆️ > T⬇️,1,1/448 [0.22%]
35,D10 > D36 > D5☑5 > T⬆️ > 🪙❓ > 🪙❗ > T⬇️,1,1/448 [0.22%]
36,T⬆️ > T⬇️ > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D35 > D5☑7 > 🪙❓ > 🪙❗,1,1/448 [0.22%]
37,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,1,1/448 [0.22%]
38,D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5☑7 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,1,1/448 [0.22%]
39,D10 > D36 > D31 > D35 > D5☑7 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,1,1/448 [0.22%]
40,D10 > D36 > D5☑5 > T⬆️ > T⬇️ > 🪙❓ > 🪙❗,1,1/448 [0.22%]
41,D10 > D5❌6 > D5❌0 > T⬆️ > D10 > D36 > D31 > T⬇️ > D5☑5 > 🪙❓ > 🪙❗,1,1/448 [0.22%]
42,D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > T⬆️ > 🪙❗ > T⬇️,1,1/448 [0.22%]
43,D10 > D5❌6 > T⬆️ > T⬇️ > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,1,1/448 [0.22%]
44,T⬆️ > T⬇️ > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,1,1/448 [0.22%]
45,D10 > T⬆️ > D5❌6 > D5❌0 > T⬇️ > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,1,1/448 [0.22%]
46,D10 > D5❌6 > D5❌0 > T⬆️ > T⬇️ > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,1,1/448 [0.22%]
47,D10 > D36 > T⬆️ > D31 > T⬇️ > D5☑5 > 🪙❓ > 🪙❗,1,1/448 [0.22%]
48,D10 > D5❌6 > T⬆️ > D5❌0 > D10 > D36 > T⬇️ > D31 > D5☑5 > 🪙❓ > 🪙❗,1,1/448 [0.22%]
49,T⬆️ > D10 > D5❌6 > D5❌0 > T⬇️ > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,1,1/448 [0.22%]
50,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,1,1/448 [0.22%]
51,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7 > 🪙❓ > 🪙❗ > T⬆️ > T⬇️,1,1/448 [0.22%]
52,D10 > D36 > D5☑5 > 🪙❓ > T⬆️ > 🪙❗ > T⬇️,1,1/448 [0.22%]
53,D10 > T⬆️ > T⬇️ > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7 > 🪙❓ > 🪙❗,1,1/448 [0.22%]
54,T⬆️ > T⬇️ > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,1,1/448 [0.22%]

======================================================================

international_only_decl_without_trips: 33 Abläufe

,Ablauf,Traces,Anteil
0,D10 > D5☑5 > 🪙❓ > 🪙❗,111,111/448 [24.78%]
1,D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,90,90/448 [20.09%]
2,D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,88,88/448 [19.64%]
3,D10 > D32 > D5☑5 > 🪙❓ > 🪙❗,33,33/448 [7.37%]
4,D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,29,29/448 [6.47%]
5,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,16,16/448 [3.57%]
6,D10 > D35 > D5☑7 > 🪙❓ > 🪙❗,14,14/448 [3.12%]
7,D10 > D36 > D35 > D5☑7 > 🪙❓ > 🪙❗,11,11/448 [2.46%]
8,D20,10,10/448 [2.23%]
9,D10 > D5❌6 > D5❌0,10,10/448 [2.23%]
10,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > 🪙❓ > 🪙❗,6,6/448 [1.34%]
11,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5☑5 > 🪙❓ > 🪙❗,3,3/448 [0.67%]
12,D10 > D5❌5 > D5❌0 > D10 > D5☑5 > 🪙❓ > 🪙❗,2,2/448 [0.45%]
13,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,2,2/448 [0.45%]
14,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,2,2/448 [0.45%]
15,D10 > D36 > D5☑5 > 🪙❗ > 🪙❓,2,2/448 [0.45%]
16,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,2,2/448 [0.45%]
17,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7 > 🪙❓ > 🪙❗,2,2/448 [0.45%]
18,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0 > D10 > D32 > D5☑5 > 🪙❓ > 🪙❗,1,1/448 [0.22%]
19,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_ > D10 > D5☑5 > 🪙❓ > 🪙❗,1,1/448 [0.22%]
20,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5 > 🪙❓ > 🪙❗,1,1/448 [0.22%]
21,D10 > D5☑5 > D5❌_,1,1/448 [0.22%]
22,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5 > 🪙❓ > 🪙❗,1,1/448 [0.22%]
23,D10 > D35 > D5☑7 > D5❌_ > D10 > D35 > D5☑7 > 🪙❓ > 🪙❗,1,1/448 [0.22%]
24,D10 > D32 > D35 > D5☑7 > 🪙❓ > 🪙❗,1,1/448 [0.22%]
25,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > 🪙❓ > 🪙❗,1,1/448 [0.22%]
26,D10 > D36 > D31 > D5❌5 > D5❌0,1,1/448 [0.22%]
27,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D35 > D5☑7 > 🪙❓ > 🪙❗,1,1/448 [0.22%]
28,D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5☑7 > 🪙❓ > 🪙❗,1,1/448 [0.22%]
29,D10 > D36 > D31 > D35 > D5☑7 > 🪙❓ > 🪙❗,1,1/448 [0.22%]
30,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,1,1/448 [0.22%]
31,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7 > 🪙❓ > 🪙❗,1,1/448 [0.22%]
32,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7 > 🪙❓ > 🪙❗,1,1/448 [0.22%]

======================================================================

international_only_decl_without_trips_or_D20: 32 Abläufe

,Ablauf,Traces,Anteil
0,D10 > D5☑5 > 🪙❓ > 🪙❗,111,111/438 [25.34%]
1,D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,90,90/438 [20.55%]
2,D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,88,88/438 [20.09%]
3,D10 > D32 > D5☑5 > 🪙❓ > 🪙❗,33,33/438 [7.53%]
4,D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,29,29/438 [6.62%]
5,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,16,16/438 [3.65%]
6,D10 > D35 > D5☑7 > 🪙❓ > 🪙❗,14,14/438 [3.20%]
7,D10 > D36 > D35 > D5☑7 > 🪙❓ > 🪙❗,11,11/438 [2.51%]
8,D10 > D5❌6 > D5❌0,10,10/438 [2.28%]
9,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > 🪙❓ > 🪙❗,6,6/438 [1.37%]
10,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5☑5 > 🪙❓ > 🪙❗,3,3/438 [0.68%]
11,D10 > D5❌5 > D5❌0 > D10 > D5☑5 > 🪙❓ > 🪙❗,2,2/438 [0.46%]
12,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,2,2/438 [0.46%]
13,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,2,2/438 [0.46%]
14,D10 > D36 > D5☑5 > 🪙❗ > 🪙❓,2,2/438 [0.46%]
15,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5 > 🪙❓ > 🪙❗,2,2/438 [0.46%]
16,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7 > 🪙❓ > 🪙❗,2,2/438 [0.46%]
17,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0 > D10 > D32 > D5☑5 > 🪙❓ > 🪙❗,1,1/438 [0.23%]
18,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_ > D10 > D5☑5 > 🪙❓ > 🪙❗,1,1/438 [0.23%]
19,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5 > 🪙❓ > 🪙❗,1,1/438 [0.23%]
20,D10 > D5☑5 > D5❌_,1,1/438 [0.23%]
21,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5 > 🪙❓ > 🪙❗,1,1/438 [0.23%]
22,D10 > D35 > D5☑7 > D5❌_ > D10 > D35 > D5☑7 > 🪙❓ > 🪙❗,1,1/438 [0.23%]
23,D10 > D32 > D35 > D5☑7 > 🪙❓ > 🪙❗,1,1/438 [0.23%]
24,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > 🪙❓ > 🪙❗,1,1/438 [0.23%]
25,D10 > D36 > D31 > D5❌5 > D5❌0,1,1/438 [0.23%]
26,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D35 > D5☑7 > 🪙❓ > 🪙❗,1,1/438 [0.23%]
27,D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5☑7 > 🪙❓ > 🪙❗,1,1/438 [0.23%]
28,D10 > D36 > D31 > D35 > D5☑7 > 🪙❓ > 🪙❗,1,1/438 [0.23%]
29,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5 > 🪙❓ > 🪙❗,1,1/438 [0.23%]
30,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7 > 🪙❓ > 🪙❗,1,1/438 [0.23%]
31,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7 > 🪙❓ > 🪙❗,1,1/438 [0.23%]

In [12]:
start_end(logs)

In [13]:
MINERS = {
    "inductivepn": pm4py.discover_petri_net_inductive,
    "alphapn": pm4py.discover_petri_net_alpha,
    "alphapluspn": pm4py.discover_petri_net_alpha_plus,
    "heuristicpn": pm4py.discover_petri_net_heuristics,
    "inductivebpmn": pm4py.discover_bpmn_inductive,
    "inductive_noise10pn": discover_inductive_noise_tenth,
    "inductive_noise20pn": discover_inductive_noise_twentieth,
    "ilppn": discover_ilp,
    "powl": discover_powl,
}

models, stats = {}, {}
for name, log in logs.items():
    for miner, discover in MINERS.items():
        models[(name, miner)], stats[(name, miner)] = discover_and_evaluate(name, miner, discover, log)

table = pd.DataFrame(stats)
table.columns.names = ["Log", "Verfahren"]
display(style_stats(compare(table)))
display(style_stats(table))

domestic_inductivepn_model.pkl: aus Cache geladen
domestic_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_alphapn_model.pkl: aus Cache geladen
domestic_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_alphapluspn_model.pkl: aus Cache geladen
domestic_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_heuristicpn_model.pkl: aus Cache geladen
domestic_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_inductivebpmn_model.pkl: aus Cache geladen
domestic_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_inductive_noise10pn_model.pkl: aus Cache geladen
domestic_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_inductive_noise20pn_model.pkl: aus Cache geladen
domestic_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_ilppn_model.pkl: aus Cache geladen
domestic_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_powl_model.pkl: aus Cache geladen
domestic_powl_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_without_D20_inductivepn_model.pkl: aus Cache geladen
domestic_without_D20_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_without_D20_alphapn_model.pkl: aus Cache geladen
domestic_without_D20_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_without_D20_alphapluspn_model.pkl: aus Cache geladen
domestic_without_D20_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_without_D20_heuristicpn_model.pkl: aus Cache geladen
domestic_without_D20_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_without_D20_inductivebpmn_model.pkl: aus Cache geladen
domestic_without_D20_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_without_D20_inductive_noise10pn_model.pkl: aus Cache geladen
domestic_without_D20_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_without_D20_inductive_noise20pn_model.pkl: aus Cache geladen
domestic_without_D20_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_without_D20_ilppn_model.pkl: aus Cache geladen
domestic_without_D20_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
domestic_without_D20_powl_model.pkl: aus Cache geladen
domestic_without_D20_powl_stats.pkl: 19 aus Cache, neu berechnet: –
international_inductivepn_model.pkl: aus Cache geladen
international_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
international_alphapn_model.pkl: aus Cache geladen
international_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
international_alphapluspn_model.pkl: aus Cache geladen
international_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
international_heuristicpn_model.pkl: aus Cache geladen
international_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
international_inductivebpmn_model.pkl: aus Cache geladen
international_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
international_inductive_noise10pn_model.pkl: aus Cache geladen
international_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
international_inductive_noise20pn_model.pkl: aus Cache geladen
international_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
international_ilppn_model.pkl: aus Cache geladen
international_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
international_powl_model.pkl: aus Cache geladen
international_powl_stats.pkl: 19 aus Cache, neu berechnet: –
decl_only_inductivepn_model.pkl: aus Cache geladen
decl_only_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_only_alphapn_model.pkl: aus Cache geladen
decl_only_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_only_alphapluspn_model.pkl: aus Cache geladen
decl_only_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_only_heuristicpn_model.pkl: aus Cache geladen
decl_only_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_only_inductivebpmn_model.pkl: aus Cache geladen
decl_only_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_only_inductive_noise10pn_model.pkl: aus Cache geladen
decl_only_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_only_inductive_noise20pn_model.pkl: aus Cache geladen
decl_only_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_only_ilppn_model.pkl: aus Cache geladen
decl_only_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_only_powl_model.pkl: aus Cache geladen
decl_only_powl_stats.pkl: 19 aus Cache, neu berechnet: –
decl_only_without_trips_inductivepn_model.pkl: aus Cache geladen
decl_only_without_trips_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_only_without_trips_alphapn_model.pkl: aus Cache geladen
decl_only_without_trips_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_only_without_trips_alphapluspn_model.pkl: aus Cache geladen
decl_only_without_trips_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_only_without_trips_heuristicpn_model.pkl: aus Cache geladen
decl_only_without_trips_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_only_without_trips_inductivebpmn_model.pkl: aus Cache geladen
decl_only_without_trips_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_only_without_trips_inductive_noise10pn_model.pkl: aus Cache geladen
decl_only_without_trips_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_only_without_trips_inductive_noise20pn_model.pkl: aus Cache geladen
decl_only_without_trips_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_only_without_trips_ilppn_model.pkl: aus Cache geladen
decl_only_without_trips_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_only_without_trips_powl_model.pkl: aus Cache geladen
decl_only_without_trips_powl_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_inductivepn_model.pkl: aus Cache geladen
decl_and_permit_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_alphapn_model.pkl: aus Cache geladen
decl_and_permit_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_alphapluspn_model.pkl: aus Cache geladen
decl_and_permit_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_heuristicpn_model.pkl: aus Cache geladen
decl_and_permit_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_inductivebpmn_model.pkl: aus Cache geladen
decl_and_permit_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_inductive_noise10pn_model.pkl: aus Cache geladen
decl_and_permit_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_inductive_noise20pn_model.pkl: aus Cache geladen
decl_and_permit_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_ilppn_model.pkl: aus Cache geladen
decl_and_permit_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_powl_model.pkl: aus Cache geladen
decl_and_permit_powl_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_without_trips_inductivepn_model.pkl: aus Cache geladen
decl_and_permit_without_trips_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_without_trips_alphapn_model.pkl: aus Cache geladen
decl_and_permit_without_trips_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_without_trips_alphapluspn_model.pkl: aus Cache geladen
decl_and_permit_without_trips_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_without_trips_heuristicpn_model.pkl: aus Cache geladen
decl_and_permit_without_trips_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_without_trips_inductivebpmn_model.pkl: aus Cache geladen
decl_and_permit_without_trips_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_without_trips_inductive_noise10pn_model.pkl: aus Cache geladen
decl_and_permit_without_trips_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_without_trips_inductive_noise20pn_model.pkl: aus Cache geladen
decl_and_permit_without_trips_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_without_trips_ilppn_model.pkl: aus Cache geladen
decl_and_permit_without_trips_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_without_trips_powl_model.pkl: aus Cache geladen
decl_and_permit_without_trips_powl_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_without_trips_or_D20_inductivepn_model.pkl: aus Cache geladen
decl_and_permit_without_trips_or_D20_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_without_trips_or_D20_alphapn_model.pkl: aus Cache geladen
decl_and_permit_without_trips_or_D20_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_without_trips_or_D20_alphapluspn_model.pkl: aus Cache geladen
decl_and_permit_without_trips_or_D20_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_without_trips_or_D20_heuristicpn_model.pkl: aus Cache geladen
decl_and_permit_without_trips_or_D20_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_without_trips_or_D20_inductivebpmn_model.pkl: aus Cache geladen
decl_and_permit_without_trips_or_D20_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_without_trips_or_D20_inductive_noise10pn_model.pkl: aus Cache geladen
decl_and_permit_without_trips_or_D20_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_without_trips_or_D20_inductive_noise20pn_model.pkl: aus Cache geladen
decl_and_permit_without_trips_or_D20_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_without_trips_or_D20_ilppn_model.pkl: aus Cache geladen
decl_and_permit_without_trips_or_D20_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
decl_and_permit_without_trips_or_D20_powl_model.pkl: aus Cache geladen
decl_and_permit_without_trips_or_D20_powl_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_inductivepn_model.pkl: aus Cache geladen
international_only_decl_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_alphapn_model.pkl: aus Cache geladen
international_only_decl_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_alphapluspn_model.pkl: aus Cache geladen
international_only_decl_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_heuristicpn_model.pkl: aus Cache geladen
international_only_decl_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_inductivebpmn_model.pkl: aus Cache geladen
international_only_decl_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_inductive_noise10pn_model.pkl: aus Cache geladen
international_only_decl_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_inductive_noise20pn_model.pkl: aus Cache geladen
international_only_decl_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_ilppn_model.pkl: aus Cache geladen
international_only_decl_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_powl_model.pkl: aus Cache geladen
international_only_decl_powl_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_without_trips_inductivepn_model.pkl: aus Cache geladen
international_only_decl_without_trips_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_without_trips_alphapn_model.pkl: aus Cache geladen
international_only_decl_without_trips_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_without_trips_alphapluspn_model.pkl: aus Cache geladen
international_only_decl_without_trips_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_without_trips_heuristicpn_model.pkl: aus Cache geladen
international_only_decl_without_trips_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_without_trips_inductivebpmn_model.pkl: aus Cache geladen
international_only_decl_without_trips_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_without_trips_inductive_noise10pn_model.pkl: aus Cache geladen
international_only_decl_without_trips_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_without_trips_inductive_noise20pn_model.pkl: aus Cache geladen
international_only_decl_without_trips_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_without_trips_ilppn_model.pkl: aus Cache geladen
international_only_decl_without_trips_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_without_trips_powl_model.pkl: aus Cache geladen
international_only_decl_without_trips_powl_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_without_trips_or_D20_inductivepn_model.pkl: aus Cache geladen
international_only_decl_without_trips_or_D20_inductivepn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_without_trips_or_D20_alphapn_model.pkl: aus Cache geladen
international_only_decl_without_trips_or_D20_alphapn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_without_trips_or_D20_alphapluspn_model.pkl: aus Cache geladen
international_only_decl_without_trips_or_D20_alphapluspn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_without_trips_or_D20_heuristicpn_model.pkl: aus Cache geladen
international_only_decl_without_trips_or_D20_heuristicpn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_without_trips_or_D20_inductivebpmn_model.pkl: aus Cache geladen
international_only_decl_without_trips_or_D20_inductivebpmn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_without_trips_or_D20_inductive_noise10pn_model.pkl: aus Cache geladen
international_only_decl_without_trips_or_D20_inductive_noise10pn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_without_trips_or_D20_inductive_noise20pn_model.pkl: aus Cache geladen
international_only_decl_without_trips_or_D20_inductive_noise20pn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_without_trips_or_D20_ilppn_model.pkl: aus Cache geladen
international_only_decl_without_trips_or_D20_ilppn_stats.pkl: 19 aus Cache, neu berechnet: –
international_only_decl_without_trips_or_D20_powl_model.pkl: aus Cache geladen
international_only_decl_without_trips_or_D20_powl_stats.pkl: 19 aus Cache, neu berechnet: –

In [14]:
# Log-Gruppen, die jeweils zusammen alle Traces abdecken: raw vs. vorverarbeitet vs. ohne Trips vs. drei Prozesse getrennt
PARTITIONS = {
    "raw": ["domestic", "international"],
    "vorverarbeitet": ["decl_only", "decl_and_permit"],
    "ohne Trips": ["decl_only_without_trips", "decl_and_permit_without_trips"],
    "getrennt ohne Trips": ["domestic", "decl_and_permit_without_trips", "international_only_decl_without_trips"],
    "getrennt ohne Trips, ohne SAVE": ["domestic_without_D20", "decl_and_permit_without_trips_or_D20", "international_only_decl_without_trips_or_D20"],
}
combined = combine_partitions(table, logs, PARTITIONS)
display(style_stats(combined[["heuristicpn"]]))
display(style_stats(combined))

### Trace-Varianten je Log: nur Declaration

Alle anderen Events werden vor der Variantenbildung entfernt. Die Ablaeufe verwenden die Kurzcodes aus der Legende oben; die Anteile beziehen sich auf Traces mit Declaration-Events.

In [15]:
declaration_variants = {}
with pd.option_context("display.max_rows", None, "display.max_colwidth", None):
    for name, log in logs.items():
        declaration_events = log[log["concept:name"].str.contains(r"\bDeclaration\b", na=False)]
        declaration_variants[name] = variants(declaration_events)
        print("=" * 70)
        print(f"\n{name}: {len(declaration_variants[name])} Declaration-Ablaeufe")
        display(declaration_variants[name])

======================================================================

domestic: 94 Declaration-Ablaeufe

,Ablauf,Traces,Anteil
0,D10 > D36 > D5☑5,4622,4622/10500 [44.02%]
1,D10 > D36 > D31 > D5☑5,2475,2475/10500 [23.57%]
2,D10 > D5☑5,1392,1392/10500 [13.26%]
3,D10 > D32 > D5☑5,575,575/10500 [5.48%]
4,D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,345,345/10500 [3.29%]
5,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,188,188/10500 [1.79%]
6,D10 > D5❌6 > D5❌0,174,174/10500 [1.66%]
7,D20,135,135/10500 [1.29%]
8,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,77,77/10500 [0.73%]
9,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,57,57/10500 [0.54%]
10,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,49,49/10500 [0.47%]
11,D10 > D5☑5 > D5❌_ > D10 > D5☑5,40,40/10500 [0.38%]
12,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,36,36/10500 [0.34%]
13,D10 > D36 > D5❌5 > D5❌0,31,31/10500 [0.30%]
14,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,29,29/10500 [0.28%]
15,D10 > D5☑5 > D5❌_,24,24/10500 [0.23%]
16,D10 > D5❌5 > D5❌0 > D10 > D5☑5,22,22/10500 [0.21%]
17,D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,20,20/10500 [0.19%]
18,D10 > D5❌5 > D5❌0,19,19/10500 [0.18%]
19,D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5☑5,14,14/10500 [0.13%]
20,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0,11,11/10500 [0.10%]
21,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,10,10/10500 [0.10%]
22,D10 > D36 > D5❌1 > D5❌0,8,8/10500 [0.08%]
23,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,8,8/10500 [0.08%]
24,D10 > D5❌2 > D5❌0,8,8/10500 [0.08%]
25,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,7,7/10500 [0.07%]
26,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,6,6/10500 [0.06%]
27,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,6,6/10500 [0.06%]
28,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0,6,6/10500 [0.06%]
29,D10 > D5❌6,5,5/10500 [0.05%]
30,D10 > D5❌2 > D5❌0 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,5,5/10500 [0.05%]
31,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0,4,4/10500 [0.04%]
32,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,4,4/10500 [0.04%]
33,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,4,4/10500 [0.04%]
34,D10 > D5❌2 > D5❌0 > D10 > D5☑5,4,4/10500 [0.04%]
35,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,3,3/10500 [0.03%]
36,D10 > D5❌6 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,3,3/10500 [0.03%]
37,D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0,3,3/10500 [0.03%]
38,D10 > D36 > D31 > D5❌5 > D5❌0,3,3/10500 [0.03%]
39,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0,3,3/10500 [0.03%]
40,D10 > D32 > D5❌5 > D5❌0,3,3/10500 [0.03%]
41,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,2,2/10500 [0.02%]
42,D10 > D5❌2 > D5❌0 > D10 > D36 > D5☑5,2,2/10500 [0.02%]
43,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D5☑5,2,2/10500 [0.02%]
44,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,2,2/10500 [0.02%]
45,D10 > D5❌6 > D10 > D5❌6 > D5❌0,2,2/10500 [0.02%]
46,D10 > D36 > D5❌5,2,2/10500 [0.02%]
47,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,2,2/10500 [0.02%]
48,D10 > D32 > D5☑5 > D5❌_,2,2/10500 [0.02%]
49,D10 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,2,2/10500 [0.02%]
50,D10 > D32 > D5☑5 > D5❌_ > D10 > D36 > D31 > D5☑5,1,1/10500 [0.01%]
51,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5☑5,1,1/10500 [0.01%]
52,D10 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,1,1/10500 [0.01%]
53,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,1,1/10500 [0.01%]
54,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D5❌0,1,1/10500 [0.01%]
55,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10500 [0.01%]
56,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D10 > D46 > D10 > D36 > D31 > D5☑5,1,1/10500 [0.01%]
57,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0,1,1/10500 [0.01%]
58,D10 > D5☑5 > D5❌_ > D10 > D36 > D5☑5,1,1/10500 [0.01%]
59,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10500 [0.01%]
60,D10 > D5☑5 > D5❌_ > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/10500 [0.01%]
61,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0,1,1/10500 [0.01%]
62,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,1,1/10500 [0.01%]
63,D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/10500 [0.01%]
64,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/10500 [0.01%]
65,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10500 [0.01%]
66,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌0,1,1/10500 [0.01%]
67,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10500 [0.01%]
68,D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/10500 [0.01%]
69,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5☑5,1,1/10500 [0.01%]
70,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10500 [0.01%]
71,D10 > D5❌6 > D10 > D36 > D5❌5 > D5❌0,1,1/10500 [0.01%]
72,D10 > D36 > D5❌5 > D10 > D36 > D5☑5,1,1/10500 [0.01%]
73,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0,1,1/10500 [0.01%]
74,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D36 > D5☑5,1,1/10500 [0.01%]
75,D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/10500 [0.01%]
76,D10 > D36 > D31 > D5❌5,1,1/10500 [0.01%]
77,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10500 [0.01%]
78,D10 > D36 > D5❌5 > D10 > D5❌0 > D10 > D36 > D5☑5,1,1/10500 [0.01%]
79,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10500 [0.01%]
80,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10500 [0.01%]
81,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5,1,1/10500 [0.01%]
82,D10 > D5☑5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,1,1/10500 [0.01%]
83,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_,1,1/10500 [0.01%]
84,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0 > D10 > D5☑5,1,1/10500 [0.01%]
85,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,1,1/10500 [0.01%]
86,D10 > D5❌2 > D10 > D5❌0 > D10 > D32 > D5☑5,1,1/10500 [0.01%]
87,D10 > D5❌5 > D5❌0 > D10 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/10500 [0.01%]
88,D10 > D45 > D5❌_,1,1/10500 [0.01%]
89,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/10500 [0.01%]
90,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_,1,1/10500 [0.01%]
91,D10 > D5☑5 > D5❌_ > D10 > D5❌5 > D5❌0 > D10 > D5☑5,1,1/10500 [0.01%]
92,D10 > D42 > D5❌_,1,1/10500 [0.01%]
93,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0,1,1/10500 [0.01%]

======================================================================

domestic_without_D20: 93 Declaration-Ablaeufe

,Ablauf,Traces,Anteil
0,D10 > D36 > D5☑5,4622,4622/10365 [44.59%]
1,D10 > D36 > D31 > D5☑5,2475,2475/10365 [23.88%]
2,D10 > D5☑5,1392,1392/10365 [13.43%]
3,D10 > D32 > D5☑5,575,575/10365 [5.55%]
4,D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,345,345/10365 [3.33%]
5,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,188,188/10365 [1.81%]
6,D10 > D5❌6 > D5❌0,174,174/10365 [1.68%]
7,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,77,77/10365 [0.74%]
8,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,57,57/10365 [0.55%]
9,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,49,49/10365 [0.47%]
10,D10 > D5☑5 > D5❌_ > D10 > D5☑5,40,40/10365 [0.39%]
11,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,36,36/10365 [0.35%]
12,D10 > D36 > D5❌5 > D5❌0,31,31/10365 [0.30%]
13,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,29,29/10365 [0.28%]
14,D10 > D5☑5 > D5❌_,24,24/10365 [0.23%]
15,D10 > D5❌5 > D5❌0 > D10 > D5☑5,22,22/10365 [0.21%]
16,D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,20,20/10365 [0.19%]
17,D10 > D5❌5 > D5❌0,19,19/10365 [0.18%]
18,D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5☑5,14,14/10365 [0.14%]
19,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0,11,11/10365 [0.11%]
20,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,10,10/10365 [0.10%]
21,D10 > D36 > D5❌1 > D5❌0,8,8/10365 [0.08%]
22,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,8,8/10365 [0.08%]
23,D10 > D5❌2 > D5❌0,8,8/10365 [0.08%]
24,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,7,7/10365 [0.07%]
25,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,6,6/10365 [0.06%]
26,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,6,6/10365 [0.06%]
27,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0,6,6/10365 [0.06%]
28,D10 > D5❌6,5,5/10365 [0.05%]
29,D10 > D5❌2 > D5❌0 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,5,5/10365 [0.05%]
30,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0,4,4/10365 [0.04%]
31,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,4,4/10365 [0.04%]
32,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,4,4/10365 [0.04%]
33,D10 > D5❌2 > D5❌0 > D10 > D5☑5,4,4/10365 [0.04%]
34,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,3,3/10365 [0.03%]
35,D10 > D5❌6 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,3,3/10365 [0.03%]
36,D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0,3,3/10365 [0.03%]
37,D10 > D36 > D31 > D5❌5 > D5❌0,3,3/10365 [0.03%]
38,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0,3,3/10365 [0.03%]
39,D10 > D32 > D5❌5 > D5❌0,3,3/10365 [0.03%]
40,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,2,2/10365 [0.02%]
41,D10 > D5❌2 > D5❌0 > D10 > D36 > D5☑5,2,2/10365 [0.02%]
42,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D5☑5,2,2/10365 [0.02%]
43,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,2,2/10365 [0.02%]
44,D10 > D5❌6 > D10 > D5❌6 > D5❌0,2,2/10365 [0.02%]
45,D10 > D36 > D5❌5,2,2/10365 [0.02%]
46,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,2,2/10365 [0.02%]
47,D10 > D32 > D5☑5 > D5❌_,2,2/10365 [0.02%]
48,D10 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,2,2/10365 [0.02%]
49,D10 > D32 > D5☑5 > D5❌_ > D10 > D36 > D31 > D5☑5,1,1/10365 [0.01%]
50,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5☑5,1,1/10365 [0.01%]
51,D10 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,1,1/10365 [0.01%]
52,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,1,1/10365 [0.01%]
53,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D5❌0,1,1/10365 [0.01%]
54,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10365 [0.01%]
55,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D10 > D46 > D10 > D36 > D31 > D5☑5,1,1/10365 [0.01%]
56,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0,1,1/10365 [0.01%]
57,D10 > D5☑5 > D5❌_ > D10 > D36 > D5☑5,1,1/10365 [0.01%]
58,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10365 [0.01%]
59,D10 > D5☑5 > D5❌_ > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/10365 [0.01%]
60,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0,1,1/10365 [0.01%]
61,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,1,1/10365 [0.01%]
62,D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/10365 [0.01%]
63,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/10365 [0.01%]
64,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10365 [0.01%]
65,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌0,1,1/10365 [0.01%]
66,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10365 [0.01%]
67,D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/10365 [0.01%]
68,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5☑5,1,1/10365 [0.01%]
69,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10365 [0.01%]
70,D10 > D5❌6 > D10 > D36 > D5❌5 > D5❌0,1,1/10365 [0.01%]
71,D10 > D36 > D5❌5 > D10 > D36 > D5☑5,1,1/10365 [0.01%]
72,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0,1,1/10365 [0.01%]
73,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D36 > D5☑5,1,1/10365 [0.01%]
74,D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/10365 [0.01%]
75,D10 > D36 > D31 > D5❌5,1,1/10365 [0.01%]
76,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10365 [0.01%]
77,D10 > D36 > D5❌5 > D10 > D5❌0 > D10 > D36 > D5☑5,1,1/10365 [0.01%]
78,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10365 [0.01%]
79,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10365 [0.01%]
80,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5,1,1/10365 [0.01%]
81,D10 > D5☑5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,1,1/10365 [0.01%]
82,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_,1,1/10365 [0.01%]
83,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0 > D10 > D5☑5,1,1/10365 [0.01%]
84,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,1,1/10365 [0.01%]
85,D10 > D5❌2 > D10 > D5❌0 > D10 > D32 > D5☑5,1,1/10365 [0.01%]
86,D10 > D5❌5 > D5❌0 > D10 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/10365 [0.01%]
87,D10 > D45 > D5❌_,1,1/10365 [0.01%]
88,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/10365 [0.01%]
89,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_,1,1/10365 [0.01%]
90,D10 > D5☑5 > D5❌_ > D10 > D5❌5 > D5❌0 > D10 > D5☑5,1,1/10365 [0.01%]
91,D10 > D42 > D5❌_,1,1/10365 [0.01%]
92,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0,1,1/10365 [0.01%]

======================================================================

international: 111 Declaration-Ablaeufe

,Ablauf,Traces,Anteil
0,D10 > D36 > D5☑5,2315,2315/6449 [35.90%]
1,D10 > D36 > D31 > D5☑5,1269,1269/6449 [19.68%]
2,D10 > D5☑5,621,621/6449 [9.63%]
3,D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,514,514/6449 [7.97%]
4,D10 > D32 > D5☑5,427,427/6449 [6.62%]
5,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,343,343/6449 [5.32%]
6,D10 > D5❌6 > D5❌0,126,126/6449 [1.95%]
7,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,79,79/6449 [1.22%]
8,D20,74,74/6449 [1.15%]
9,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,74,74/6449 [1.15%]
10,D10 > D35 > D5☑7,73,73/6449 [1.13%]
11,D10 > D36 > D35 > D5☑7,65,65/6449 [1.01%]
12,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,56,56/6449 [0.87%]
13,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,39,39/6449 [0.60%]
14,D10 > D5☑5 > D5❌_ > D10 > D5☑5,31,31/6449 [0.48%]
15,D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5☑7,27,27/6449 [0.42%]
16,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,25,25/6449 [0.39%]
17,D10 > D36 > D31 > D35 > D5☑7,23,23/6449 [0.36%]
18,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,18,18/6449 [0.28%]
19,D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,14,14/6449 [0.22%]
20,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,12,12/6449 [0.19%]
21,D10 > D32 > D5☑5 > D5❌_,12,12/6449 [0.19%]
22,D10 > D5❌2 > D5❌0,10,10/6449 [0.16%]
23,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,9,9/6449 [0.14%]
24,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,9,9/6449 [0.14%]
25,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,9,9/6449 [0.14%]
26,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,9,9/6449 [0.14%]
27,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,7,7/6449 [0.11%]
28,D10 > D5❌5 > D5❌0 > D10 > D5☑5,7,7/6449 [0.11%]
29,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5☑7,6,6/6449 [0.09%]
30,D10 > D36 > D5❌5 > D5❌0,6,6/6449 [0.09%]
31,D10 > D36 > D5❌1 > D5❌0,5,5/6449 [0.08%]
32,D10 > D35 > D5☑7 > D5❌_ > D10 > D35 > D5☑7,5,5/6449 [0.08%]
33,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,5,5/6449 [0.08%]
34,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,5,5/6449 [0.08%]
35,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0,5,5/6449 [0.08%]
36,D10 > D36 > D31 > D5❌5 > D5❌0,4,4/6449 [0.06%]
37,D10 > D5☑5 > D5❌_,4,4/6449 [0.06%]
38,D10 > D32 > D35 > D5☑7,4,4/6449 [0.06%]
39,D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5☑5,4,4/6449 [0.06%]
40,D10 > D32 > D5☑5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,4,4/6449 [0.06%]
41,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_ > D10 > D5☑5,3,3/6449 [0.05%]
42,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,3,3/6449 [0.05%]
43,D10 > D5❌6 > D10 > D36 > D31 > D5☑5,3,3/6449 [0.05%]
44,D10 > D5❌6 > D10 > D5❌6 > D5❌0,3,3/6449 [0.05%]
45,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D31 > D5☑5,3,3/6449 [0.05%]
46,D10 > D5❌6 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,3,3/6449 [0.05%]
47,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D36 > D5☑5,2,2/6449 [0.03%]
48,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,2,2/6449 [0.03%]
49,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,2,2/6449 [0.03%]
50,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D35 > D5☑7,2,2/6449 [0.03%]
51,D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,2,2/6449 [0.03%]
52,D10 > D5❌6 > D10 > D36 > D5☑5,2,2/6449 [0.03%]
53,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,2,2/6449 [0.03%]
54,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,2,2/6449 [0.03%]
55,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D5☑5,2,2/6449 [0.03%]
56,D10 > D5❌5 > D5❌0,2,2/6449 [0.03%]
57,D10 > D5❌2 > D5❌0 > D10 > D5☑5,2,2/6449 [0.03%]
58,D10 > D5❌2 > D5❌0 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,2,2/6449 [0.03%]
59,D10 > D32 > D5☑7 > D35,2,2/6449 [0.03%]
60,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/6449 [0.02%]
61,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,1,1/6449 [0.02%]
62,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D35 > D5☑7,1,1/6449 [0.02%]
63,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/6449 [0.02%]
64,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0,1,1/6449 [0.02%]
65,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/6449 [0.02%]
66,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D20,1,1/6449 [0.02%]
67,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/6449 [0.02%]
68,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D35 > D5☑7,1,1/6449 [0.02%]
69,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/6449 [0.02%]
70,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0,1,1/6449 [0.02%]
71,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0,1,1/6449 [0.02%]
72,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/6449 [0.02%]
73,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5☑5,1,1/6449 [0.02%]
74,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5❌7 > D5❌0 > D10 > D36 > D5☑5,1,1/6449 [0.02%]
75,D10 > D36 > D5❌5,1,1/6449 [0.02%]
76,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,1,1/6449 [0.02%]
77,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5☑7,1,1/6449 [0.02%]
78,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/6449 [0.02%]
79,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/6449 [0.02%]
80,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/6449 [0.02%]
81,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0,1,1/6449 [0.02%]
82,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/6449 [0.02%]
83,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/6449 [0.02%]
84,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D36 > D31 > D5☑5,1,1/6449 [0.02%]
85,D10 > D36 > D5❌5 > D10 > D36 > D5❌5 > D5❌0,1,1/6449 [0.02%]
86,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/6449 [0.02%]
87,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/6449 [0.02%]
88,D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/6449 [0.02%]
89,D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/6449 [0.02%]
90,D10 > D36 > D31 > D5❌5 > D10 > D36 > D31 > D5☑5,1,1/6449 [0.02%]
91,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/6449 [0.02%]
92,D10 > D32 > D35 > D5☑7 > D5❌_ > D10 > D32 > D5☑5,1,1/6449 [0.02%]
93,D10 > D35 > D5☑7 > D5❌_ > D10 > D35 > D5❌7 > D5❌0 > D10 > D35 > D5☑7,1,1/6449 [0.02%]
94,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D35 > D5☑7,1,1/6449 [0.02%]
95,D10 > D5❌2 > D5❌0 > D10 > D35 > D5☑7 > D5❌_ > D10 > D5☑7 > D35,1,1/6449 [0.02%]
96,D10 > D32 > D35 > D5❌7 > D5❌0 > D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D35 > D5☑7,1,1/6449 [0.02%]
97,D10 > D32 > D35 > D5☑7 > D5❌_ > D10 > D32 > D35 > D5☑7,1,1/6449 [0.02%]
98,D10 > D32 > D5❌5 > D5❌0 > D10 > D5❌2 > D5❌0 > D10 > D36 > D5☑5,1,1/6449 [0.02%]
99,D10 > D32 > D5❌5 > D10 > D32 > D5☑5,1,1/6449 [0.02%]
100,D10 > D36 > D31 > D35 > D5❌7 > D5❌0,1,1/6449 [0.02%]
101,D10 > D5❌5 > D5❌0 > D10 > D35 > D5☑7,1,1/6449 [0.02%]
102,D10 > D32 > D5☑5 > D5❌_ > D10 > D36 > D5☑5,1,1/6449 [0.02%]
103,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,1,1/6449 [0.02%]
104,D10 > D5❌5 > D5❌0 > D10 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/6449 [0.02%]
105,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,1,1/6449 [0.02%]
106,D10 > D5❌2 > D5❌0 > D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,1,1/6449 [0.02%]
107,D10 > D32 > D5☑5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,1,1/6449 [0.02%]
108,D10 > D32 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/6449 [0.02%]
109,D10 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/6449 [0.02%]
110,D10 > D32 > D5☑5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D5☑5,1,1/6449 [0.02%]

======================================================================

decl_only: 106 Declaration-Ablaeufe

,Ablauf,Traces,Anteil
0,D10 > D36 > D5☑5,4712,4712/10948 [43.04%]
1,D10 > D36 > D31 > D5☑5,2565,2565/10948 [23.43%]
2,D10 > D5☑5,1503,1503/10948 [13.73%]
3,D10 > D32 > D5☑5,608,608/10948 [5.55%]
4,D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,374,374/10948 [3.42%]
5,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,204,204/10948 [1.86%]
6,D10 > D5❌6 > D5❌0,184,184/10948 [1.68%]
7,D20,145,145/10948 [1.32%]
8,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,79,79/10948 [0.72%]
9,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,63,63/10948 [0.58%]
10,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,49,49/10948 [0.45%]
11,D10 > D5☑5 > D5❌_ > D10 > D5☑5,41,41/10948 [0.37%]
12,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,37,37/10948 [0.34%]
13,D10 > D36 > D5❌5 > D5❌0,31,31/10948 [0.28%]
14,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,31,31/10948 [0.28%]
15,D10 > D5☑5 > D5❌_,25,25/10948 [0.23%]
16,D10 > D5❌5 > D5❌0 > D10 > D5☑5,24,24/10948 [0.22%]
17,D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,20,20/10948 [0.18%]
18,D10 > D5❌5 > D5❌0,19,19/10948 [0.17%]
19,D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5☑5,14,14/10948 [0.13%]
20,D10 > D35 > D5☑7,14,14/10948 [0.13%]
21,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0,11,11/10948 [0.10%]
22,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,11,11/10948 [0.10%]
23,D10 > D36 > D35 > D5☑7,11,11/10948 [0.10%]
24,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,10,10/10948 [0.09%]
25,D10 > D36 > D5❌1 > D5❌0,8,8/10948 [0.07%]
26,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,8,8/10948 [0.07%]
27,D10 > D5❌2 > D5❌0,8,8/10948 [0.07%]
28,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,6,6/10948 [0.05%]
29,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,6,6/10948 [0.05%]
30,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0,6,6/10948 [0.05%]
31,D10 > D5❌6,5,5/10948 [0.05%]
32,D10 > D5❌2 > D5❌0 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,5,5/10948 [0.05%]
33,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0,4,4/10948 [0.04%]
34,D10 > D36 > D31 > D5❌5 > D5❌0,4,4/10948 [0.04%]
35,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,4,4/10948 [0.04%]
36,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,4,4/10948 [0.04%]
37,D10 > D5❌2 > D5❌0 > D10 > D5☑5,4,4/10948 [0.04%]
38,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,3,3/10948 [0.03%]
39,D10 > D5❌6 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,3,3/10948 [0.03%]
40,D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0,3,3/10948 [0.03%]
41,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,3,3/10948 [0.03%]
42,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0,3,3/10948 [0.03%]
43,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,3,3/10948 [0.03%]
44,D10 > D32 > D5❌5 > D5❌0,3,3/10948 [0.03%]
45,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,2,2/10948 [0.02%]
46,D10 > D5❌2 > D5❌0 > D10 > D36 > D5☑5,2,2/10948 [0.02%]
47,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D5☑5,2,2/10948 [0.02%]
48,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,2,2/10948 [0.02%]
49,D10 > D5❌6 > D10 > D5❌6 > D5❌0,2,2/10948 [0.02%]
50,D10 > D36 > D5❌5,2,2/10948 [0.02%]
51,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,2,2/10948 [0.02%]
52,D10 > D32 > D5☑5 > D5❌_,2,2/10948 [0.02%]
53,D10 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,2,2/10948 [0.02%]
54,D10 > D32 > D5☑5 > D5❌_ > D10 > D36 > D31 > D5☑5,1,1/10948 [0.01%]
55,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5☑5,1,1/10948 [0.01%]
56,D10 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,1,1/10948 [0.01%]
57,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,1,1/10948 [0.01%]
58,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D5❌0,1,1/10948 [0.01%]
59,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10948 [0.01%]
60,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D10 > D46 > D10 > D36 > D31 > D5☑5,1,1/10948 [0.01%]
61,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0,1,1/10948 [0.01%]
62,D10 > D5☑5 > D5❌_ > D10 > D36 > D5☑5,1,1/10948 [0.01%]
63,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10948 [0.01%]
64,D10 > D5☑5 > D5❌_ > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/10948 [0.01%]
65,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0,1,1/10948 [0.01%]
66,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,1,1/10948 [0.01%]
67,D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/10948 [0.01%]
68,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/10948 [0.01%]
69,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10948 [0.01%]
70,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌0,1,1/10948 [0.01%]
71,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10948 [0.01%]
72,D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/10948 [0.01%]
73,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5☑5,1,1/10948 [0.01%]
74,D10 > D5❌6 > D10 > D36 > D5❌5 > D5❌0,1,1/10948 [0.01%]
75,D10 > D36 > D5❌5 > D10 > D36 > D5☑5,1,1/10948 [0.01%]
76,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0,1,1/10948 [0.01%]
77,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D36 > D5☑5,1,1/10948 [0.01%]
78,D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/10948 [0.01%]
79,D10 > D36 > D31 > D5❌5,1,1/10948 [0.01%]
80,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10948 [0.01%]
81,D10 > D36 > D5❌5 > D10 > D5❌0 > D10 > D36 > D5☑5,1,1/10948 [0.01%]
82,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10948 [0.01%]
83,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10948 [0.01%]
84,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5,1,1/10948 [0.01%]
85,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,1,1/10948 [0.01%]
86,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/10948 [0.01%]
87,D10 > D35 > D5☑7 > D5❌_ > D10 > D35 > D5☑7,1,1/10948 [0.01%]
88,D10 > D32 > D35 > D5☑7,1,1/10948 [0.01%]
89,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D35 > D5☑7,1,1/10948 [0.01%]
90,D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5☑7,1,1/10948 [0.01%]
91,D10 > D36 > D31 > D35 > D5☑7,1,1/10948 [0.01%]
92,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/10948 [0.01%]
93,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/10948 [0.01%]
94,D10 > D5☑5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,1,1/10948 [0.01%]
95,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_,1,1/10948 [0.01%]
96,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0 > D10 > D5☑5,1,1/10948 [0.01%]
97,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,1,1/10948 [0.01%]
98,D10 > D5❌2 > D10 > D5❌0 > D10 > D32 > D5☑5,1,1/10948 [0.01%]
99,D10 > D5❌5 > D5❌0 > D10 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/10948 [0.01%]
100,D10 > D45 > D5❌_,1,1/10948 [0.01%]
101,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/10948 [0.01%]
102,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_,1,1/10948 [0.01%]
103,D10 > D5☑5 > D5❌_ > D10 > D5❌5 > D5❌0 > D10 > D5☑5,1,1/10948 [0.01%]
104,D10 > D42 > D5❌_,1,1/10948 [0.01%]
105,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0,1,1/10948 [0.01%]

======================================================================

decl_only_without_trips: 106 Declaration-Ablaeufe

,Ablauf,Traces,Anteil
0,D10 > D36 > D5☑5,4712,4712/10948 [43.04%]
1,D10 > D36 > D31 > D5☑5,2565,2565/10948 [23.43%]
2,D10 > D5☑5,1503,1503/10948 [13.73%]
3,D10 > D32 > D5☑5,608,608/10948 [5.55%]
4,D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,374,374/10948 [3.42%]
5,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,204,204/10948 [1.86%]
6,D10 > D5❌6 > D5❌0,184,184/10948 [1.68%]
7,D20,145,145/10948 [1.32%]
8,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,79,79/10948 [0.72%]
9,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,63,63/10948 [0.58%]
10,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,49,49/10948 [0.45%]
11,D10 > D5☑5 > D5❌_ > D10 > D5☑5,41,41/10948 [0.37%]
12,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,37,37/10948 [0.34%]
13,D10 > D36 > D5❌5 > D5❌0,31,31/10948 [0.28%]
14,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,31,31/10948 [0.28%]
15,D10 > D5☑5 > D5❌_,25,25/10948 [0.23%]
16,D10 > D5❌5 > D5❌0 > D10 > D5☑5,24,24/10948 [0.22%]
17,D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,20,20/10948 [0.18%]
18,D10 > D5❌5 > D5❌0,19,19/10948 [0.17%]
19,D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5☑5,14,14/10948 [0.13%]
20,D10 > D35 > D5☑7,14,14/10948 [0.13%]
21,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0,11,11/10948 [0.10%]
22,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,11,11/10948 [0.10%]
23,D10 > D36 > D35 > D5☑7,11,11/10948 [0.10%]
24,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,10,10/10948 [0.09%]
25,D10 > D36 > D5❌1 > D5❌0,8,8/10948 [0.07%]
26,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,8,8/10948 [0.07%]
27,D10 > D5❌2 > D5❌0,8,8/10948 [0.07%]
28,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,6,6/10948 [0.05%]
29,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,6,6/10948 [0.05%]
30,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0,6,6/10948 [0.05%]
31,D10 > D5❌6,5,5/10948 [0.05%]
32,D10 > D5❌2 > D5❌0 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,5,5/10948 [0.05%]
33,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0,4,4/10948 [0.04%]
34,D10 > D36 > D31 > D5❌5 > D5❌0,4,4/10948 [0.04%]
35,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,4,4/10948 [0.04%]
36,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,4,4/10948 [0.04%]
37,D10 > D5❌2 > D5❌0 > D10 > D5☑5,4,4/10948 [0.04%]
38,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,3,3/10948 [0.03%]
39,D10 > D5❌6 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,3,3/10948 [0.03%]
40,D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0,3,3/10948 [0.03%]
41,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,3,3/10948 [0.03%]
42,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0,3,3/10948 [0.03%]
43,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,3,3/10948 [0.03%]
44,D10 > D32 > D5❌5 > D5❌0,3,3/10948 [0.03%]
45,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,2,2/10948 [0.02%]
46,D10 > D5❌2 > D5❌0 > D10 > D36 > D5☑5,2,2/10948 [0.02%]
47,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D5☑5,2,2/10948 [0.02%]
48,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,2,2/10948 [0.02%]
49,D10 > D5❌6 > D10 > D5❌6 > D5❌0,2,2/10948 [0.02%]
50,D10 > D36 > D5❌5,2,2/10948 [0.02%]
51,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,2,2/10948 [0.02%]
52,D10 > D32 > D5☑5 > D5❌_,2,2/10948 [0.02%]
53,D10 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,2,2/10948 [0.02%]
54,D10 > D32 > D5☑5 > D5❌_ > D10 > D36 > D31 > D5☑5,1,1/10948 [0.01%]
55,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5☑5,1,1/10948 [0.01%]
56,D10 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,1,1/10948 [0.01%]
57,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,1,1/10948 [0.01%]
58,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D5❌0,1,1/10948 [0.01%]
59,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10948 [0.01%]
60,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D10 > D46 > D10 > D36 > D31 > D5☑5,1,1/10948 [0.01%]
61,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0,1,1/10948 [0.01%]
62,D10 > D5☑5 > D5❌_ > D10 > D36 > D5☑5,1,1/10948 [0.01%]
63,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10948 [0.01%]
64,D10 > D5☑5 > D5❌_ > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/10948 [0.01%]
65,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0,1,1/10948 [0.01%]
66,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,1,1/10948 [0.01%]
67,D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/10948 [0.01%]
68,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/10948 [0.01%]
69,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10948 [0.01%]
70,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌0,1,1/10948 [0.01%]
71,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10948 [0.01%]
72,D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/10948 [0.01%]
73,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5☑5,1,1/10948 [0.01%]
74,D10 > D5❌6 > D10 > D36 > D5❌5 > D5❌0,1,1/10948 [0.01%]
75,D10 > D36 > D5❌5 > D10 > D36 > D5☑5,1,1/10948 [0.01%]
76,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0,1,1/10948 [0.01%]
77,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D36 > D5☑5,1,1/10948 [0.01%]
78,D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/10948 [0.01%]
79,D10 > D36 > D31 > D5❌5,1,1/10948 [0.01%]
80,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10948 [0.01%]
81,D10 > D36 > D5❌5 > D10 > D5❌0 > D10 > D36 > D5☑5,1,1/10948 [0.01%]
82,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10948 [0.01%]
83,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/10948 [0.01%]
84,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5,1,1/10948 [0.01%]
85,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,1,1/10948 [0.01%]
86,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/10948 [0.01%]
87,D10 > D35 > D5☑7 > D5❌_ > D10 > D35 > D5☑7,1,1/10948 [0.01%]
88,D10 > D32 > D35 > D5☑7,1,1/10948 [0.01%]
89,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D35 > D5☑7,1,1/10948 [0.01%]
90,D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5☑7,1,1/10948 [0.01%]
91,D10 > D36 > D31 > D35 > D5☑7,1,1/10948 [0.01%]
92,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/10948 [0.01%]
93,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/10948 [0.01%]
94,D10 > D5☑5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,1,1/10948 [0.01%]
95,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_,1,1/10948 [0.01%]
96,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0 > D10 > D5☑5,1,1/10948 [0.01%]
97,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,1,1/10948 [0.01%]
98,D10 > D5❌2 > D10 > D5❌0 > D10 > D32 > D5☑5,1,1/10948 [0.01%]
99,D10 > D5❌5 > D5❌0 > D10 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/10948 [0.01%]
100,D10 > D45 > D5❌_,1,1/10948 [0.01%]
101,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/10948 [0.01%]
102,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_,1,1/10948 [0.01%]
103,D10 > D5☑5 > D5❌_ > D10 > D5❌5 > D5❌0 > D10 > D5☑5,1,1/10948 [0.01%]
104,D10 > D42 > D5❌_,1,1/10948 [0.01%]
105,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0,1,1/10948 [0.01%]

======================================================================

decl_and_permit: 108 Declaration-Ablaeufe

,Ablauf,Traces,Anteil
0,D10 > D36 > D5☑5,2225,2225/6001 [37.08%]
1,D10 > D36 > D31 > D5☑5,1179,1179/6001 [19.65%]
2,D10 > D5☑5,510,510/6001 [8.50%]
3,D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,485,485/6001 [8.08%]
4,D10 > D32 > D5☑5,394,394/6001 [6.57%]
5,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,327,327/6001 [5.45%]
6,D10 > D5❌6 > D5❌0,116,116/6001 [1.93%]
7,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,77,77/6001 [1.28%]
8,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,73,73/6001 [1.22%]
9,D20,64,64/6001 [1.07%]
10,D10 > D35 > D5☑7,59,59/6001 [0.98%]
11,D10 > D36 > D35 > D5☑7,54,54/6001 [0.90%]
12,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,50,50/6001 [0.83%]
13,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,37,37/6001 [0.62%]
14,D10 > D5☑5 > D5❌_ > D10 > D5☑5,30,30/6001 [0.50%]
15,D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5☑7,26,26/6001 [0.43%]
16,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,24,24/6001 [0.40%]
17,D10 > D36 > D31 > D35 > D5☑7,22,22/6001 [0.37%]
18,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,16,16/6001 [0.27%]
19,D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,14,14/6001 [0.23%]
20,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,12,12/6001 [0.20%]
21,D10 > D32 > D5☑5 > D5❌_,12,12/6001 [0.20%]
22,D10 > D5❌2 > D5❌0,10,10/6001 [0.17%]
23,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,9,9/6001 [0.15%]
24,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,9,9/6001 [0.15%]
25,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,7,7/6001 [0.12%]
26,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,7,7/6001 [0.12%]
27,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5☑7,6,6/6001 [0.10%]
28,D10 > D36 > D5❌5 > D5❌0,6,6/6001 [0.10%]
29,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,6,6/6001 [0.10%]
30,D10 > D36 > D5❌1 > D5❌0,5,5/6001 [0.08%]
31,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,5,5/6001 [0.08%]
32,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0,5,5/6001 [0.08%]
33,D10 > D5❌5 > D5❌0 > D10 > D5☑5,5,5/6001 [0.08%]
34,D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5☑5,4,4/6001 [0.07%]
35,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,4,4/6001 [0.07%]
36,D10 > D35 > D5☑7 > D5❌_ > D10 > D35 > D5☑7,4,4/6001 [0.07%]
37,D10 > D32 > D5☑5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,4,4/6001 [0.07%]
38,D10 > D36 > D31 > D5❌5 > D5❌0,3,3/6001 [0.05%]
39,D10 > D5❌6 > D10 > D36 > D31 > D5☑5,3,3/6001 [0.05%]
40,D10 > D5❌6 > D10 > D5❌6 > D5❌0,3,3/6001 [0.05%]
41,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D31 > D5☑5,3,3/6001 [0.05%]
42,D10 > D5❌6 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,3,3/6001 [0.05%]
43,D10 > D32 > D35 > D5☑7,3,3/6001 [0.05%]
44,D10 > D5☑5 > D5❌_,3,3/6001 [0.05%]
45,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D36 > D5☑5,2,2/6001 [0.03%]
46,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,2,2/6001 [0.03%]
47,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,2,2/6001 [0.03%]
48,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D35 > D5☑7,2,2/6001 [0.03%]
49,D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,2,2/6001 [0.03%]
50,D10 > D5❌6 > D10 > D36 > D5☑5,2,2/6001 [0.03%]
51,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,2,2/6001 [0.03%]
52,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,2,2/6001 [0.03%]
53,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D5☑5,2,2/6001 [0.03%]
54,D10 > D5❌5 > D5❌0,2,2/6001 [0.03%]
55,D10 > D5❌2 > D5❌0 > D10 > D5☑5,2,2/6001 [0.03%]
56,D10 > D5❌2 > D5❌0 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,2,2/6001 [0.03%]
57,D10 > D32 > D5☑7 > D35,2,2/6001 [0.03%]
58,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_ > D10 > D5☑5,2,2/6001 [0.03%]
59,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,2,2/6001 [0.03%]
60,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/6001 [0.02%]
61,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0,1,1/6001 [0.02%]
62,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/6001 [0.02%]
63,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D20,1,1/6001 [0.02%]
64,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/6001 [0.02%]
65,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D35 > D5☑7,1,1/6001 [0.02%]
66,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/6001 [0.02%]
67,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0,1,1/6001 [0.02%]
68,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0,1,1/6001 [0.02%]
69,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/6001 [0.02%]
70,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5☑5,1,1/6001 [0.02%]
71,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5❌7 > D5❌0 > D10 > D36 > D5☑5,1,1/6001 [0.02%]
72,D10 > D36 > D5❌5,1,1/6001 [0.02%]
73,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,1,1/6001 [0.02%]
74,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5☑7,1,1/6001 [0.02%]
75,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/6001 [0.02%]
76,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/6001 [0.02%]
77,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/6001 [0.02%]
78,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0,1,1/6001 [0.02%]
79,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/6001 [0.02%]
80,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/6001 [0.02%]
81,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D36 > D31 > D5☑5,1,1/6001 [0.02%]
82,D10 > D36 > D5❌5 > D10 > D36 > D5❌5 > D5❌0,1,1/6001 [0.02%]
83,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/6001 [0.02%]
84,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/6001 [0.02%]
85,D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/6001 [0.02%]
86,D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/6001 [0.02%]
87,D10 > D36 > D31 > D5❌5 > D10 > D36 > D31 > D5☑5,1,1/6001 [0.02%]
88,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/6001 [0.02%]
89,D10 > D32 > D35 > D5☑7 > D5❌_ > D10 > D32 > D5☑5,1,1/6001 [0.02%]
90,D10 > D35 > D5☑7 > D5❌_ > D10 > D35 > D5❌7 > D5❌0 > D10 > D35 > D5☑7,1,1/6001 [0.02%]
91,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D35 > D5☑7,1,1/6001 [0.02%]
92,D10 > D5❌2 > D5❌0 > D10 > D35 > D5☑7 > D5❌_ > D10 > D5☑7 > D35,1,1/6001 [0.02%]
93,D10 > D32 > D35 > D5❌7 > D5❌0 > D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D35 > D5☑7,1,1/6001 [0.02%]
94,D10 > D32 > D35 > D5☑7 > D5❌_ > D10 > D32 > D35 > D5☑7,1,1/6001 [0.02%]
95,D10 > D32 > D5❌5 > D5❌0 > D10 > D5❌2 > D5❌0 > D10 > D36 > D5☑5,1,1/6001 [0.02%]
96,D10 > D32 > D5❌5 > D10 > D32 > D5☑5,1,1/6001 [0.02%]
97,D10 > D36 > D31 > D35 > D5❌7 > D5❌0,1,1/6001 [0.02%]
98,D10 > D5❌5 > D5❌0 > D10 > D35 > D5☑7,1,1/6001 [0.02%]
99,D10 > D32 > D5☑5 > D5❌_ > D10 > D36 > D5☑5,1,1/6001 [0.02%]
100,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,1,1/6001 [0.02%]
101,D10 > D5❌5 > D5❌0 > D10 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/6001 [0.02%]
102,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,1,1/6001 [0.02%]
103,D10 > D5❌2 > D5❌0 > D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,1,1/6001 [0.02%]
104,D10 > D32 > D5☑5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,1,1/6001 [0.02%]
105,D10 > D32 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/6001 [0.02%]
106,D10 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/6001 [0.02%]
107,D10 > D32 > D5☑5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D5☑5,1,1/6001 [0.02%]

======================================================================

decl_and_permit_without_trips: 108 Declaration-Ablaeufe

,Ablauf,Traces,Anteil
0,D10 > D36 > D5☑5,2225,2225/6001 [37.08%]
1,D10 > D36 > D31 > D5☑5,1179,1179/6001 [19.65%]
2,D10 > D5☑5,510,510/6001 [8.50%]
3,D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,485,485/6001 [8.08%]
4,D10 > D32 > D5☑5,394,394/6001 [6.57%]
5,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,327,327/6001 [5.45%]
6,D10 > D5❌6 > D5❌0,116,116/6001 [1.93%]
7,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,77,77/6001 [1.28%]
8,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,73,73/6001 [1.22%]
9,D20,64,64/6001 [1.07%]
10,D10 > D35 > D5☑7,59,59/6001 [0.98%]
11,D10 > D36 > D35 > D5☑7,54,54/6001 [0.90%]
12,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,50,50/6001 [0.83%]
13,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,37,37/6001 [0.62%]
14,D10 > D5☑5 > D5❌_ > D10 > D5☑5,30,30/6001 [0.50%]
15,D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5☑7,26,26/6001 [0.43%]
16,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,24,24/6001 [0.40%]
17,D10 > D36 > D31 > D35 > D5☑7,22,22/6001 [0.37%]
18,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,16,16/6001 [0.27%]
19,D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,14,14/6001 [0.23%]
20,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,12,12/6001 [0.20%]
21,D10 > D32 > D5☑5 > D5❌_,12,12/6001 [0.20%]
22,D10 > D5❌2 > D5❌0,10,10/6001 [0.17%]
23,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,9,9/6001 [0.15%]
24,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,9,9/6001 [0.15%]
25,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,7,7/6001 [0.12%]
26,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,7,7/6001 [0.12%]
27,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5☑7,6,6/6001 [0.10%]
28,D10 > D36 > D5❌5 > D5❌0,6,6/6001 [0.10%]
29,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,6,6/6001 [0.10%]
30,D10 > D36 > D5❌1 > D5❌0,5,5/6001 [0.08%]
31,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,5,5/6001 [0.08%]
32,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0,5,5/6001 [0.08%]
33,D10 > D5❌5 > D5❌0 > D10 > D5☑5,5,5/6001 [0.08%]
34,D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5☑5,4,4/6001 [0.07%]
35,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,4,4/6001 [0.07%]
36,D10 > D35 > D5☑7 > D5❌_ > D10 > D35 > D5☑7,4,4/6001 [0.07%]
37,D10 > D32 > D5☑5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,4,4/6001 [0.07%]
38,D10 > D36 > D31 > D5❌5 > D5❌0,3,3/6001 [0.05%]
39,D10 > D5❌6 > D10 > D36 > D31 > D5☑5,3,3/6001 [0.05%]
40,D10 > D5❌6 > D10 > D5❌6 > D5❌0,3,3/6001 [0.05%]
41,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D31 > D5☑5,3,3/6001 [0.05%]
42,D10 > D5❌6 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,3,3/6001 [0.05%]
43,D10 > D32 > D35 > D5☑7,3,3/6001 [0.05%]
44,D10 > D5☑5 > D5❌_,3,3/6001 [0.05%]
45,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D36 > D5☑5,2,2/6001 [0.03%]
46,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,2,2/6001 [0.03%]
47,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,2,2/6001 [0.03%]
48,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D35 > D5☑7,2,2/6001 [0.03%]
49,D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,2,2/6001 [0.03%]
50,D10 > D5❌6 > D10 > D36 > D5☑5,2,2/6001 [0.03%]
51,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,2,2/6001 [0.03%]
52,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,2,2/6001 [0.03%]
53,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D5☑5,2,2/6001 [0.03%]
54,D10 > D5❌5 > D5❌0,2,2/6001 [0.03%]
55,D10 > D5❌2 > D5❌0 > D10 > D5☑5,2,2/6001 [0.03%]
56,D10 > D5❌2 > D5❌0 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,2,2/6001 [0.03%]
57,D10 > D32 > D5☑7 > D35,2,2/6001 [0.03%]
58,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_ > D10 > D5☑5,2,2/6001 [0.03%]
59,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,2,2/6001 [0.03%]
60,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/6001 [0.02%]
61,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0,1,1/6001 [0.02%]
62,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/6001 [0.02%]
63,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D20,1,1/6001 [0.02%]
64,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/6001 [0.02%]
65,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D35 > D5☑7,1,1/6001 [0.02%]
66,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/6001 [0.02%]
67,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0,1,1/6001 [0.02%]
68,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0,1,1/6001 [0.02%]
69,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/6001 [0.02%]
70,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5☑5,1,1/6001 [0.02%]
71,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5❌7 > D5❌0 > D10 > D36 > D5☑5,1,1/6001 [0.02%]
72,D10 > D36 > D5❌5,1,1/6001 [0.02%]
73,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,1,1/6001 [0.02%]
74,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5☑7,1,1/6001 [0.02%]
75,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/6001 [0.02%]
76,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/6001 [0.02%]
77,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/6001 [0.02%]
78,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0,1,1/6001 [0.02%]
79,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/6001 [0.02%]
80,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/6001 [0.02%]
81,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D36 > D31 > D5☑5,1,1/6001 [0.02%]
82,D10 > D36 > D5❌5 > D10 > D36 > D5❌5 > D5❌0,1,1/6001 [0.02%]
83,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/6001 [0.02%]
84,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/6001 [0.02%]
85,D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/6001 [0.02%]
86,D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/6001 [0.02%]
87,D10 > D36 > D31 > D5❌5 > D10 > D36 > D31 > D5☑5,1,1/6001 [0.02%]
88,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/6001 [0.02%]
89,D10 > D32 > D35 > D5☑7 > D5❌_ > D10 > D32 > D5☑5,1,1/6001 [0.02%]
90,D10 > D35 > D5☑7 > D5❌_ > D10 > D35 > D5❌7 > D5❌0 > D10 > D35 > D5☑7,1,1/6001 [0.02%]
91,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D35 > D5☑7,1,1/6001 [0.02%]
92,D10 > D5❌2 > D5❌0 > D10 > D35 > D5☑7 > D5❌_ > D10 > D5☑7 > D35,1,1/6001 [0.02%]
93,D10 > D32 > D35 > D5❌7 > D5❌0 > D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D35 > D5☑7,1,1/6001 [0.02%]
94,D10 > D32 > D35 > D5☑7 > D5❌_ > D10 > D32 > D35 > D5☑7,1,1/6001 [0.02%]
95,D10 > D32 > D5❌5 > D5❌0 > D10 > D5❌2 > D5❌0 > D10 > D36 > D5☑5,1,1/6001 [0.02%]
96,D10 > D32 > D5❌5 > D10 > D32 > D5☑5,1,1/6001 [0.02%]
97,D10 > D36 > D31 > D35 > D5❌7 > D5❌0,1,1/6001 [0.02%]
98,D10 > D5❌5 > D5❌0 > D10 > D35 > D5☑7,1,1/6001 [0.02%]
99,D10 > D32 > D5☑5 > D5❌_ > D10 > D36 > D5☑5,1,1/6001 [0.02%]
100,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,1,1/6001 [0.02%]
101,D10 > D5❌5 > D5❌0 > D10 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/6001 [0.02%]
102,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,1,1/6001 [0.02%]
103,D10 > D5❌2 > D5❌0 > D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,1,1/6001 [0.02%]
104,D10 > D32 > D5☑5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,1,1/6001 [0.02%]
105,D10 > D32 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/6001 [0.02%]
106,D10 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/6001 [0.02%]
107,D10 > D32 > D5☑5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D5☑5,1,1/6001 [0.02%]

======================================================================

decl_and_permit_without_trips_or_D20: 106 Declaration-Ablaeufe

,Ablauf,Traces,Anteil
0,D10 > D36 > D5☑5,2225,2225/5937 [37.48%]
1,D10 > D36 > D31 > D5☑5,1179,1179/5937 [19.86%]
2,D10 > D5☑5,510,510/5937 [8.59%]
3,D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,485,485/5937 [8.17%]
4,D10 > D32 > D5☑5,394,394/5937 [6.64%]
5,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,327,327/5937 [5.51%]
6,D10 > D5❌6 > D5❌0,116,116/5937 [1.95%]
7,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,77,77/5937 [1.30%]
8,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,73,73/5937 [1.23%]
9,D10 > D35 > D5☑7,59,59/5937 [0.99%]
10,D10 > D36 > D35 > D5☑7,54,54/5937 [0.91%]
11,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,50,50/5937 [0.84%]
12,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,37,37/5937 [0.62%]
13,D10 > D5☑5 > D5❌_ > D10 > D5☑5,30,30/5937 [0.51%]
14,D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5☑7,26,26/5937 [0.44%]
15,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,24,24/5937 [0.40%]
16,D10 > D36 > D31 > D35 > D5☑7,22,22/5937 [0.37%]
17,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,16,16/5937 [0.27%]
18,D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,14,14/5937 [0.24%]
19,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,12,12/5937 [0.20%]
20,D10 > D32 > D5☑5 > D5❌_,12,12/5937 [0.20%]
21,D10 > D5❌2 > D5❌0,10,10/5937 [0.17%]
22,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,9,9/5937 [0.15%]
23,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,9,9/5937 [0.15%]
24,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,7,7/5937 [0.12%]
25,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,7,7/5937 [0.12%]
26,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5☑7,6,6/5937 [0.10%]
27,D10 > D36 > D5❌5 > D5❌0,6,6/5937 [0.10%]
28,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0,6,6/5937 [0.10%]
29,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,6,6/5937 [0.10%]
30,D10 > D36 > D5❌1 > D5❌0,5,5/5937 [0.08%]
31,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,5,5/5937 [0.08%]
32,D10 > D5❌5 > D5❌0 > D10 > D5☑5,5,5/5937 [0.08%]
33,D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5☑5,4,4/5937 [0.07%]
34,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,4,4/5937 [0.07%]
35,D10 > D35 > D5☑7 > D5❌_ > D10 > D35 > D5☑7,4,4/5937 [0.07%]
36,D10 > D32 > D5☑5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,4,4/5937 [0.07%]
37,D10 > D36 > D31 > D5❌5 > D5❌0,3,3/5937 [0.05%]
38,D10 > D5❌6 > D10 > D36 > D31 > D5☑5,3,3/5937 [0.05%]
39,D10 > D5❌6 > D10 > D5❌6 > D5❌0,3,3/5937 [0.05%]
40,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D31 > D5☑5,3,3/5937 [0.05%]
41,D10 > D5❌6 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,3,3/5937 [0.05%]
42,D10 > D32 > D35 > D5☑7,3,3/5937 [0.05%]
43,D10 > D5☑5 > D5❌_,3,3/5937 [0.05%]
44,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D36 > D5☑5,2,2/5937 [0.03%]
45,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,2,2/5937 [0.03%]
46,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,2,2/5937 [0.03%]
47,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D35 > D5☑7,2,2/5937 [0.03%]
48,D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,2,2/5937 [0.03%]
49,D10 > D5❌6 > D10 > D36 > D5☑5,2,2/5937 [0.03%]
50,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,2,2/5937 [0.03%]
51,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,2,2/5937 [0.03%]
52,D10 > D5❌6 > D10 > D5❌0 > D10 > D36 > D5☑5,2,2/5937 [0.03%]
53,D10 > D5❌5 > D5❌0,2,2/5937 [0.03%]
54,D10 > D5❌2 > D5❌0 > D10 > D5☑5,2,2/5937 [0.03%]
55,D10 > D5❌2 > D5❌0 > D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,2,2/5937 [0.03%]
56,D10 > D32 > D5☑7 > D35,2,2/5937 [0.03%]
57,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_ > D10 > D5☑5,2,2/5937 [0.03%]
58,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,2,2/5937 [0.03%]
59,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/5937 [0.02%]
60,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0,1,1/5937 [0.02%]
61,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/5937 [0.02%]
62,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/5937 [0.02%]
63,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D35 > D5☑7,1,1/5937 [0.02%]
64,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/5937 [0.02%]
65,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0,1,1/5937 [0.02%]
66,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0,1,1/5937 [0.02%]
67,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/5937 [0.02%]
68,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D5☑5,1,1/5937 [0.02%]
69,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5❌7 > D5❌0 > D10 > D36 > D5☑5,1,1/5937 [0.02%]
70,D10 > D36 > D5❌5,1,1/5937 [0.02%]
71,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,1,1/5937 [0.02%]
72,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5☑7,1,1/5937 [0.02%]
73,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/5937 [0.02%]
74,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/5937 [0.02%]
75,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/5937 [0.02%]
76,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0,1,1/5937 [0.02%]
77,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/5937 [0.02%]
78,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/5937 [0.02%]
79,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D36 > D31 > D5☑5,1,1/5937 [0.02%]
80,D10 > D36 > D5❌5 > D10 > D36 > D5❌5 > D5❌0,1,1/5937 [0.02%]
81,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/5937 [0.02%]
82,D10 > D5❌6 > D5❌0 > D10 > D36 > D5❌1 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/5937 [0.02%]
83,D10 > D36 > D5❌5 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/5937 [0.02%]
84,D10 > D5❌6 > D10 > D5❌6 > D10 > D5❌6 > D5❌0,1,1/5937 [0.02%]
85,D10 > D36 > D31 > D5❌5 > D10 > D36 > D31 > D5☑5,1,1/5937 [0.02%]
86,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/5937 [0.02%]
87,D10 > D32 > D35 > D5☑7 > D5❌_ > D10 > D32 > D5☑5,1,1/5937 [0.02%]
88,D10 > D35 > D5☑7 > D5❌_ > D10 > D35 > D5❌7 > D5❌0 > D10 > D35 > D5☑7,1,1/5937 [0.02%]
89,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D35 > D5☑7,1,1/5937 [0.02%]
90,D10 > D5❌2 > D5❌0 > D10 > D35 > D5☑7 > D5❌_ > D10 > D5☑7 > D35,1,1/5937 [0.02%]
91,D10 > D32 > D35 > D5❌7 > D5❌0 > D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D35 > D5☑7,1,1/5937 [0.02%]
92,D10 > D32 > D35 > D5☑7 > D5❌_ > D10 > D32 > D35 > D5☑7,1,1/5937 [0.02%]
93,D10 > D32 > D5❌5 > D5❌0 > D10 > D5❌2 > D5❌0 > D10 > D36 > D5☑5,1,1/5937 [0.02%]
94,D10 > D32 > D5❌5 > D10 > D32 > D5☑5,1,1/5937 [0.02%]
95,D10 > D36 > D31 > D35 > D5❌7 > D5❌0,1,1/5937 [0.02%]
96,D10 > D5❌5 > D5❌0 > D10 > D35 > D5☑7,1,1/5937 [0.02%]
97,D10 > D32 > D5☑5 > D5❌_ > D10 > D36 > D5☑5,1,1/5937 [0.02%]
98,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,1,1/5937 [0.02%]
99,D10 > D5❌5 > D5❌0 > D10 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/5937 [0.02%]
100,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,1,1/5937 [0.02%]
101,D10 > D5❌2 > D5❌0 > D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,1,1/5937 [0.02%]
102,D10 > D32 > D5☑5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,1,1/5937 [0.02%]
103,D10 > D32 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/5937 [0.02%]
104,D10 > D5❌5 > D5❌0 > D10 > D36 > D31 > D5☑5,1,1/5937 [0.02%]
105,D10 > D32 > D5☑5 > D5❌_ > D10 > D5❌2 > D5❌0 > D10 > D5☑5,1,1/5937 [0.02%]

======================================================================

international_only_decl: 32 Declaration-Ablaeufe

,Ablauf,Traces,Anteil
0,D10 > D5☑5,111,111/448 [24.78%]
1,D10 > D36 > D5☑5,90,90/448 [20.09%]
2,D10 > D36 > D31 > D5☑5,90,90/448 [20.09%]
3,D10 > D32 > D5☑5,33,33/448 [7.37%]
4,D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,29,29/448 [6.47%]
5,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,16,16/448 [3.57%]
6,D10 > D35 > D5☑7,14,14/448 [3.12%]
7,D10 > D36 > D35 > D5☑7,11,11/448 [2.46%]
8,D20,10,10/448 [2.23%]
9,D10 > D5❌6 > D5❌0,10,10/448 [2.23%]
10,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,6,6/448 [1.34%]
11,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,3,3/448 [0.67%]
12,D10 > D5❌5 > D5❌0 > D10 > D5☑5,2,2/448 [0.45%]
13,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,2,2/448 [0.45%]
14,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,2,2/448 [0.45%]
15,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,2,2/448 [0.45%]
16,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,2,2/448 [0.45%]
17,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,1,1/448 [0.22%]
18,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/448 [0.22%]
19,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,1,1/448 [0.22%]
20,D10 > D5☑5 > D5❌_,1,1/448 [0.22%]
21,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,1,1/448 [0.22%]
22,D10 > D35 > D5☑7 > D5❌_ > D10 > D35 > D5☑7,1,1/448 [0.22%]
23,D10 > D32 > D35 > D5☑7,1,1/448 [0.22%]
24,D10 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/448 [0.22%]
25,D10 > D36 > D31 > D5❌5 > D5❌0,1,1/448 [0.22%]
26,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D35 > D5☑7,1,1/448 [0.22%]
27,D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5☑7,1,1/448 [0.22%]
28,D10 > D36 > D31 > D35 > D5☑7,1,1/448 [0.22%]
29,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/448 [0.22%]
30,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/448 [0.22%]
31,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/448 [0.22%]

======================================================================

international_only_decl_without_trips: 32 Declaration-Ablaeufe

,Ablauf,Traces,Anteil
0,D10 > D5☑5,111,111/448 [24.78%]
1,D10 > D36 > D5☑5,90,90/448 [20.09%]
2,D10 > D36 > D31 > D5☑5,90,90/448 [20.09%]
3,D10 > D32 > D5☑5,33,33/448 [7.37%]
4,D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,29,29/448 [6.47%]
5,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,16,16/448 [3.57%]
6,D10 > D35 > D5☑7,14,14/448 [3.12%]
7,D10 > D36 > D35 > D5☑7,11,11/448 [2.46%]
8,D20,10,10/448 [2.23%]
9,D10 > D5❌6 > D5❌0,10,10/448 [2.23%]
10,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,6,6/448 [1.34%]
11,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,3,3/448 [0.67%]
12,D10 > D5❌5 > D5❌0 > D10 > D5☑5,2,2/448 [0.45%]
13,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,2,2/448 [0.45%]
14,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,2,2/448 [0.45%]
15,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,2,2/448 [0.45%]
16,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,2,2/448 [0.45%]
17,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,1,1/448 [0.22%]
18,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/448 [0.22%]
19,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,1,1/448 [0.22%]
20,D10 > D5☑5 > D5❌_,1,1/448 [0.22%]
21,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,1,1/448 [0.22%]
22,D10 > D35 > D5☑7 > D5❌_ > D10 > D35 > D5☑7,1,1/448 [0.22%]
23,D10 > D32 > D35 > D5☑7,1,1/448 [0.22%]
24,D10 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/448 [0.22%]
25,D10 > D36 > D31 > D5❌5 > D5❌0,1,1/448 [0.22%]
26,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D35 > D5☑7,1,1/448 [0.22%]
27,D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5☑7,1,1/448 [0.22%]
28,D10 > D36 > D31 > D35 > D5☑7,1,1/448 [0.22%]
29,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/448 [0.22%]
30,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/448 [0.22%]
31,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/448 [0.22%]

======================================================================

international_only_decl_without_trips_or_D20: 31 Declaration-Ablaeufe

,Ablauf,Traces,Anteil
0,D10 > D5☑5,111,111/438 [25.34%]
1,D10 > D36 > D5☑5,90,90/438 [20.55%]
2,D10 > D36 > D31 > D5☑5,90,90/438 [20.55%]
3,D10 > D32 > D5☑5,33,33/438 [7.53%]
4,D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,29,29/438 [6.62%]
5,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,16,16/438 [3.65%]
6,D10 > D35 > D5☑7,14,14/438 [3.20%]
7,D10 > D36 > D35 > D5☑7,11,11/438 [2.51%]
8,D10 > D5❌6 > D5❌0,10,10/438 [2.28%]
9,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5,6,6/438 [1.37%]
10,D10 > D32 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,3,3/438 [0.68%]
11,D10 > D5❌5 > D5❌0 > D10 > D5☑5,2,2/438 [0.46%]
12,D10 > D36 > D5❌5 > D5❌0 > D10 > D36 > D5☑5,2,2/438 [0.46%]
13,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,2,2/438 [0.46%]
14,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D5☑5,2,2/438 [0.46%]
15,D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,2,2/438 [0.46%]
16,D10 > D5❌5 > D5❌0 > D10 > D5❌5 > D5❌0 > D10 > D32 > D5☑5,1,1/438 [0.23%]
17,D10 > D5☑5 > D5❌_ > D10 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/438 [0.23%]
18,D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,1,1/438 [0.23%]
19,D10 > D5☑5 > D5❌_,1,1/438 [0.23%]
20,D10 > D5❌2 > D5❌0 > D10 > D32 > D5☑5 > D5❌_ > D10 > D32 > D5☑5,1,1/438 [0.23%]
21,D10 > D35 > D5☑7 > D5❌_ > D10 > D35 > D5☑7,1,1/438 [0.23%]
22,D10 > D32 > D35 > D5☑7,1,1/438 [0.23%]
23,D10 > D5☑5 > D5❌_ > D10 > D5☑5,1,1/438 [0.23%]
24,D10 > D36 > D31 > D5❌5 > D5❌0,1,1/438 [0.23%]
25,D10 > D36 > D31 > D5❌5 > D5❌0 > D10 > D36 > D35 > D5☑7,1,1/438 [0.23%]
26,D10 > D5❌6 > D5❌0 > D10 > D36 > D35 > D5☑7,1,1/438 [0.23%]
27,D10 > D36 > D31 > D35 > D5☑7,1,1/438 [0.23%]
28,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D5☑5,1,1/438 [0.23%]
29,D10 > D5❌6 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/438 [0.23%]
30,D10 > D36 > D5❌1 > D5❌0 > D10 > D5❌6 > D5❌0 > D10 > D36 > D31 > D35 > D5☑7,1,1/438 [0.23%]

In [16]:
import re
from collections import Counter
from python_analysis.functions import variants

domestic_without_trips = logs["domestic"][
    ~logs["domestic"]["concept:name"].isin(["Start trip", "End trip"])
]
declaration_events = domestic_without_trips[
    domestic_without_trips["concept:name"].str.contains(
        r"\bDeclaration\b", na=False
    )
]

def split_variants(log, event: str):
    counts = Counter()
    for row in variants(log).itertuples(index=False):
        # D10 bleibt erhalten; ein D10 am Trace-Anfang erzeugt keinen leeren Teil.
        parts = re.split(r" > (?="+event+"(?: > |$))", row.Ablauf)
        for part in parts:
            counts[part] += row.Traces

    split_variants = (
        pd.DataFrame(counts.items(), columns=["Ablauf", "Teil-Traces"])
        .sort_values("Teil-Traces", ascending=False, ignore_index=True)
    )
    total = split_variants["Teil-Traces"].sum()
    split_variants["Anteil"] = split_variants["Teil-Traces"].map(
        lambda n: f"{n}/{total} [{n / total:.2%}]"
    )

    return split_variants

with pd.option_context("display.max_rows", None, "display.max_colwidth", None):
    df = split_variants(declaration_events, "D10") # Declaration Submitted by EMPLOYEE
    display(df)

                           Ablauf  Teil-Traces               Anteil
0                D10 > D36 > D5☑5         5133  5133/11666 [44.00%]
1          D10 > D36 > D31 > D5☑5         2788  2788/11666 [23.90%]
2                      D10 > D5☑5         1462  1462/11666 [12.53%]
3               D10 > D5❌6 > D5❌0          928    928/11666 [7.95%]
4                D10 > D32 > D5☑5          659    659/11666 [5.65%]
5         D10 > D36 > D5❌5 > D5❌0          185    185/11666 [1.59%]
6                             D20          135    135/11666 [1.16%]
7               D10 > D5❌2 > D5❌0           85     85/11666 [0.73%]
8               D10 > D5☑5 > D5❌_           74     74/11666 [0.63%]
9               D10 > D5❌5 > D5❌0           60     60/11666 [0.51%]
10        D10 > D36 > D5❌1 > D5❌0           58     58/11666 [0.50%]
11  D10 > D36 > D31 > D5❌5 > D5❌0           31     31/11666 [0.27%]
12                     D10 > D5❌6           24     24/11666 [0.21%]
13        D10 > D32 > D5☑5 > D5❌_           15     15/11666 [0.13%]
14        D10 > D32 > D5❌5 > D5❌0           11     11/11666 [0.09%]
15                     D10 > D5❌0            7      7/11666 [0.06%]
16               D10 > D36 > D5❌5            5      5/11666 [0.04%]
17               D10 > D36 > D5❌1            1      1/11666 [0.01%]
18                      D10 > D46            1      1/11666 [0.01%]
19         D10 > D36 > D31 > D5❌5            1      1/11666 [0.01%]
20                     D10 > D5❌2            1      1/11666 [0.01%]
21               D10 > D45 > D5❌_            1      1/11666 [0.01%]
22               D10 > D42 > D5❌_            1      1/11666 [0.01%]

In [17]:
with pd.option_context("display.max_rows", None, "display.max_colwidth", None):
    df = variants(declaration_events)
    display(df.loc[df["Ablauf"].str.contains("D20", regex=False, na=False)])

with pd.option_context("display.max_rows", None, "display.max_colwidth", None):
    df = split_variants(declaration_events, "D20") # Declaration SAVED by EMPLOYEE
    #display(df)
    display(df.loc[df["Ablauf"].str.contains("D20", na=False)])

  Ablauf  Traces             Anteil
7    D20     135  135/10500 [1.29%]

  Ablauf  Teil-Traces             Anteil
7    D20          135  135/10500 [1.29%]

Aufgabe 2

In [26]:
# Frage 2: volle Ausgangslogs, unabhaengig von Miner und Discovery-Aufteilung.
# Zeiten = erster bis letzter beobachteter Event, nicht zwingend abgeschlossene Faelle.
# Zellenangaben unten zaehlen alle Notebook-Zellen ab 1, nicht Ausfuehrungsnummern.
analysis_logs = {"domestic": dom_log_base, "international": int_log_base}
duration_results = {}
for name, log in analysis_logs.items():
    duration_results[name] = process_durations(log)
    print(name)
    display(duration_results[name]["summary"])
    #display(duration_results[name]["by_start_month"]) #Randmonate eventuell nicht repräsentant
    #display(duration_results[name]["cases"].head(20))

domestic

         cases  mean_days  median_days  min_days    max_days   p90_days
group
all    10500.0  11.525722     7.330289       0.0  469.236319  20.120839

international

        cases  mean_days  median_days  min_days  max_days    p90_days
group
all    6449.0  86.451729    66.041667  6.729988     742.0  159.185472

Aufgabe 3

In [19]:
# Frage 3: direkt aufeinanderfolgende Events mit langen Zeitabstaenden.
# Keine Trennung von Warte-, Arbeits- und Reisezeit, keine automatische Ursachenbestimmung.
# Alle Paare bleiben im Ergebnis; angezeigt werden je 20 nach Median und Gesamtzeit.
bottleneck_results = {}
for name, log in analysis_logs.items():
    bottleneck_results[name] = bottleneck_analysis(log)
    print(name, '- Engpass-Kandidaten, Zeiten in Tagen')
    transitions = bottleneck_results[name]["transitions"]
    display(transitions.head(20))
    display(transitions.sort_values("total_days", ascending=False).head(20))
    display(bottleneck_results[name]["intervals"].head(20))

domestic - Engpass-Kandidaten, Zeiten in Tagen

                                                                                     occurrences  \
from_activity                              to_activity
Declaration FINAL_APPROVED by SUPERVISOR   Payment Handled                                     7
Request Payment                            Declaration REJECTED by MISSING                     3
Declaration SAVED by EMPLOYEE              Request Payment                                     1
Declaration REJECTED by SUPERVISOR         Request Payment                                     1
Declaration REJECTED by BUDGET OWNER       Declaration SUBMITTED by EMPLOYEE                   1
Declaration FOR_APPROVAL by PRE_APPROVER   Declaration REJECTED by MISSING                     1
Declaration APPROVED by BUDGET OWNER       Declaration REJECTED by SUPERVISOR                 32
Request Payment                            Payment Handled                                 10037
Declaration FINAL_APPROVED by SUPERVISOR   Declaration REJECTED by MISSING                    86
Declaration APPROVED by PRE_APPROVER       Declaration REJECTED by SUPERVISOR                 11
Declaration REJECTED by SUPERVISOR         Declaration SUBMITTED by EMPLOYEE                   2
Declaration APPROVED by BUDGET OWNER       Declaration FINAL_APPROVED by SUPERVISOR         2788
Payment Handled                            Declaration REJECTED by EMPLOYEE                    1
Declaration FINAL_APPROVED by SUPERVISOR   Request Payment                                 10038
Declaration REJECTED by SUPERVISOR         Declaration REJECTED by EMPLOYEE                  286
Declaration REJECTED by BUDGET OWNER       Declaration REJECTED by EMPLOYEE                   58
Declaration FOR_APPROVAL by ADMINISTRATION Declaration SUBMITTED by EMPLOYEE                   1
Declaration REJECTED by ADMINISTRATION     Declaration SUBMITTED by EMPLOYEE                  19
                                           Declaration REJECTED by EMPLOYEE                  928
Declaration APPROVED by ADMINISTRATION     Declaration REJECTED by SUPERVISOR                190

                                                                                     cases  \
from_activity                              to_activity
Declaration FINAL_APPROVED by SUPERVISOR   Payment Handled                               7
Request Payment                            Declaration REJECTED by MISSING               3
Declaration SAVED by EMPLOYEE              Request Payment                               1
Declaration REJECTED by SUPERVISOR         Request Payment                               1
Declaration REJECTED by BUDGET OWNER       Declaration SUBMITTED by EMPLOYEE             1
Declaration FOR_APPROVAL by PRE_APPROVER   Declaration REJECTED by MISSING               1
Declaration APPROVED by BUDGET OWNER       Declaration REJECTED by SUPERVISOR           32
Request Payment                            Payment Handled                           10037
Declaration FINAL_APPROVED by SUPERVISOR   Declaration REJECTED by MISSING              82
Declaration APPROVED by PRE_APPROVER       Declaration REJECTED by SUPERVISOR           11
Declaration REJECTED by SUPERVISOR         Declaration SUBMITTED by EMPLOYEE             2
Declaration APPROVED by BUDGET OWNER       Declaration FINAL_APPROVED by SUPERVISOR   2788
Payment Handled                            Declaration REJECTED by EMPLOYEE              1
Declaration FINAL_APPROVED by SUPERVISOR   Request Payment                           10038
Declaration REJECTED by SUPERVISOR         Declaration REJECTED by EMPLOYEE            274
Declaration REJECTED by BUDGET OWNER       Declaration REJECTED by EMPLOYEE             57
Declaration FOR_APPROVAL by ADMINISTRATION Declaration SUBMITTED by EMPLOYEE             1
Declaration REJECTED by ADMINISTRATION     Declaration SUBMITTED by EMPLOYEE            14
                                           Declaration REJECTED by EMPLOYEE            837
Declaration APPROVED by ADMINISTRATION     Declaration REJECTED by SUPERVISOR          186

                                                                                     mean_days  \
from_activity                              to_activity
Declaration FINAL_APPROVED by SUPERVISOR   Payment Handled                           81.585701
Request Payment                            Declaration REJECTED by MISSING           18.986154
Declaration SAVED by EMPLOYEE              Request Payment                           17.033345
Declaration REJECTED by SUPERVISOR         Request Payment                            6.922326
Declaration REJECTED by BUDGET OWNER       Declaration SUBMITTED by EMPLOYEE          6.092315
Declaration FOR_APPROVAL by PRE_APPROVER   Declaration REJECTED by MISSING            4.132477
Declaration APPROVED by BUDGET OWNER       Declaration REJECTED by SUPERVISOR         4.189010
Request Payment                            Payment Handled                            3.574593
Declaration FINAL_APPROVED by SUPERVISOR   Declaration REJECTED by MISSING           11.029341
Declaration APPROVED by PRE_APPROVER       Declaration REJECTED by SUPERVISOR         2.998766
Declaration REJECTED by SUPERVISOR         Declaration SUBMITTED by EMPLOYEE          1.914624
Declaration APPROVED by BUDGET OWNER       Declaration FINAL_APPROVED by SUPERVISOR   2.864106
Payment Handled                            Declaration REJECTED by EMPLOYEE           1.625278
Declaration FINAL_APPROVED by SUPERVISOR   Request Payment                            3.162912
Declaration REJECTED by SUPERVISOR         Declaration REJECTED by EMPLOYEE           3.682776
Declaration REJECTED by BUDGET OWNER       Declaration REJECTED by EMPLOYEE           2.135020
Declaration FOR_APPROVAL by ADMINISTRATION Declaration SUBMITTED by EMPLOYEE          1.016481
Declaration REJECTED by ADMINISTRATION     Declaration SUBMITTED by EMPLOYEE          2.213864
                                           Declaration REJECTED by EMPLOYEE           2.043734
Declaration APPROVED by ADMINISTRATION     Declaration REJECTED by SUPERVISOR         2.191663

                                                                                     median_days  \
from_activity                              to_activity
Declaration FINAL_APPROVED by SUPERVISOR   Payment Handled                             48.366100
Request Payment                            Declaration REJECTED by MISSING             26.765324
Declaration SAVED by EMPLOYEE              Request Payment                             17.033345
Declaration REJECTED by SUPERVISOR         Request Payment                              6.922326
Declaration REJECTED by BUDGET OWNER       Declaration SUBMITTED by EMPLOYEE            6.092315
Declaration FOR_APPROVAL by PRE_APPROVER   Declaration REJECTED by MISSING              4.132477
Declaration APPROVED by BUDGET OWNER       Declaration REJECTED by SUPERVISOR           3.996985
Request Payment                            Payment Handled                              3.240475
Declaration FINAL_APPROVED by SUPERVISOR   Declaration REJECTED by MISSING              3.060185
Declaration APPROVED by PRE_APPROVER       Declaration REJECTED by SUPERVISOR           2.093958
Declaration REJECTED by SUPERVISOR         Declaration SUBMITTED by EMPLOYEE            1.914624
Declaration APPROVED by BUDGET OWNER       Declaration FINAL_APPROVED by SUPERVISOR     1.909751
Payment Handled                            Declaration REJECTED by EMPLOYEE             1.625278
Declaration FINAL_APPROVED by SUPERVISOR   Request Payment                              1.142836
Declaration REJECTED by SUPERVISOR         Declaration REJECTED by EMPLOYEE             1.048466
Declaration REJECTED by BUDGET OWNER       Declaration REJECTED by EMPLOYEE             1.023432
Declaration FOR_APPROVAL by ADMINISTRATION Declaration SUBMITTED by EMPLOYEE            1.016481
Declaration REJECTED by ADMINISTRATION     Declaration SUBMITTED by EMPLOYEE            0.948310
                                           Declaration REJECTED by EMPLOYEE             0.922176
Declaration APPROVED by ADMINISTRATION     Declaration REJECTED by SUPERVISOR           0.918646

                                                                                       p90_days  \
from_activity                              to_activity
Declaration FINAL_APPROVED by SUPERVISOR   Payment Handled                           147.397583
Request Payment                            Declaration REJECTED by MISSING            29.304361
Declaration SAVED by EMPLOYEE              Request Payment                            17.033345
Declaration REJECTED by SUPERVISOR         Request Payment                             6.922326
Declaration REJECTED by BUDGET OWNER       Declaration SUBMITTED by EMPLOYEE           6.092315
Declaration FOR_APPROVAL by PRE_APPROVER   Declaration REJECTED by MISSING             4.132477
Declaration APPROVED by BUDGET OWNER       Declaration REJECTED by SUPERVISOR          6.836884
Request Payment                            Payment Handled                             4.912648
Declaration FINAL_APPROVED by SUPERVISOR   Declaration REJECTED by MISSING            13.878374
Declaration APPROVED by PRE_APPROVER       Declaration REJECTED by SUPERVISOR          6.773345
Declaration REJECTED by SUPERVISOR         Declaration SUBMITTED by EMPLOYEE           2.583841
Declaration APPROVED by BUDGET OWNER       Declaration FINAL_APPROVED by SUPERVISOR    6.720473
Payment Handled                            Declaration REJECTED by EMPLOYEE            1.625278
Declaration FINAL_APPROVED by SUPERVISOR   Request Payment                             6.974372
Declaration REJECTED by SUPERVISOR         Declaration REJECTED by EMPLOYEE            9.902436
Declaration REJECTED by BUDGET OWNER       Declaration REJECTED by EMPLOYEE            4.923522
Declaration FOR_APPROVAL by ADMINISTRATION Declaration SUBMITTED by EMPLOYEE           1.016481
Declaration REJECTED by ADMINISTRATION     Declaration SUBMITTED by EMPLOYEE           6.247301
                                           Declaration REJECTED by EMPLOYEE            5.040957
Declaration APPROVED by ADMINISTRATION     Declaration REJECTED by SUPERVISOR          4.935568

                                                                                       max_days  \
from_activity                              to_activity
Declaration FINAL_APPROVED by SUPERVISOR   Payment Handled                           284.274653
Request Payment                            Declaration REJECTED by MISSING            29.939120
Declaration SAVED by EMPLOYEE              Request Payment                            17.033345
Declaration REJECTED by SUPERVISOR         Request Payment                             6.922326
Declaration REJECTED by BUDGET OWNER       Declaration SUBMITTED by EMPLOYEE           6.092315
Declaration FOR_APPROVAL by PRE_APPROVER   Declaration REJECTED by MISSING             4.132477
Declaration APPROVED by BUDGET OWNER       Declaration REJECTED by SUPERVISOR          6.849745
Request Payment                            Payment Handled                            62.145127
Declaration FINAL_APPROVED by SUPERVISOR   Declaration REJECTED by MISSING           293.360428
Declaration APPROVED by PRE_APPROVER       Declaration REJECTED by SUPERVISOR          6.782234
Declaration REJECTED by SUPERVISOR         Declaration SUBMITTED by EMPLOYEE           2.751146
Declaration APPROVED by BUDGET OWNER       Declaration FINAL_APPROVED by SUPERVISOR   11.852593
Payment Handled                            Declaration REJECTED by EMPLOYEE            1.625278
Declaration FINAL_APPROVED by SUPERVISOR   Request Payment                           234.680012
Declaration REJECTED by SUPERVISOR         Declaration REJECTED by EMPLOYEE           55.187917
Declaration REJECTED by BUDGET OWNER       Declaration REJECTED by EMPLOYEE            6.370185
Declaration FOR_APPROVAL by ADMINISTRATION Declaration SUBMITTED by EMPLOYEE           1.016481
Declaration REJECTED by ADMINISTRATION     Declaration SUBMITTED by EMPLOYEE           9.925000
                                           Declaration REJECTED by EMPLOYEE           27.162870
Declaration APPROVED by ADMINISTRATION     Declaration REJECTED by SUPERVISOR         18.008634

                                                                                       total_days  \
from_activity                              to_activity
Declaration FINAL_APPROVED by SUPERVISOR   Payment Handled                             571.099907
Request Payment                            Declaration REJECTED by MISSING              56.958461
Declaration SAVED by EMPLOYEE              Request Payment                              17.033345
Declaration REJECTED by SUPERVISOR         Request Payment                               6.922326
Declaration REJECTED by BUDGET OWNER       Declaration SUBMITTED by EMPLOYEE             6.092315
Declaration FOR_APPROVAL by PRE_APPROVER   Declaration REJECTED by MISSING               4.132477
Declaration APPROVED by BUDGET OWNER       Declaration REJECTED by SUPERVISOR          134.048322
Request Payment                            Payment Handled                           35878.189363
Declaration FINAL_APPROVED by SUPERVISOR   Declaration REJECTED by MISSING             948.523356
Declaration APPROVED by PRE_APPROVER       Declaration REJECTED by SUPERVISOR           32.986424
Declaration REJECTED by SUPERVISOR         Declaration SUBMITTED by EMPLOYEE             3.829248
Declaration APPROVED by BUDGET OWNER       Declaration FINAL_APPROVED by SUPERVISOR   7985.128530
Payment Handled                            Declaration REJECTED by EMPLOYEE              1.625278
Declaration FINAL_APPROVED by SUPERVISOR   Request Payment                           31749.310370
Declaration REJECTED by SUPERVISOR         Declaration REJECTED by EMPLOYEE           1053.273877
Declaration REJECTED by BUDGET OWNER       Declaration REJECTED by EMPLOYEE            123.831181
Declaration FOR_APPROVAL by ADMINISTRATION Declaration SUBMITTED by EMPLOYEE             1.016481
Declaration REJECTED by ADMINISTRATION     Declaration SUBMITTED by EMPLOYEE            42.063414
                                           Declaration REJECTED by EMPLOYEE           1896.584826
Declaration APPROVED by ADMINISTRATION     Declaration REJECTED by SUPERVISOR          416.415937

                                                                                     case_share
from_activity                              to_activity
Declaration FINAL_APPROVED by SUPERVISOR   Payment Handled                             0.000667
Request Payment                            Declaration REJECTED by MISSING             0.000286
Declaration SAVED by EMPLOYEE              Request Payment                             0.000095
Declaration REJECTED by SUPERVISOR         Request Payment                             0.000095
Declaration REJECTED by BUDGET OWNER       Declaration SUBMITTED by EMPLOYEE           0.000095
Declaration FOR_APPROVAL by PRE_APPROVER   Declaration REJECTED by MISSING             0.000095
Declaration APPROVED by BUDGET OWNER       Declaration REJECTED by SUPERVISOR          0.003048
Request Payment                            Payment Handled                             0.955905
Declaration FINAL_APPROVED by SUPERVISOR   Declaration REJECTED by MISSING             0.007810
Declaration APPROVED by PRE_APPROVER       Declaration REJECTED by SUPERVISOR          0.001048
Declaration REJECTED by SUPERVISOR         Declaration SUBMITTED by EMPLOYEE           0.000190
Declaration APPROVED by BUDGET OWNER       Declaration FINAL_APPROVED by SUPERVISOR    0.265524
Payment Handled                            Declaration REJECTED by EMPLOYEE            0.000095
Declaration FINAL_APPROVED by SUPERVISOR   Request Payment                             0.956000
Declaration REJECTED by SUPERVISOR         Declaration REJECTED by EMPLOYEE            0.026095
Declaration REJECTED by BUDGET OWNER       Declaration REJECTED by EMPLOYEE            0.005429
Declaration FOR_APPROVAL by ADMINISTRATION Declaration SUBMITTED by EMPLOYEE           0.000095
Declaration REJECTED by ADMINISTRATION     Declaration SUBMITTED by EMPLOYEE           0.001333
                                           Declaration REJECTED by EMPLOYEE            0.079714
Declaration APPROVED by ADMINISTRATION     Declaration REJECTED by SUPERVISOR          0.017714

,,occurrences,cases,mean_days,median_days,p90_days,max_days,total_days,case_share
from_activity,to_activity,,,,,,,,
Request Payment,Payment Handled,10037,10037,3.574593,3.240475,4.912648,62.145127,35878.189363,0.955905
Declaration FINAL_APPROVED by SUPERVISOR,Request Payment,10038,10038,3.162912,1.142836,6.974372,234.680012,31749.310370,0.956000
Declaration APPROVED by ADMINISTRATION,Declaration FINAL_APPROVED by SUPERVISOR,5133,5133,1.902123,0.869850,4.767502,49.923634,9763.595405,0.488857
Declaration SUBMITTED by EMPLOYEE,Declaration APPROVED by ADMINISTRATION,8202,7983,1.155718,0.000428,0.016400,282.582558,9479.195347,0.760286
Declaration APPROVED by BUDGET OWNER,Declaration FINAL_APPROVED by SUPERVISOR,2788,2788,2.864106,1.909751,6.720473,11.852593,7985.128530,0.265524
Declaration REJECTED by EMPLOYEE,Declaration SUBMITTED by EMPLOYEE,1081,961,5.178999,0.202211,11.066655,356.922269,5598.498032,0.091524
Declaration SUBMITTED by EMPLOYEE,Declaration REJECTED by ADMINISTRATION,952,846,5.662438,0.001105,1.694793,469.236319,5390.641192,0.080571
Declaration APPROVED by ADMINISTRATION,Declaration APPROVED by BUDGET OWNER,2820,2807,1.897848,0.865469,4.859507,49.929745,5351.930787,0.267333
Declaration REJECTED by ADMINISTRATION,Declaration REJECTED by EMPLOYEE,928,837,2.043734,0.922176,5.040957,27.162870,1896.584826,0.079714
Declaration SUBMITTED by EMPLOYEE,Declaration FINAL_APPROVED by SUPERVISOR,1536,1490,0.948301,0.000324,0.015359,144.138669,1456.590961,0.141905
Declaration APPROVED by PRE_APPROVER,Declaration FINAL_APPROVED by SUPERVISOR,674,663,1.888721,0.898767,6.154068,7.212442,1272.997998,0.063143
Declaration REJECTED by SUPERVISOR,Declaration REJECTED by EMPLOYEE,286,274,3.682776,1.048466,9.902436,55.187917,1053.273877,0.026095
Declaration FINAL_APPROVED by SUPERVISOR,Declaration REJECTED by MISSING,86,82,11.029341,3.060185,13.878374,293.360428,948.523356,0.007810
Declaration SUBMITTED by EMPLOYEE,Declaration APPROVED by PRE_APPROVER,685,666,1.241504,0.000289,0.013275,119.067488,850.430567,0.063429
Declaration FINAL_APPROVED by SUPERVISOR,Payment Handled,7,7,81.585701,48.366100,147.397583,284.274653,571.099907,0.000667
Declaration REJECTED by MISSING,Declaration SUBMITTED by EMPLOYEE,61,58,8.559964,0.415718,20.099363,137.048727,522.157778,0.005524
Declaration APPROVED by ADMINISTRATION,Declaration REJECTED by SUPERVISOR,190,186,2.191663,0.918646,4.935568,18.008634,416.415937,0.017714
Declaration SUBMITTED by EMPLOYEE,Declaration REJECTED by PRE_APPROVER,86,81,1.946682,0.000758,3.502297,70.960035,167.414688,0.007714
Declaration APPROVED by BUDGET OWNER,Declaration REJECTED by SUPERVISOR,32,32,4.189010,3.996985,6.836884,6.849745,134.048322,0.003048
Declaration REJECTED by BUDGET OWNER,Declaration REJECTED by EMPLOYEE,58,57,2.135020,1.023432,4.923522,6.370185,123.831181,0.005429

,case:concept:name,from_activity,start,to_activity,end,elapsed_days
720,declaration 100723,Declaration SUBMITTED by EMPLOYEE,2018-01-08 15:24:37+00:00,Declaration REJECTED by ADMINISTRATION,2019-04-22 21:04:55+00:00,469.236319
1977,declaration 101989,Declaration REJECTED by EMPLOYEE,2017-06-20 09:22:05+00:00,Declaration SUBMITTED by EMPLOYEE,2018-06-12 07:30:09+00:00,356.922269
199,declaration 100197,Declaration FINAL_APPROVED by SUPERVISOR,2017-03-21 04:15:02+00:00,Declaration REJECTED by MISSING,2018-01-08 12:54:03+00:00,293.360428
15554,declaration 115669,Declaration FINAL_APPROVED by SUPERVISOR,2018-04-26 09:55:46+00:00,Payment Handled,2019-02-04 16:31:16+00:00,284.274653
26056,declaration 126246,Declaration SUBMITTED by EMPLOYEE,2018-07-01 17:47:14+00:00,Declaration APPROVED by ADMINISTRATION,2019-04-10 07:46:07+00:00,282.582558
54599,declaration 98152,Declaration SUBMITTED by EMPLOYEE,2017-12-04 16:59:49+00:00,Declaration REJECTED by ADMINISTRATION,2018-08-27 17:16:11+00:00,266.011366
2466,declaration 102487,Declaration SUBMITTED by EMPLOYEE,2018-03-09 08:34:28+00:00,Declaration REJECTED by ADMINISTRATION,2018-11-07 18:19:12+00:00,243.406065
55738,declaration 99294,Declaration SUBMITTED by EMPLOYEE,2018-03-09 08:52:30+00:00,Declaration REJECTED by ADMINISTRATION,2018-11-07 18:19:12+00:00,243.393542
52166,declaration 95691,Declaration FINAL_APPROVED by SUPERVISOR,2017-05-15 17:56:22+00:00,Request Payment,2018-01-05 10:15:35+00:00,234.680012
3587,declaration 103613,Declaration SUBMITTED by EMPLOYEE,2018-04-11 13:25:39+00:00,Declaration REJECTED by ADMINISTRATION,2018-11-12 13:27:20+00:00,215.001169
3851,declaration 103881,Declaration SUBMITTED by EMPLOYEE,2018-04-12 18:30:48+00:00,Declaration REJECTED by ADMINISTRATION,2018-11-10 11:59:38+00:00,211.728356
51086,declaration 94604,Declaration FINAL_APPROVED by SUPERVISOR,2017-06-20 17:10:02+00:00,Request Payment,2018-01-05 10:15:35+00:00,198.712187
34333,declaration 134592,Declaration SUBMITTED by EMPLOYEE,2018-11-30 11:45:59+00:00,Declaration APPROVED by ADMINISTRATION,2019-06-12 09:36:41+00:00,193.910208
1924,declaration 101937,Declaration SUBMITTED by EMPLOYEE,2018-02-02 13:58:58+00:00,Declaration REJECTED by ADMINISTRATION,2018-08-14 10:37:40+00:00,192.860208
21225,declaration 121390,Declaration SUBMITTED by EMPLOYEE,2018-05-22 11:55:25+00:00,Declaration REJECTED by ADMINISTRATION,2018-11-29 10:24:12+00:00,190.936655
51574,declaration 95095,Declaration FINAL_APPROVED by SUPERVISOR,2017-06-30 05:03:14+00:00,Request Payment,2018-01-05 10:15:35+00:00,189.216910
48911,declaration 92410,Declaration FINAL_APPROVED by SUPERVISOR,2017-06-20 08:34:20+00:00,Request Payment,2017-12-15 08:36:47+00:00,178.001701
48434,declaration 91931,Declaration SUBMITTED by EMPLOYEE,2017-11-13 09:32:42+00:00,Declaration APPROVED by ADMINISTRATION,2018-05-07 07:34:36+00:00,174.917986
44862,declaration 88320,Declaration FINAL_APPROVED by SUPERVISOR,2017-07-19 05:17:29+00:00,Request Payment,2018-01-05 10:15:35+00:00,170.207014
10120,declaration 110191,Declaration FINAL_APPROVED by SUPERVISOR,2017-07-22 16:40:24+00:00,Declaration REJECTED by MISSING,2018-01-08 13:09:36+00:00,169.853611

international - Engpass-Kandidaten, Zeiten in Tagen

                                                                               occurrences  \
from_activity                            to_activity
Declaration SAVED by EMPLOYEE            End trip                                        2
Declaration FINAL_APPROVED by SUPERVISOR Payment Handled                                 5
End trip                                 Permit APPROVED by PRE_APPROVER                 2
Payment Handled                          End trip                                      121
                                         Start trip                                    415
End trip                                 Permit REJECTED by MISSING                      5
Declaration REJECTED by MISSING          Start trip                                      3
Declaration SAVED by EMPLOYEE            Start trip                                     16
Declaration REJECTED by MISSING          End trip                                        1
Permit FINAL_APPROVED by DIRECTOR        Start trip                                    493
End trip                                 Send Reminder                                 288
Permit FINAL_APPROVED by DIRECTOR        Send Reminder                                   3
Declaration REJECTED by EMPLOYEE         Start trip                                     36
Permit REJECTED by MISSING               Start trip                                      2
Permit FINAL_APPROVED by SUPERVISOR      Declaration APPROVED by PRE_APPROVER            1
Declaration REJECTED by EMPLOYEE         End trip                                       10
Declaration REJECTED by MISSING          Permit REJECTED by MISSING                      2
Permit FINAL_APPROVED by SUPERVISOR      Send Reminder                                 101
                                         Start trip                                   4206
Permit FINAL_APPROVED by DIRECTOR        Declaration SUBMITTED by EMPLOYEE              95

                                                                               cases  \
from_activity                            to_activity
Declaration SAVED by EMPLOYEE            End trip                                  2
Declaration FINAL_APPROVED by SUPERVISOR Payment Handled                           5
End trip                                 Permit APPROVED by PRE_APPROVER           2
Payment Handled                          End trip                                121
                                         Start trip                              415
End trip                                 Permit REJECTED by MISSING                5
Declaration REJECTED by MISSING          Start trip                                3
Declaration SAVED by EMPLOYEE            Start trip                               16
Declaration REJECTED by MISSING          End trip                                  1
Permit FINAL_APPROVED by DIRECTOR        Start trip                              493
End trip                                 Send Reminder                           288
Permit FINAL_APPROVED by DIRECTOR        Send Reminder                             3
Declaration REJECTED by EMPLOYEE         Start trip                               36
Permit REJECTED by MISSING               Start trip                                2
Permit FINAL_APPROVED by SUPERVISOR      Declaration APPROVED by PRE_APPROVER      1
Declaration REJECTED by EMPLOYEE         End trip                                 10
Declaration REJECTED by MISSING          Permit REJECTED by MISSING                2
Permit FINAL_APPROVED by SUPERVISOR      Send Reminder                           101
                                         Start trip                             4206
Permit FINAL_APPROVED by DIRECTOR        Declaration SUBMITTED by EMPLOYEE        95

                                                                                mean_days  \
from_activity                            to_activity
Declaration SAVED by EMPLOYEE            End trip                              139.156852
Declaration FINAL_APPROVED by SUPERVISOR Payment Handled                       127.705264
End trip                                 Permit APPROVED by PRE_APPROVER       129.550735
Payment Handled                          End trip                              123.865694
                                         Start trip                            182.145684
End trip                                 Permit REJECTED by MISSING             68.030852
Declaration REJECTED by MISSING          Start trip                            137.940741
Declaration SAVED by EMPLOYEE            Start trip                            146.831528
Declaration REJECTED by MISSING          End trip                               47.574410
Permit FINAL_APPROVED by DIRECTOR        Start trip                             54.812778
End trip                                 Send Reminder                          44.406476
Permit FINAL_APPROVED by DIRECTOR        Send Reminder                          35.111609
Declaration REJECTED by EMPLOYEE         Start trip                             45.407056
Permit REJECTED by MISSING               Start trip                             35.081846
Permit FINAL_APPROVED by SUPERVISOR      Declaration APPROVED by PRE_APPROVER   34.720914
Declaration REJECTED by EMPLOYEE         End trip                               61.256071
Declaration REJECTED by MISSING          Permit REJECTED by MISSING             34.334780
Permit FINAL_APPROVED by SUPERVISOR      Send Reminder                          25.961504
                                         Start trip                             39.251807
Permit FINAL_APPROVED by DIRECTOR        Declaration SUBMITTED by EMPLOYEE      76.018369

                                                                               median_days  \
from_activity                            to_activity
Declaration SAVED by EMPLOYEE            End trip                               139.156852
Declaration FINAL_APPROVED by SUPERVISOR Payment Handled                        131.438275
End trip                                 Permit APPROVED by PRE_APPROVER        129.550735
Payment Handled                          End trip                                82.228229
                                         Start trip                              77.228275
End trip                                 Permit REJECTED by MISSING              67.425324
Declaration REJECTED by MISSING          Start trip                              64.623356
Declaration SAVED by EMPLOYEE            Start trip                              47.658009
Declaration REJECTED by MISSING          End trip                                47.574410
Permit FINAL_APPROVED by DIRECTOR        Start trip                              43.387627
End trip                                 Send Reminder                           43.250156
Permit FINAL_APPROVED by DIRECTOR        Send Reminder                           36.808090
Declaration REJECTED by EMPLOYEE         Start trip                              35.445486
Permit REJECTED by MISSING               Start trip                              35.081846
Permit FINAL_APPROVED by SUPERVISOR      Declaration APPROVED by PRE_APPROVER    34.720914
Declaration REJECTED by EMPLOYEE         End trip                                34.548478
Declaration REJECTED by MISSING          Permit REJECTED by MISSING              34.334780
Permit FINAL_APPROVED by SUPERVISOR      Send Reminder                           28.939051
                                         Start trip                              27.412442
Permit FINAL_APPROVED by DIRECTOR        Declaration SUBMITTED by EMPLOYEE       26.325266

                                                                                 p90_days  \
from_activity                            to_activity
Declaration SAVED by EMPLOYEE            End trip                              244.163157
Declaration FINAL_APPROVED by SUPERVISOR Payment Handled                       233.723081
End trip                                 Permit APPROVED by PRE_APPROVER       230.331582
Payment Handled                          End trip                              276.311678
                                         Start trip                            417.227836
End trip                                 Permit REJECTED by MISSING            103.032380
Declaration REJECTED by MISSING          Start trip                            250.993671
Declaration SAVED by EMPLOYEE            Start trip                            417.792899
Declaration REJECTED by MISSING          End trip                               47.574410
Permit FINAL_APPROVED by DIRECTOR        Start trip                            115.655826
End trip                                 Send Reminder                          56.250524
Permit FINAL_APPROVED by DIRECTOR        Send Reminder                          47.984488
Declaration REJECTED by EMPLOYEE         Start trip                             90.561464
Permit REJECTED by MISSING               Start trip                             54.667490
Permit FINAL_APPROVED by SUPERVISOR      Declaration APPROVED by PRE_APPROVER   34.720914
Declaration REJECTED by EMPLOYEE         End trip                              133.849648
Declaration REJECTED by MISSING          Permit REJECTED by MISSING             53.173465
Permit FINAL_APPROVED by SUPERVISOR      Send Reminder                          44.419815
                                         Start trip                             90.518148
Permit FINAL_APPROVED by DIRECTOR        Declaration SUBMITTED by EMPLOYEE     262.741435

                                                                                 max_days  \
from_activity                            to_activity
Declaration SAVED by EMPLOYEE            End trip                              270.414734
Declaration FINAL_APPROVED by SUPERVISOR Payment Handled                       273.341840
End trip                                 Permit APPROVED by PRE_APPROVER       255.526794
Payment Handled                          End trip                              660.269410
                                         Start trip                            452.228113
End trip                                 Permit REJECTED by MISSING            115.425579
Declaration REJECTED by MISSING          Start trip                            297.586250
Declaration SAVED by EMPLOYEE            Start trip                            454.363368
Declaration REJECTED by MISSING          End trip                               47.574410
Permit FINAL_APPROVED by DIRECTOR        Start trip                            272.371389
End trip                                 Send Reminder                         139.675729
Permit FINAL_APPROVED by DIRECTOR        Send Reminder                          50.778588
Declaration REJECTED by EMPLOYEE         Start trip                            149.569340
Permit REJECTED by MISSING               Start trip                             59.563900
Permit FINAL_APPROVED by SUPERVISOR      Declaration APPROVED by PRE_APPROVER   34.720914
Declaration REJECTED by EMPLOYEE         End trip                              270.382106
Declaration REJECTED by MISSING          Permit REJECTED by MISSING             57.883137
Permit FINAL_APPROVED by SUPERVISOR      Send Reminder                          55.839919
                                         Start trip                            338.575521
Permit FINAL_APPROVED by DIRECTOR        Declaration SUBMITTED by EMPLOYEE     332.013264

                                                                                  total_days  \
from_activity                            to_activity
Declaration SAVED by EMPLOYEE            End trip                                 278.313704
Declaration FINAL_APPROVED by SUPERVISOR Payment Handled                          638.526319
End trip                                 Permit APPROVED by PRE_APPROVER          259.101470
Payment Handled                          End trip                               14987.748970
                                         Start trip                             75590.458715
End trip                                 Permit REJECTED by MISSING               340.154259
Declaration REJECTED by MISSING          Start trip                               413.822222
Declaration SAVED by EMPLOYEE            Start trip                              2349.304444
Declaration REJECTED by MISSING          End trip                                  47.574410
Permit FINAL_APPROVED by DIRECTOR        Start trip                             27022.699745
End trip                                 Send Reminder                          12789.065116
Permit FINAL_APPROVED by DIRECTOR        Send Reminder                            105.334826
Declaration REJECTED by EMPLOYEE         Start trip                              1634.654016
Permit REJECTED by MISSING               Start trip                                70.163692
Permit FINAL_APPROVED by SUPERVISOR      Declaration APPROVED by PRE_APPROVER      34.720914
Declaration REJECTED by EMPLOYEE         End trip                                 612.560706
Declaration REJECTED by MISSING          Permit REJECTED by MISSING                68.669560
Permit FINAL_APPROVED by SUPERVISOR      Send Reminder                           2622.111887
                                         Start trip                            165093.101204
Permit FINAL_APPROVED by DIRECTOR        Declaration SUBMITTED by EMPLOYEE       7221.745058

                                                                               case_share
from_activity                            to_activity
Declaration SAVED by EMPLOYEE            End trip                                0.000310
Declaration FINAL_APPROVED by SUPERVISOR Payment Handled                         0.000775
End trip                                 Permit APPROVED by PRE_APPROVER         0.000310
Payment Handled                          End trip                                0.018763
                                         Start trip                              0.064351
End trip                                 Permit REJECTED by MISSING              0.000775
Declaration REJECTED by MISSING          Start trip                              0.000465
Declaration SAVED by EMPLOYEE            Start trip                              0.002481
Declaration REJECTED by MISSING          End trip                                0.000155
Permit FINAL_APPROVED by DIRECTOR        Start trip                              0.076446
End trip                                 Send Reminder                           0.044658
Permit FINAL_APPROVED by DIRECTOR        Send Reminder                           0.000465
Declaration REJECTED by EMPLOYEE         Start trip                              0.005582
Permit REJECTED by MISSING               Start trip                              0.000310
Permit FINAL_APPROVED by SUPERVISOR      Declaration APPROVED by PRE_APPROVER    0.000155
Declaration REJECTED by EMPLOYEE         End trip                                0.001551
Declaration REJECTED by MISSING          Permit REJECTED by MISSING              0.000310
Permit FINAL_APPROVED by SUPERVISOR      Send Reminder                           0.015661
                                         Start trip                              0.652194
Permit FINAL_APPROVED by DIRECTOR        Declaration SUBMITTED by EMPLOYEE       0.014731

,,occurrences,cases,mean_days,median_days,p90_days,max_days,total_days,case_share
from_activity,to_activity,,,,,,,,
Permit FINAL_APPROVED by SUPERVISOR,Start trip,4206,4206,39.251807,27.412442,90.518148,338.575521,165093.101204,0.652194
Payment Handled,Start trip,415,415,182.145684,77.228275,417.227836,452.228113,75590.458715,0.064351
End trip,Declaration SUBMITTED by EMPLOYEE,4591,4591,12.698465,5.648299,28.514456,295.891898,58298.653692,0.711893
Start trip,End trip,5784,5784,5.222402,4.000000,9.000000,274.000000,30206.375000,0.896883
Permit FINAL_APPROVED by DIRECTOR,Start trip,493,493,54.812778,43.387627,115.655826,272.371389,27022.699745,0.076446
Request Payment,Payment Handled,6149,6149,3.456923,3.217812,4.917162,31.116354,21256.619039,0.953481
Declaration FINAL_APPROVED by SUPERVISOR,Request Payment,5918,5918,3.207570,1.187025,7.476610,266.099039,18982.401412,0.917662
Payment Handled,End trip,121,121,123.865694,82.228229,276.311678,660.269410,14987.748970,0.018763
End trip,Permit SUBMITTED by EMPLOYEE,492,492,26.301193,9.363414,61.746005,366.472373,12940.186794,0.076291
Permit FINAL_APPROVED by SUPERVISOR,Declaration SUBMITTED by EMPLOYEE,776,776,16.564629,6.204462,36.059855,279.773125,12854.152338,0.120329
End trip,Send Reminder,288,288,44.406476,43.250156,56.250524,139.675729,12789.065116,0.044658
Declaration APPROVED by ADMINISTRATION,Declaration FINAL_APPROVED by SUPERVISOR,2959,2959,2.885552,1.106042,7.207424,57.007269,8538.349132,0.458831
Permit FINAL_APPROVED by DIRECTOR,Declaration SUBMITTED by EMPLOYEE,95,95,76.018369,26.325266,262.741435,332.013264,7221.745058,0.014731
Declaration SUBMITTED by EMPLOYEE,Declaration APPROVED by ADMINISTRATION,4952,4838,1.398018,0.001736,1.010583,422.003970,6922.984850,0.750194
Declaration APPROVED by ADMINISTRATION,Declaration APPROVED by BUDGET OWNER,1815,1798,3.124669,1.081134,7.211153,55.814456,5671.273935,0.278803
Send Reminder,Declaration SUBMITTED by EMPLOYEE,378,378,14.630359,7.845133,34.789369,169.390880,5530.275706,0.058614
Start trip,Permit SUBMITTED by EMPLOYEE,225,225,23.807168,3.400949,74.368414,306.642396,5356.612882,0.034889
Declaration APPROVED by BUDGET OWNER,Declaration FINAL_APPROVED by SUPERVISOR,1746,1746,3.039236,2.003611,6.731007,11.625046,5306.506898,0.270740
Declaration REJECTED by ADMINISTRATION,Declaration REJECTED by EMPLOYEE,1510,1262,3.431175,1.805920,8.768294,53.060926,5181.074838,0.195689
Permit APPROVED by ADMINISTRATION,Permit FINAL_APPROVED by SUPERVISOR,2563,2563,1.916121,0.894757,4.928887,40.926435,4911.017292,0.397426

,case:concept:name,from_activity,start,to_activity,end,elapsed_days
47684,declaration 61184,Payment Handled,2018-07-19 15:32:03+00:00,End trip,2020-05-09 22:00:00+00:00,660.269410
3630,declaration 143612,Declaration SAVED by EMPLOYEE,2017-01-10 13:16:45+00:00,Start trip,2018-04-09 22:00:00+00:00,454.363368
3589,declaration 143578,Payment Handled,2017-01-12 16:31:31+00:00,Start trip,2018-04-09 22:00:00+00:00,452.228113
3621,declaration 143598,Payment Handled,2017-01-16 16:32:18+00:00,Start trip,2018-04-09 22:00:00+00:00,448.227569
3654,declaration 143637,Payment Handled,2017-01-16 16:32:18+00:00,Start trip,2018-04-09 22:00:00+00:00,448.227569
3636,declaration 143617,Payment Handled,2017-01-19 16:31:50+00:00,Start trip,2018-04-09 22:00:00+00:00,445.227894
3684,declaration 143670,Payment Handled,2017-01-19 16:31:50+00:00,Start trip,2018-04-09 22:00:00+00:00,445.227894
3642,declaration 143624,Payment Handled,2017-01-23 16:32:17+00:00,Start trip,2018-04-09 22:00:00+00:00,441.227581
3481,declaration 143467,Payment Handled,2017-01-23 16:32:17+00:00,Start trip,2018-04-09 22:00:00+00:00,441.227581
3497,declaration 143474,Payment Handled,2017-01-23 16:32:17+00:00,Start trip,2018-04-09 22:00:00+00:00,441.227581
3525,declaration 143502,Payment Handled,2017-01-26 16:30:47+00:00,Start trip,2018-04-09 22:00:00+00:00,438.228623
3672,declaration 143657,Payment Handled,2017-01-26 16:30:47+00:00,Start trip,2018-04-09 22:00:00+00:00,438.228623
3666,declaration 143644,Payment Handled,2017-01-26 16:30:47+00:00,Start trip,2018-04-09 22:00:00+00:00,438.228623
3615,declaration 143585,Payment Handled,2017-01-26 16:30:47+00:00,Start trip,2018-04-09 22:00:00+00:00,438.228623
3503,declaration 143481,Payment Handled,2017-01-30 16:31:40+00:00,Start trip,2018-04-09 22:00:00+00:00,434.228009
3555,declaration 143539,Payment Handled,2017-01-30 16:31:40+00:00,Start trip,2018-04-09 22:00:00+00:00,434.228009
3531,declaration 143513,Payment Handled,2017-01-30 16:31:40+00:00,Start trip,2018-04-09 22:00:00+00:00,434.228009
3515,declaration 143496,Payment Handled,2017-01-30 16:31:40+00:00,Start trip,2018-04-09 22:00:00+00:00,434.228009
3509,declaration 143488,Payment Handled,2017-01-30 16:31:40+00:00,Start trip,2018-04-09 22:00:00+00:00,434.228009
3549,declaration 143532,Payment Handled,2017-01-30 16:31:40+00:00,Start trip,2018-04-09 22:00:00+00:00,434.228009

Aufgabe 4

In [20]:
# Frage 4: Declaration-Ablehnungen; Permit-Entscheidungen werden nicht mitgezaehlt.
# Bezugsgroesse: Traces mit Declaration-Events, nicht Zahl der REJECTED-Events.
# Ein REJECTED-Event ist keine endgueltige Ablehnung. Spaetere Freigaben separat.
# Bei gleichen Zeitstempeln gilt fuer die Entscheidungsfolge die stabile Logreihenfolge.
# Ablehnende Aktivitaet/Rolle und Budgetgruppen liefern Hinweise, keine Ursachen.
rejection_results = {}
for name, log in analysis_logs.items():
    rejection_results[name] = rejection_analysis(log, group_by="case:BudgetNumber")
    print(name)
    display(rejection_results[name]["summary"])
    display(rejection_results[name]["by_activity"])
    display(rejection_results[name]["by_group"].head(20))
    cases = rejection_results[name]["cases"]
    display(cases.loc[cases["rejected"]].head(20))
# Zelle 3 (field_summary) zeigt kein explizites Ablehnungsgrund-Feld.
# Auch last_entity_event_rejected bedeutet nur letzter beobachteter Declaration-Status.

domestic

,cases,rejection_events,rejected_cases,rejected_share,final_approval_after_last_rejection,last_entity_event_rejected
entity,,,,,,
Declaration,10500,2846,1301,0.123905,978,323

,rejection_events,rejected_cases,case_share
concept:name,,,
Declaration REJECTED by ADMINISTRATION,952,846,0.080571
Declaration REJECTED by BUDGET OWNER,59,58,0.005524
Declaration REJECTED by EMPLOYEE,1365,1212,0.115429
Declaration REJECTED by MISSING,91,87,0.008286
Declaration REJECTED by PRE_APPROVER,86,81,0.007714
Declaration REJECTED by SUPERVISOR,293,281,0.026762

                   cases  rejected_cases  rejected_share
case:BudgetNumber
budget 86566       10500            1301        0.123905

,rejection_events,last_entity_activity,rejected,final_approval_after_last_rejection,last_entity_event_rejected,case:BudgetNumber
case:concept:name,,,,,,
declaration 100122,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 86566
declaration 100197,1,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 86566
declaration 100245,4,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 86566
declaration 100365,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 86566
declaration 100380,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 86566
declaration 100399,4,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 86566
declaration 100433,4,Declaration REJECTED by EMPLOYEE,True,False,True,budget 86566
declaration 100512,2,Declaration REJECTED by EMPLOYEE,True,False,True,budget 86566
declaration 100543,2,Declaration REJECTED by EMPLOYEE,True,False,True,budget 86566
declaration 100553,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 86566
declaration 100708,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 86566
declaration 100723,1,Declaration REJECTED by ADMINISTRATION,True,False,True,budget 86566
declaration 100764,2,Declaration REJECTED by EMPLOYEE,True,False,True,budget 86566
declaration 100816,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 86566
declaration 100919,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 86566
declaration 100928,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 86566
declaration 100941,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 86566
declaration 100971,6,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 86566
declaration 101070,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 86566
declaration 101084,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 86566

international

,cases,rejection_events,rejected_cases,rejected_share,final_approval_after_last_rejection,last_entity_event_rejected
entity,,,,,,
Declaration,6449,3686,1576,0.244379,1389,186

,rejection_events,rejected_cases,case_share
concept:name,,,
Declaration REJECTED by ADMINISTRATION,1549,1287,0.199566
Declaration REJECTED by BUDGET OWNER,40,40,0.006203
Declaration REJECTED by DIRECTOR,4,4,0.000620
Declaration REJECTED by EMPLOYEE,1780,1483,0.229958
Declaration REJECTED by MISSING,103,98,0.015196
Declaration REJECTED by PRE_APPROVER,84,82,0.012715
Declaration REJECTED by SUPERVISOR,126,122,0.018918

                   cases  rejected_cases  rejected_share
case:BudgetNumber
budget 146697         58              15        0.258621
budget 146776         56              14        0.250000
budget 146681         54              14        0.259259
budget 146666         53              18        0.339623
budget 145339         49               2        0.040816
budget 146757         42              12        0.285714
budget 146663         42              16        0.380952
budget 146690         42              18        0.428571
budget 146682         38              13        0.342105
budget 146824         37              12        0.324324
budget 146794         37              12        0.324324
budget 146856         36              15        0.416667
budget 146665         33               8        0.242424
budget 146817         33               9        0.272727
budget 147110         33               9        0.272727
budget 147065         32              10        0.312500
budget 146808         31               7        0.225806
budget 146730         31              13        0.419355
budget 145389         31               7        0.225806
budget 146692         31               8        0.258065

,rejection_events,last_entity_activity,rejected,final_approval_after_last_rejection,last_entity_event_rejected,case:BudgetNumber
case:concept:name,,,,,,
declaration 10089,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 146762
declaration 10168,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 146817
declaration 10240,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 147421
declaration 10265,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 147063
declaration 10279,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 146755
declaration 10324,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 147423
declaration 10495,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 146850
declaration 10522,4,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 146668
declaration 10552,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 146681
declaration 1056,4,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 146663
declaration 10603,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 146756
declaration 10718,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 147424
declaration 10720,2,Declaration REJECTED by EMPLOYEE,True,False,True,budget 147424
declaration 10721,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 147424
declaration 10797,6,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 146856
declaration 10818,2,Declaration REJECTED by EMPLOYEE,True,False,True,budget 146794
declaration 10886,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 147388
declaration 10939,2,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 146670
declaration 10961,8,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 146681
declaration 11025,4,Declaration FINAL_APPROVED by SUPERVISOR,True,True,False,budget 146663

Aufgabe 5

In [21]:
# Frage 5: bereits analysiert in Zelle 6 (#Permit Dummy Analyse):
# 448 internationale Traces ohne Permit-Event; exakt dieselben 448 haben
# abweichende case:Permit id / case:Permit ID. Kein Beweis fehlender realer Genehmigung.
# Zelle 5 (unique_analysis der Betraege): nur declaration 54434 weicht ab;
# AdjustedAmount = 100.494292, die drei anderen verglichenen Betragsfelder = 0.
# Ergaenzung: explizite Pruefhypothese, fachlich noch zu bestaetigen:
# Vor dem ersten Start trip muss eine finale Permit-Freigabe beobachtet worden sein.
permit_rules = {
    "Finale Permit-Freigabe vor Reisebeginn": (
        {"Permit FINAL_APPROVED by DIRECTOR", "Permit FINAL_APPROVED by SUPERVISOR"},
        {"Start trip"},
    ),
}
unexpected_results = unexpected_behavior(int_log_base, rules=permit_rules)
display(unexpected_results["summary"])
display(unexpected_results["cases"].query("status not in ['ok', 'no_trigger']").head(30))
# Gleiche Zeitstempel sind unklar; Faelle ohne Start trip sind nicht bewertbar.
# Nur das vollstaendige internationale Log verwenden, keine Events herausfiltern.

,cases,eligible_cases,violations,violation_share,missing_required,required_after_trigger,same_timestamp,no_trigger
Finale Permit-Freigabe vor Reisebeginn,6449,6449,1578,0.244689,448,1130,0,0

,case:concept:name,required_time,trigger_time,status,rule
4,declaration 10069,2018-02-22 07:27:05+00:00,2018-02-21 23:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
10,declaration 10151,2018-02-26 14:09:04+00:00,2018-02-18 23:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
11,declaration 10168,2018-09-06 07:51:39+00:00,2018-08-25 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
18,declaration 10279,2018-09-18 03:15:13+00:00,2018-08-19 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
29,declaration 10472,2018-06-19 08:56:26+00:00,2018-06-17 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
33,declaration 10552,2018-07-17 03:15:12+00:00,2018-07-07 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
35,declaration 10578,2018-06-18 08:58:33+00:00,2018-06-10 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
40,declaration 10638,2018-06-26 05:26:44+00:00,2018-06-12 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
50,declaration 10743,2018-09-25 07:09:50+00:00,2018-09-13 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
54,declaration 1079,2018-03-13 04:15:17+00:00,2018-03-07 23:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
56,declaration 1081,2018-03-13 04:15:17+00:00,2018-03-07 23:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
57,declaration 10816,2018-09-24 09:05:31+00:00,2018-09-15 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
58,declaration 10818,2018-09-24 09:05:31+00:00,2018-09-15 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
61,declaration 10862,2018-09-18 12:07:22+00:00,2018-09-17 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
69,declaration 10986,2018-06-26 07:50:39+00:00,2018-06-15 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
73,declaration 11025,2018-07-03 14:55:27+00:00,2018-06-23 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
80,declaration 11149,2018-07-03 06:34:32+00:00,2018-06-16 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
81,declaration 1116,2018-03-05 08:39:29+00:00,2017-07-15 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
83,declaration 11177,2018-10-03 08:02:11+00:00,2018-09-04 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
86,declaration 11239,2018-10-17 13:31:43+00:00,2018-10-06 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
91,declaration 11293,2018-11-09 15:01:31+00:00,2018-11-05 23:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
100,declaration 11436,2018-07-12 10:28:56+00:00,2018-07-10 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
104,declaration 11492,2018-07-14 15:22:55+00:00,2018-07-07 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
105,declaration 11524,2018-07-09 08:10:32+00:00,2018-07-01 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
106,declaration 11537,2018-07-09 08:08:19+00:00,2018-07-06 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
108,declaration 11558,2018-07-13 09:08:11+00:00,2018-06-30 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
111,declaration 11595,2018-07-12 07:44:08+00:00,2018-06-29 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
112,declaration 11596,2018-07-12 07:44:08+00:00,2018-06-29 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
118,declaration 11695,2018-07-25 07:38:58+00:00,2018-07-12 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn
120,declaration 11706,2018-08-16 08:27:52+00:00,2018-07-17 22:00:00+00:00,required_after_trigger,Finale Permit-Freigabe vor Reisebeginn

Aufgabe 6

In [22]:
# Frage 6: Zellen 13/14 enthalten bereits globale Modellkennzahlen.
# Hier zusaetzlich konkrete Fall-Diagnosen und haeufige nicht passende Varianten.
# Beispielauswahl, keine automatische Bestmodell-Auswahl; in Zelle 13 vorhanden.
conformance_miner = "heuristicpn"
conformance_results = {}
for name, log in analysis_logs.items():
    reference_model = models[(name, conformance_miner)]
    conformance_results[name] = conformance_analysis(log, model=reference_model)
    print(name, '- Referenzmodell:', conformance_miner)
    display(conformance_results[name]["summary"])
    patterns = conformance_results[name]["patterns"]
    display(patterns.loc[patterns["non_fitting_cases"].gt(0)].head(20))
    cases = conformance_results[name]["cases"]
    display(cases.loc[~cases["trace_is_fit"]].head(20))
# Modelle wurden aus denselben Logs entdeckt: keine unabhaengige Compliance-Pruefung.
# Ein fachliches Sollmodell kann stattdessen direkt als model uebergeben werden.
# Token-Fitness allein kann unbekannte Aktivitaeten uebersehen; diese stehen separat im Ergebnis.

domestic - Referenzmodell: heuristicpn

,cases,fitting_cases,non_fitting_cases,fitting_share,mean_fitness,cases_with_unknown_activities
0,10500,3714,6786,0.353714,0.918933,0

,cases,fitting_cases,mean_fitness,missing_tokens,remaining_tokens,non_fitting_cases,non_fitting_share
variant,,,,,,,
"(Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",4618,0,0.875000,4618,4618,4618,1.0
"(Declaration SUBMITTED by EMPLOYEE, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",1392,0,0.857143,1392,1392,1392,1.0
"(Declaration SUBMITTED by EMPLOYEE, Declaration REJECTED by ADMINISTRATION, Declaration REJECTED by EMPLOYEE, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",345,0,0.923077,345,345,345,1.0
"(Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration REJECTED by SUPERVISOR, Declaration REJECTED by EMPLOYEE, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",77,0,0.866667,154,154,77,1.0
"(Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration REJECTED by SUPERVISOR, Declaration REJECTED by EMPLOYEE, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration APPROVED by BUDGET OWNER, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",49,0,0.941176,49,49,49,1.0
"(Declaration SUBMITTED by EMPLOYEE, Declaration FINAL_APPROVED by SUPERVISOR, Declaration REJECTED by MISSING, Declaration SUBMITTED by EMPLOYEE, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",40,0,0.833333,80,80,40,1.0
"(Declaration SUBMITTED by EMPLOYEE, Declaration REJECTED by ADMINISTRATION, Declaration REJECTED by EMPLOYEE, Declaration SUBMITTED by EMPLOYEE, Declaration REJECTED by ADMINISTRATION, Declaration REJECTED by EMPLOYEE, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",36,0,0.944444,36,36,36,1.0
"(Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration REJECTED by SUPERVISOR, Declaration REJECTED by EMPLOYEE)",31,0,0.888889,31,31,31,1.0
"(Declaration SUBMITTED by EMPLOYEE, Declaration REJECTED by SUPERVISOR, Declaration REJECTED by EMPLOYEE, Declaration SUBMITTED by EMPLOYEE, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",22,0,0.833333,44,44,22,1.0
"(Declaration SUBMITTED by EMPLOYEE, Declaration FINAL_APPROVED by SUPERVISOR, Declaration REJECTED by MISSING)",21,0,0.857143,21,21,21,1.0
"(Declaration SUBMITTED by EMPLOYEE, Declaration REJECTED by SUPERVISOR, Declaration REJECTED by EMPLOYEE)",18,0,0.857143,18,18,18,1.0
"(Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration REJECTED by BUDGET OWNER, Declaration REJECTED by EMPLOYEE, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",14,0,0.923077,14,14,14,1.0
"(Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration APPROVED by BUDGET OWNER, Declaration REJECTED by SUPERVISOR, Declaration REJECTED by EMPLOYEE, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration APPROVED by BUDGET OWNER, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",10,0,0.941176,10,10,10,1.0
"(Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by PRE_APPROVER, Declaration REJECTED by SUPERVISOR, Declaration REJECTED by EMPLOYEE, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by PRE_APPROVER, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",8,0,0.928571,8,8,8,1.0
"(Declaration SUBMITTED by EMPLOYEE, Declaration REJECTED by SUPERVISOR, Declaration REJECTED by EMPLOYEE, Declaration SUBMITTED by EMPLOYEE, Declaration REJECTED by SUPERVISOR, Declaration REJECTED by EMPLOYEE)",6,0,0.833333,12,12,6,1.0
"(Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration APPROVED by BUDGET OWNER, Declaration REJECTED by SUPERVISOR, Declaration REJECTED by EMPLOYEE, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",6,0,0.937500,6,6,6,1.0
"(Declaration SUBMITTED by EMPLOYEE, Declaration REJECTED by ADMINISTRATION, Declaration REJECTED by EMPLOYEE, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration REJECTED by SUPERVISOR, Declaration REJECTED by EMPLOYEE, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",6,0,0.900000,12,12,6,1.0
"(Declaration SUBMITTED by EMPLOYEE, Declaration REJECTED by ADMINISTRATION, Declaration REJECTED by EMPLOYEE, Declaration SUBMITTED by EMPLOYEE, Declaration REJECTED by ADMINISTRATION, Declaration REJECTED by EMPLOYEE, Declaration SUBMITTED by EMPLOYEE, Declaration REJECTED by ADMINISTRATION, Declaration REJECTED by EMPLOYEE, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",4,0,0.956522,4,4,4,1.0
"(Declaration SUBMITTED by EMPLOYEE, Declaration REJECTED by PRE_APPROVER, Declaration REJECTED by EMPLOYEE, Declaration SUBMITTED by EMPLOYEE, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",4,0,0.909091,4,4,4,1.0
"(Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration FINAL_APPROVED by SUPERVISOR, Payment Handled)",4,0,0.666667,8,8,4,1.0

,trace_is_fit,trace_fitness,missing_tokens,remaining_tokens,consumed_tokens,produced_tokens,unknown_activities,variant
case:concept:name,,,,,,,,
declaration 100000,False,0.875,1,1,8,8,(),"(Declaration SUBMITTED by EMPLOYEE, Declaratio..."
declaration 100005,False,0.875,1,1,8,8,(),"(Declaration SUBMITTED by EMPLOYEE, Declaratio..."
declaration 100010,False,0.875,1,1,8,8,(),"(Declaration SUBMITTED by EMPLOYEE, Declaratio..."
declaration 100027,False,0.875,1,1,8,8,(),"(Declaration SUBMITTED by EMPLOYEE, Declaratio..."
declaration 100032,False,0.875,1,1,8,8,(),"(Declaration SUBMITTED by EMPLOYEE, Declaratio..."
declaration 100037,False,0.875,1,1,8,8,(),"(Declaration SUBMITTED by EMPLOYEE, Declaratio..."
declaration 100048,False,0.875,1,1,8,8,(),"(Declaration SUBMITTED by EMPLOYEE, Declaratio..."
declaration 100059,False,0.875,1,1,8,8,(),"(Declaration SUBMITTED by EMPLOYEE, Declaratio..."
declaration 100064,False,0.875,1,1,8,8,(),"(Declaration SUBMITTED by EMPLOYEE, Declaratio..."
declaration 100069,False,0.875,1,1,8,8,(),"(Declaration SUBMITTED by EMPLOYEE, Declaratio..."
declaration 100074,False,0.875,1,1,8,8,(),"(Declaration SUBMITTED by EMPLOYEE, Declaratio..."
declaration 100085,False,0.875,1,1,8,8,(),"(Declaration SUBMITTED by EMPLOYEE, Declaratio..."
declaration 100090,False,0.875,1,1,8,8,(),"(Declaration SUBMITTED by EMPLOYEE, Declaratio..."
declaration 100095,False,0.875,1,1,8,8,(),"(Declaration SUBMITTED by EMPLOYEE, Declaratio..."
declaration 100100,False,0.875,1,1,8,8,(),"(Declaration SUBMITTED by EMPLOYEE, Declaratio..."
declaration 100111,False,0.875,1,1,8,8,(),"(Declaration SUBMITTED by EMPLOYEE, Declaratio..."
declaration 100149,False,0.875,1,1,8,8,(),"(Declaration SUBMITTED by EMPLOYEE, Declaratio..."
declaration 100172,False,0.875,1,1,8,8,(),"(Declaration SUBMITTED by EMPLOYEE, Declaratio..."
declaration 100177,False,0.875,1,1,8,8,(),"(Declaration SUBMITTED by EMPLOYEE, Declaratio..."
declaration 100182,False,0.875,1,1,8,8,(),"(Declaration SUBMITTED by EMPLOYEE, Declaratio..."

international - Referenzmodell: heuristicpn

,cases,fitting_cases,non_fitting_cases,fitting_share,mean_fitness,cases_with_unknown_activities
0,6449,354,6095,0.054892,0.896192,0

,cases,fitting_cases,mean_fitness,missing_tokens,remaining_tokens,non_fitting_cases,non_fitting_share
variant,,,,,,,
"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED by ADMINISTRATION, Permit FINAL_APPROVED by SUPERVISOR, Start trip, End trip, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",1369,0,0.878571,2738,4107,1369,1.0
"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED by ADMINISTRATION, Permit APPROVED by BUDGET OWNER, Permit FINAL_APPROVED by SUPERVISOR, Start trip, End trip, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration APPROVED by BUDGET OWNER, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",624,0,0.979167,0,624,624,1.0
"(Permit SUBMITTED by EMPLOYEE, Permit FINAL_APPROVED by SUPERVISOR, Start trip, End trip, Declaration SUBMITTED by EMPLOYEE, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",361,0,0.882353,722,722,361,1.0
"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED by ADMINISTRATION, Permit FINAL_APPROVED by SUPERVISOR, Start trip, End trip, Declaration SUBMITTED by EMPLOYEE, Declaration REJECTED by ADMINISTRATION, Declaration REJECTED by EMPLOYEE, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",311,0,0.898333,622,933,311,1.0
"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED by ADMINISTRATION, Permit APPROVED by BUDGET OWNER, Permit FINAL_APPROVED by SUPERVISOR, Start trip, End trip, Declaration SUBMITTED by EMPLOYEE, Declaration REJECTED by ADMINISTRATION, Declaration REJECTED by EMPLOYEE, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration APPROVED by BUDGET OWNER, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",188,0,0.982143,0,188,188,1.0
"(Start trip, End trip, Permit SUBMITTED by EMPLOYEE, Permit APPROVED by ADMINISTRATION, Permit FINAL_APPROVED by SUPERVISOR, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",157,0,0.791667,471,785,157,1.0
"(Declaration SUBMITTED by EMPLOYEE, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled, Start trip, End trip)",111,0,0.833333,222,222,111,1.0
"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED by ADMINISTRATION, Permit FINAL_APPROVED by SUPERVISOR, Start trip, End trip, Send Reminder, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",94,0,0.826087,376,376,94,1.0
"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED by ADMINISTRATION, Permit APPROVED by SUPERVISOR, Permit FINAL_APPROVED by DIRECTOR, Start trip, End trip, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",85,0,0.878571,170,255,85,1.0
"(Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled, Start trip, End trip)",79,0,0.846154,158,158,79,1.0
"(Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration APPROVED by BUDGET OWNER, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled, Start trip, End trip)",75,0,0.933333,75,75,75,1.0
"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED by ADMINISTRATION, Start trip, Permit FINAL_APPROVED by SUPERVISOR, End trip, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",73,0,0.829762,219,292,73,1.0
"(Start trip, End trip, Permit SUBMITTED by EMPLOYEE, Permit APPROVED by ADMINISTRATION, Permit APPROVED by BUDGET OWNER, Permit FINAL_APPROVED by SUPERVISOR, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration APPROVED by BUDGET OWNER, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",62,0,0.910973,62,186,62,1.0
"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED by ADMINISTRATION, Permit APPROVED by BUDGET OWNER, Permit APPROVED by SUPERVISOR, Permit FINAL_APPROVED by DIRECTOR, Start trip, End trip, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration APPROVED by BUDGET OWNER, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",62,0,0.933794,62,124,62,1.0
"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED by ADMINISTRATION, Permit FINAL_APPROVED by SUPERVISOR, Start trip, End trip, Declaration SUBMITTED by EMPLOYEE, Declaration REJECTED by ADMINISTRATION, Declaration REJECTED by EMPLOYEE, Declaration SUBMITTED by EMPLOYEE, Declaration REJECTED by ADMINISTRATION, Declaration REJECTED by EMPLOYEE, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",50,0,0.912562,100,150,50,1.0
"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED by ADMINISTRATION, Permit FINAL_APPROVED by SUPERVISOR, Start trip, End trip, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration APPROVED by BUDGET OWNER, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",46,0,0.933794,46,92,46,1.0
"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED by SUPERVISOR, Permit FINAL_APPROVED by DIRECTOR, Start trip, End trip, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by SUPERVISOR, Declaration FINAL_APPROVED by DIRECTOR, Request Payment, Payment Handled)",45,0,0.865497,90,135,45,1.0
"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED by ADMINISTRATION, Permit APPROVED by BUDGET OWNER, Permit FINAL_APPROVED by SUPERVISOR, Start trip, End trip, Send Reminder, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration APPROVED by BUDGET OWNER, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",42,0,0.923077,84,84,42,1.0
"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED by ADMINISTRATION, Permit FINAL_APPROVED by SUPERVISOR, Start trip, End trip, Declaration SUBMITTED by EMPLOYEE, Declaration REJECTED by ADMINISTRATION, Declaration REJECTED by EMPLOYEE)",41,0,0.909926,41,82,41,1.0
"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED by ADMINISTRATION, Start trip, End trip, Permit FINAL_APPROVED by SUPERVISOR, Declaration SUBMITTED by EMPLOYEE, Declaration APPROVED by ADMINISTRATION, Declaration FINAL_APPROVED by SUPERVISOR, Request Payment, Payment Handled)",40,0,0.743464,160,200,40,1.0

,trace_is_fit,trace_fitness,missing_tokens,remaining_tokens,consumed_tokens,produced_tokens,unknown_activities,variant
case:concept:name,,,,,,,,
declaration 1002,False,0.878571,2,3,20,21,(),"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED..."
declaration 10024,False,0.979167,0,1,23,24,(),"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED..."
declaration 10026,False,0.979167,0,1,23,24,(),"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED..."
declaration 10046,False,0.878571,2,3,20,21,(),"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED..."
declaration 10069,False,0.743464,4,5,17,18,(),"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED..."
declaration 10079,False,0.878571,2,3,20,21,(),"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED..."
declaration 10089,False,0.851449,3,4,23,24,(),"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED..."
declaration 10106,False,0.923077,2,2,26,26,(),"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED..."
declaration 10128,False,0.878571,2,3,20,21,(),"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED..."
declaration 10138,False,0.979167,0,1,23,24,(),"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED..."
declaration 10151,False,0.791667,3,5,18,20,(),"(Start trip, End trip, Permit SUBMITTED by EMP..."
declaration 10168,False,0.924444,1,3,25,27,(),"(Start trip, End trip, Permit SUBMITTED by EMP..."
declaration 10184,False,0.979167,0,1,23,24,(),"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED..."
declaration 10207,False,0.878571,2,3,20,21,(),"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED..."
declaration 10217,False,0.979167,0,1,23,24,(),"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED..."
declaration 10238,False,0.878571,2,3,20,21,(),"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED..."
declaration 10240,False,0.898333,2,3,24,25,(),"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED..."
declaration 10265,False,0.898333,2,3,24,25,(),"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED..."
declaration 10279,False,0.927198,1,3,26,28,(),"(Start trip, End trip, Permit SUBMITTED by EMP..."
declaration 1029,False,0.878571,2,3,20,21,(),"(Permit SUBMITTED by EMPLOYEE, Permit APPROVED..."

Aufgabe 7

In [23]:
# Frage 7: bereits vorhanden: Zelle 10 (Aktivitaetsanteile), 11 (Varianten),
# 12 (Start/Ende) und 18 (Declaration-Varianten). Zelle 11 zeigt in den gespeicherten
# Ergebnissen 99 domestic- gegen 753 international-Ablaeufe im vollen Log.
# Das allein ist kein fairer Komplexitaetsvergleich: international enthaelt auch Permits/Trips.
# Ergaenzung: Zeit-, Ablehnungs- und Strukturkennzahlen fuer beide Ausgangslogs;
# Declaration-Spannen und volle Trace-Dauern werden getrennt ausgewiesen.
declaration_comparison = compare_declarations(dom_log_base, int_log_base)
for label, result in declaration_comparison.items():
    print(label)
    display(result)
# Anteile sind Zahlen zwischen 0 und 1; Differenzen * 100 ergeben Prozentpunkte.
# Declaration-Spannen enden am letzten Declaration-Event, nicht zwingend an der Zahlung.
# Deskriptive Unterschiede, kein Signifikanz- oder Kausalitaetsnachweis.

overview

                                                    domestic  international
all_cases                                       10500.000000    6449.000000
declaration_cases                               10500.000000    6449.000000
cases_without_declaration                           0.000000       0.000000
full_median_days                                    7.330289      66.041667
full_p90_days                                      20.120839     159.185472
declaration_median_days                             1.545972       3.645949
declaration_p90_days                                9.617816      17.795139
declaration_mean_events                             3.462190       4.014576
declaration_variants                               94.000000     111.000000
most_common_variant_share                           0.440190       0.358970
cases_with_repeated_declaration_activity_share      0.097048       0.217863
rejected_cases                                   1301.000000    1576.000000
rejected_share                                      0.123905       0.244379

declaration_activity_shares

,domestic,international,international_minus_domestic
concept:name,,,
Declaration APPROVED by ADMINISTRATION,0.760286,0.762754,0.002468
Declaration APPROVED by BUDGET OWNER,0.267333,0.281749,0.014416
Declaration APPROVED by PRE_APPROVER,0.063429,0.086525,0.023096
Declaration APPROVED by SUPERVISOR,0.000000,0.038145,0.038145
Declaration FINAL_APPROVED by DIRECTOR,0.000000,0.037835,0.037835
Declaration FINAL_APPROVED by SUPERVISOR,0.959048,0.924329,-0.034718
Declaration FOR_APPROVAL by ADMINISTRATION,0.000095,0.000000,-0.000095
Declaration FOR_APPROVAL by PRE_APPROVER,0.000095,0.000000,-0.000095
Declaration FOR_APPROVAL by SUPERVISOR,0.000095,0.000000,-0.000095
Declaration REJECTED by ADMINISTRATION,0.080571,0.199566,0.118994
Declaration REJECTED by BUDGET OWNER,0.005524,0.006203,0.000679
Declaration REJECTED by DIRECTOR,0.000000,0.000620,0.000620
Declaration REJECTED by EMPLOYEE,0.115429,0.229958,0.114530
Declaration REJECTED by MISSING,0.008286,0.015196,0.006910
Declaration REJECTED by PRE_APPROVER,0.007714,0.012715,0.005001
Declaration REJECTED by SUPERVISOR,0.026762,0.018918,-0.007844
Declaration SAVED by EMPLOYEE,0.012857,0.011630,-0.001227
Declaration SUBMITTED by EMPLOYEE,0.987143,0.988525,0.001382

declaration_by_start_month

                           cases  mean_days  median_days  min_days  \
log           start_month
domestic      2017-01        122   3.450613     0.004161  0.000000
              2017-02        168   4.263271     0.000949  0.000023
              2017-03        191   1.971969     0.013021  0.000000
              2017-04        174   1.437844     0.001921  0.000000
              2017-05        201   4.850752     0.002766  0.000000
              2017-06        225   4.993548     0.009340  0.000000
              2017-07        149   4.117909     0.004051  0.000000
              2017-08         87   2.326216     0.001400  0.000023
              2017-09        222   2.377300     0.000712  0.000000
              2017-10        215   2.361564     0.008924  0.000000
              2017-11        244   2.615174     0.001574  0.000000
              2017-12        242   5.078754     0.005116  0.000000
              2018-01        564   6.396998     1.970590  0.000000
              2018-02        669   5.937706     1.978843  0.000000
              2018-03        685   5.136924     1.792558  0.000000
              2018-04        756   5.177850     1.974844  0.000000
              2018-05        634   5.605149     1.944468  0.000000
              2018-06        914   5.851919     2.726377  0.000000
              2018-07        682   6.223602     1.955208  0.000000
              2018-08        296   6.066717     2.749479  0.000000
              2018-09        641   5.396917     2.855949  0.000000
              2018-10        804   4.631662     2.578652  0.000000
              2018-11        851   4.861393     2.841817  0.000000
              2018-12        764   5.182176     2.499971  0.000000
international 2017-01         53   3.399232     0.024699  0.000000
              2017-02        120   1.046497     0.003275  0.000000
              2017-03         91   2.334383     0.769525  0.000000
              2017-04         89   4.798857     0.616956  0.000000
              2017-05        105   5.936858     0.970764  0.000000
              2017-06        145   5.998710     0.264884  0.000000
              2017-07        144   6.323570     0.784444  0.000000
              2017-08         67   4.683146     1.162604  0.000035
              2017-09        160   6.875657     0.778096  0.000000
              2017-10        153   3.386849     0.880903  0.000000
              2017-11        109   3.688174     0.735949  0.000035
              2017-12        105   3.056693     0.151227  0.000035
              2018-01        238   8.112295     4.889468  0.000000
              2018-02        297   7.999399     3.769931  0.000000
              2018-03        381   6.958655     3.701065  0.000000
              2018-04        459   6.355215     2.460243  0.000000
              2018-05        397   8.420655     4.148727  0.000000
              2018-06        572   8.845556     4.165035  0.000000
              2018-07        543  10.541143     5.062106  0.000000
              2018-08        335  11.734953     6.836238  0.000000
              2018-09        535  10.683913     6.802454  0.000000
              2018-10        522   7.538129     5.060463  0.000000
              2018-11        472   8.068658     5.655943  0.000000
              2018-12        357   6.894237     3.999942  0.000000

                             max_days   p90_days
log           start_month
domestic      2017-01      146.986713   7.124354
              2017-02      337.101956   4.891584
              2017-03       73.729653   4.023438
              2017-04       24.163021   5.164847
              2017-05      133.146019   7.004954
              2017-06      362.876794   6.792120
              2017-07      171.679826   6.756465
              2017-08       37.719525   6.525898
              2017-09      106.983484   4.003948
              2017-10       87.024410   4.705410
              2017-11      174.960197   2.901260
              2017-12      280.803299  10.068959
              2018-01      469.236319   9.068557
              2018-02      219.822072  10.818234
              2018-03      249.980451   8.703153
              2018-04      250.865660   8.603142
              2018-05      225.095602  10.586515
              2018-06      173.600961  11.996406
              2018-07      282.642627  11.710161
              2018-08      141.065613  11.680822
              2018-09       92.110498  10.855741
              2018-10       78.036505  10.151219
              2018-11      194.830787   9.177836
              2018-12      114.757766  11.892079
international 2017-01       36.906655   8.349523
              2017-02       18.582465   3.175016
              2017-03       41.878322   5.036852
              2017-04       84.050208  10.741648
              2017-05       94.026215  15.671127
              2017-06      153.108079  13.721250
              2017-07      156.885648  13.904443
              2017-08       68.664132  11.353257
              2017-09      216.190359  12.646167
              2017-10       49.799502   9.785252
              2017-11       72.869375   7.733907
              2017-12      111.074259   6.503521
              2018-01       97.086412  15.278738
              2018-02      426.870637  13.972123
              2018-03      163.883252  15.044549
              2018-04       86.059039  14.217833
              2018-05      203.363229  16.484757
              2018-06      174.909468  18.014867
              2018-07      232.173843  28.932664
              2018-08      132.118356  29.679829
              2018-09      348.588218  20.994292
              2018-10       89.911273  15.899177
              2018-11      222.889861  17.030955
              2018-12       64.929213  17.076234

Aufgabe 8

In [24]:
# Frage 8: Dateninventar bereits in Zelle 3 (field_summary) und Zelle 4 (Wertevielfalt).
# Essenz: Aktivitaet, Zeitstempel, Resource/Role sowie Fall-IDs und Finanz-/Permit-Attribute.
# Keine expliziten Ablehnungsgruende oder lifecycle:transition fuer Start/Ende der Arbeit.
# Daher keine saubere Trennung von Warte- und Bearbeitungszeit aus diesen Feldern.
# Welche weiteren Informationen fachlich benoetigt werden, ist keine reine Python-Berechnung.

Aufgabe 9

Aufgabe 10

Aufgabe 11